[[configure_lbaas]]
= Load-Balancer-as-a-Service（LBaaS）を構成する

[IMPORTANT]
OpenStack ドキュメント
http://docs.openstack.org/admin-guide-cloud/networking_config-agents.html#configure-load-balancer-as-a-service-lbaas[Configure Load-Balancer-as-a-Service (LBaaS)]
の指示に従ってください。ただし、*次の違いに注意してください*。

. *エージェントをインストールする*
+
====
適用*しないでください*。

その代わりに python-neutron-lbaas のパッケージをインストールします。

[source]
----
# yum install python-neutron-lbaas
----
====

. */etc/neutron/neutron.conf ファイルで service_provider オプションを使用し、HAProxy プラグインを有効にします。*
+
====
適用*しないでください*。

その代わりに `service_provider` を次のように設定します。
[source]
----
[service_providers]
service_provider = LOADBALANCER:Midonet:midonet.neutron.services.loadbalancer.driver.MidonetLoadbalancerDriver:default
----
====

. */etc/neutron/neutron.conf ファイルで service_plugins オプションを使用し、負荷分散プラグインを有効にします。*
+
====
現状のまま適用します。
====

. */etc/neutron/lbaas_agent.ini ファイルで HAProxy ロードバランサーを有効にします。*
+
====
適用*しないでください*。
====

. *必要なドライバーを /etc/neutron/lbaas_agent.ini ファイルで選択します。*
+
====
適用*しないでください*。
====

. *必要なテーブルをデータベースに作成します。*
+
====
適用*しないでください*。
====

. *neutron-server サービスと neutron-lbaas-agent サービスを再起動し、設定を適用します。*
+
====
適用*しないでください*。
====

. *ダッシュボードの Project セクションで負荷分散を有効にします。*
+
====
現状のまま適用します。
====

. *インストールをファイナライズするには*
+
====
xref:neutron_controller_node_installation_finalize[Neutron Controller Node
Installation] の説明に従って、インストールをファイナライズします。
====
