[[neutron_controller_node_installation]]
= Controller Node

[IMPORTANT]
Follow the OpenStack documentation's
https://www.suse.com/documentation/suse-openstack-cloud-6/book_cloud_deploy/data/sec_depl_ostack_nova.html[Deploying Nova]
instructions, but *note the following differences and additions*.

. *Prerequisites*
+
====
Apply as is.
====

. *Configure networking options*
+
====
Do *not* apply.

.. Instead, install the following packages:
+
[source]
----
# zypper install openstack-neutron python-networking-midonet python-neutronclient
----
+
.. Configure the server component:
+
Edit the `/etc/neutron/neutron.conf` file and configure the following keys:
+
[literal,subs="quotes"]
----
[DEFAULT]
...
core_plugin = *midonet.neutron.plugin_v2.MidonetPluginV2*
service_plugins = *midonet.neutron.services.l3.l3_midonet.MidonetL3ServicePlugin*
...
dhcp_agent_notification = False
...
allow_overlapping_ips = True
...
rpc_backend = rabbit
...
auth_strategy = keystone
...
notify_nova_on_port_status_changes = True
notify_nova_on_port_data_changes = True
nova_url = http://**_controller_**:8774/v2

[database]
...
connection = postgresql://neutron:**_NEUTRON_DBPASS_**@*_controller_*/neutron

[oslo_messaging_rabbit]
...
rabbit_host = *_controller_*
rabbit_userid = openstack
rabbit_password = *_RABBIT_PASS_*

[keystone_authtoken]
...
auth_uri = http://**_controller_**:5000
auth_url = http://**_controller_**:35357
auth_plugin = password
project_domain_id = default
user_domain_id = default
project_name = service
username = neutron
password = *_NEUTRON_PASS_*

[nova]
...
auth_url = http://**_controller_**:35357
auth_plugin = password
project_domain_id = default
user_domain_id = default
region_name = RegionOne
project_name = service
username = nova
password = *_NOVA_PASS_*

[oslo_concurrency]
...
lock_path = /var/lib/neutron/tmp
----

[NOTE]
=====
When using multiple service plugins, separate them with commas:

[source]
----
[DEFAULT]
service_plugins = foo,bar,midonet.neutron.services.l3.l3_midonet.MidonetL3ServicePlugin
----
=====
====

. *Configure the MidoNet plug-in*
+
====
.. Create the directory for the MidoNet plugin:
+
[source]
----
mkdir /etc/neutron/plugins/midonet
----
+
.. Create the `/etc/neutron/plugins/midonet/midonet.ini` file and edit it to
contain the following:
+
[literal,subs="quotes"]
----
[DATABASE]
sql_connection = postgresql://neutron:**_NEUTRON_DBPASS_**@*_controller_*/neutron

[MIDONET]
# MidoNet API URL
midonet_uri = http://*_controller_*:8080/midonet-api
# MidoNet administrative user in Keystone
username = *_midonet_*
password = *_MIDONET_PASS_*
# MidoNet administrative user's tenant
project_id = service
----
+
.. Create a symbolic link to direct Neutron to the MidoNet configuration:
+
[source]
----
# ln -s /etc/neutron/plugins/midonet/midonet.ini /etc/neutron/plugin.ini
----
====

. *Configure the metadata agent*
+
====
Do *not* apply.
====

. *To configure Compute to use Networking*
+
====
Apply as is.
====

. *Configure Load-Balancer-as-a-Service (LBaaS)*
+
====
Additionally to the OpenStack Installation Guide, configure
Load-Balancer-as-a-Service (LBaaS) as described in xref:configure_lbaas[].
====

. *To finalize installation* [[neutron_controller_node_installation_finalize]]
+
====
Do *not* apply.

Instead, perform the following steps.

.. Populate the database:
+
[source]
----
# su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/midonet/midonet.ini upgrade head" neutron
# su -s /bin/sh -c "neutron-db-manage --subproject networking-midonet upgrade head" neutron
----
+
.. Restart the Compute service:
+
[source]
----
# service openstack-nova-api restart
----
+
.. Start the Networking service and configure it to start when the system boots:
+
[source]
----
# service neutron-server start
----
====

