= コントローラノード

[IMPORTANT]
Red Hatの文書のhttps://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/6/html/Deploying_OpenStack_Learning_Environments/sect-Install_a_Compute_Node.html[8.3. Install a Compute Node]の指示に従います。ただし、*次の追加事項と追加事項に注意してください。*

. *8.3.1. Compute Service Databaseを作成する*
+
====
このまま適用します。
====

. *8.3.2. Compute Serviceの認証を構成する*
+
====
このまま適用します。
====

. *8.3.3. Compute Serviceパッケージをインストールする*
+
====
そのまま適用*しないで*ください。

代わりに、次のパッケージのみインストールします。

[source]
----
# yum install openstack-nova-api openstack-nova-conductor openstack-nova-scheduler python-cinderclient
----

[NOTE]
代わりに、`openstack-nova-compute`パッケージがコンピュートノードにインストールされます。
====

. *8.3.4. Compute ServiceのSSLの使用を構成する*
+
====
このまま適用します。
====

. *8.3.5. Compute Serviceを構成する*
+
====
このまま適用します。
====

. *8.3.6. Compute Service Databaseを追加する*
+
====
このまま適用します。
====

. *8.3.7. コンピュートサービスを開始する*
+
====
.. *1. Message Bus Serviceの開始*
+
適用*しないで*ください。 コンピュートノードでのみ必要です。

.. *2. Libvirtd Serviceの開始*
+
適用*しないで*ください。 コンピュートノードでのみ必要です。

.. *3. API Serviceの開始*
+
このまま適用します。

.. *4. スケジューラの開始*
+
このまま適用します。

.. *5. コンダクタの開始*
+
このまま適用します。

.. *6. Compute Serviceの開始*
+
適用*しないで*ください。 コンピュートノードでのみ必要です。
====

{empty} +

[[nova_metadata_proxy]]
. *追加の変更*
+
====
.. *メタデータプロキシを構成する*
+
`/etc/nova/nova.conf` ファイルを修正して次を含めます。
+
[literal,subs="quotes"]
----
[neutron]
...
service_metadata_proxy = true
metadata_proxy_shared_secret = *_METADATA_SECRET_*
----
+
[NOTE]
xref:neutron_metadata_proxy[Metadata Proxy configuration]と同じ*_METADATA_SECRET_*を使用します。
+
Compute APIサービスを再開します。
+
[source]
----
# systemctl restart openstack-nova-api
----
====

