[[viewing_routes]]
= ルートの表示

MidoNet内のそれぞれの仮想ルーターで定義されたルートを表示できます。例えば、仮想ブリッジや、テナントルーターやMidoNet Providerルーターのような他のルーターへのルートについてのインフォメーションを表示できます。

現在のテナントのルーターについてのインフォメーションを表示するため、

. 現在のテナントへのルーターをリスト化するため下記のコマンドを入力します。
+
[source]
midonet> list router
router router0 name tenant-router state up infilter chain0 outfilter chain1

. ルーターへのルートリスト、この場合はテナントルーター（ルーター0）をリスト化するため下記のコマンドを入力します。
+
[source]
midonet> router router0 list route
route route0 type normal src 0.0.0.0/0 dst 169.254.255.2 port router0:port0 weight 0
route route1 type normal src 0.0.0.0/0 dst 0.0.0.0/0 port router0:port0 weight 100
route route2 type normal src 0.0.0.0/0 dst 172.16.3.0/24 port router0:port1 weight 100
route route3 type normal src 172.16.3.0/24 dst 169.254.169.254 gw 172.16.3.2 port router0:port1 weight 100
route route4 type normal src 0.0.0.0/0 dst 172.16.3.1 port router0:port1 weight 0

ルートリストは下記のインフォメーションを示します。

* トラフィックをマッチするためのソース(src)。ルート3はマッチする特定のソースネットワークを示します。 0.0.0.0/0は全てのネットワークからのトラフィックとマッチするという意味です。

* このトラフィックのデスティネーション(dst)。これはネットワークまたは特定のインターフェースとなります。

** ルート0は特定のインターフェースへのルートの例を表示します。これは、link-localアドレスへのルートで、この例で言うと、MidoNet プロバイダールーターで見られます。

** ルート2は172.16.3.0/24ネットワークへのルートを示し、そしてこのネットワークはプライベートネットワークとなります。

** ルート1の内容は、次のとおりです。 全てのネットワーク(0.0.0.0/0)にマッチして全てのネットワーク(0.0.0.0/0)のデスティネーションを持つトラフィックについて、このトラフィックをMidoNet プロバイダールーターでみられる、ポート1に転送します。 ソースIPアドレスにマッチするトラフィックについて、MidoNetはデスティネーションプレフィックスがパケットのデスティネーションにマッチし、かつ最長のマスク（すなわち最長プレフィックスマッチング）を持つルートを見つけます。もしルーターが0.0.0.0より長いプレフィックスを持つデスティネーションが見つけられなかった場合、ルーターはデフォルトのルートにこのトラフィックを送ります。

* ルーターに直接接続されていないデスティネーションについて、デスティネーションへのゲートウェイへのインターフェースが表示されます（ネクストホップゲートウェイ）。

** ルート3は例を示します。このルートの内容は次のとおりです。プライベートネットワークよりのトラフィックである、172.16.3.0/24ネットワークにマッチするソースをもち、メタデータサービスへのlink-localアドレス169.254.169.254がデスティネーションであるトラフィックについて、メタデータサービスへのテナントルーターのインターフェースであるゲートウェイポート172.16.3.2に転送してください。

** ルート4の内容は次のとおりです。 プライベートネットワークへのテナントルーターのインターフェースである、テナントルーターインターフェースのデスティネーション(172.16.3.1)をもった任意のネットワーク(0.0.0.0/0)でのトラフィックについて、このトラフィックをポート1へ転送してください。テナントルーター上のポート1はMidoNet プロバイダールーターである、ルーター1のポート0で見られます。 

