[[routing_process_overview]]
= ルーティングプロセス概要

ルーターポートに進入するトラッフィックについて、ルーターは以下を行います:

* 与えられたパケットの送信元と送信先に基づき、そのパケットのデスティネーションとルーティングテーブル内のルートをマッチしようとします。

* マッチするルートがひとつ以上あるパケットに関しては、パケットを送るにあたってルートのウェイト値に基づいてランダムに選んだものを使います。

* マッチするソースとデスティネーションのルートとマッチしないパケットに関してはパケットをドロップします。

ルーターはルーティングテーブル内の以下のフィールドの情報を使います:

* ソース: 直接接続されたネットワークとホストへのデリバリー、もしくは他のネットワークへのゲートウェイへ転送するため、IPアドレスとネットワークを定義してフィルターをかけて評価します。  

* ルートタイプ: パケットに対してとるアクションを決定します。

* ネクストホップポートとネクストホップゲートウェイ: パケットをどこに送るか決定します。

下記はテナントルーター上の２つのサンプルルートになります(MidoNet CLIを使って表示されています):

[source]
route route2 type normal src 0.0.0.0/0 dst 172.16.3.0/24 port router0:port1 weight 100
route route3 type normal src 172.16.3.0/24 dst 169.254.169.254 gw 172.16.3.2 port router0:port1 weight 100

++++
<?dbhtml stop-chunking?>
++++

== ソース

ソースベースルーティングについてはルートのソースプレフィックスを示します。どのルートがパケットに適用されるかを決めるアルゴリズムは簡単に述べると以下のようになります:

. ソースプレフィックスがパケットのソースとマッチしない全てのルートは無視します。0.0.0.0/0というソースプレフィックスは全てにマッチします。/0は長さがゼロのビットマスクを意味するので、アドレス0.0.0.0は無視されます。

. デスティネーションプレフィックスがパケットのデスティネーションとマッチし、最長マスク (別名・最長プレフィックスマッチング)をもつルートを見つけます。

. もし（同じデスティネーションプレフィックスマスクの長さである）ルート候補がひとつ以上ある場合は、ルートのウェイトフィールドに基づき、重み付きランダムセレクションを使います。

== タイプ

３タイプ: ノーマル、ブラックホール、リジェクトがあります。

* ノーマル: パケットを転送するための通常タイプのルートです。パケットを送るために、ネクストホップゲートウェイとネクストホップポート情報を使います。

* ブラックホール: パケットがこのルートにマッチしたときには通知を送ることなくパケットをドロップするべきであると示します。もし外部ネットワークにフローティングIPアドレスが存在しない場合には、トラフィックはブラックホールに送られそこでドロップされます。

* リジェクト:パケットがこのルートとマッチする場合を除き、ブラックホールと同様ルーターはICMPエラーを返します(MidoNetはフローの最初のパケットを受信したときまたはフローが再計算されたときにエラーを送るのみです)。エラーはタイプ3で (デスティネーションポートに届かなかったことを意味します)、ルートのデスティネーションプレフィックスが32ビットのマスクを持っている(すなわち、特定のホスト= コード10)または32ビット以下のマスクを持っている(ネットワーク = コード9)次第で、コードはコード9もしくはコード10(デスティネーションホスト/ネットワークが管理上禁止されているものです)です。詳しい情報についてはhttp://en.wikipedia.org/wiki/ICMP_Destination_Unreachable#Destination_unreachableをご参照ください。

== 送信先

ピアデバイス (ルーターやブリッジなど)に接続されているインターフェースのIPアドレスを示します。 これはデスティネーションピアに送られたパケットの放出ポートです。

== ネクストホップゲートウェイ

パケットに何を行うかに関してルートは３つのオプションを持っています:

. パケットをドロップします。このケースの場合、ネクストホップゲートウェイは必要ありません。

. パケットをデスティネーションに直接転送します;これはデスティネーションがルーターのポートのうちのひとつとして同じL2ネットワークにある場合にのみ発生します。通常これはパケットのデスティネーションアドレスがルーターのポートと同じネットワークプレフィックス内にあるということです。同じく、ネクストホップゲートウェイは必要ありません。

. パケットをデスティネーションに送りますが、中間ルーターを使います。このようなルートは”ネクストホップゲートウェイ”として知られています。

ネクストホップゲートウェイは、このルートを持っているルーターに向いた中間ルーターのポートのIPアドレスです。このIPアドレスはARP resolutionを行うため (IPアドレスをMACアドレスにマッピングします) と、中間ルーターにパケットを放つ前にどのようにそのデスティネーションMACアドレスを書き換えるのかを決めるためだけに使われます。

通常のルーター（＝物理的なルーター）のルートはターゲット/デスティネーション仮想ポートを持っていない (MidoNetの'Normal'ルートは持っています。"タイプ"をご参照ください).という点において MidoNetの仮想ルーターとは違うということを留意してください。従って、通常のルーターはパケットを放つのにどのポートが使われるべきかを決めるために、ネクストホップゲートウェイIPアドレスを使います(ポートのプレフィックスはネクストホップゲートウェイのIPアドレスにマッチします).

== ネクストホップポート

ピアデバイスに接続されているポートのIDを表示します。

== ウェイト

複数のパスがあるデスティネーションのロードバランシングに使われます。高いウェイト値は望ましいパス（例えば、高い帯域幅）を識別します。デフォルトのウェイト値は100です。”ソース”もご参照ください。
