[[concept_e3j_tpd_q4]]

=プロバイダールーターへの対応

MidoNet プロバイダールーターは通常アドミンテナントにて設定されます。

MidoNetプロバイダールーターを見る必要があれば、MidoNet プロバイダールーターが設定されているテナントに切り替えるため、セットコマンドもしくは他の方法を使ってください。

現在のテナント上のルーターをリスト化するには、コマンドを入力します。

[source]
midonet> list router
router router1 name MidoNet Provider Router state up

MidoNetプロバイダールーターポートをリスト化するには、コマンドを入力します。

[source]
midonet> router router1 list port
port port0 device router1 state up mac 02:fb:21:dc:49:62 address 169.254.255.1 net 169.254.255.0/30 peer router0:port0
port port1 device router1 state up mac 02:f3:fa:89:34:c6 address 198.51.100.1 net 198.51.100.0/24 peer bridge0:port0

上記のアウトプットが示すのは:

* ポート0は169.254.255.1 link-localアドレス経由でルーター0 (テナントルーター)と見られています。
* ポート1ブリッジ0上のポート0と見られています。

ブリッジ0に関するインフォメーションをリスト化するには、以下のコマンドを入力します。

[source]
midonet> show bridge bridge0
bridge bridge0 name demo-ext-net state up

demo-ext-netは外部のパブリックネットワークです。

ブリッジ0に関するインフォメーションをリスト化するにはコマンドを入力します。

[source]
midonet> bridge bridge0 list port
port port1 device bridge0 state up
port port2 device bridge0 state up
port port0 device bridge0 state up peer router1:port1

上記のアウトプットが示すのは:

* ブリッジ0には3つのポートがあります。
* ブリッジ0上のポート0はルーター1(MidoNet プロバイダールーター)上のポート1と見られています。

MidoNet プロバイダールータールートをリスト化するには、以下のコマンドを入力します。

[source]
midonet> router router1 list route
route route0 type blackhole src 0.0.0.0/0 dst 198.51.100.0/24 weight 100
route route1 type normal src 0.0.0.0/0 dst 198.51.100.3 port router1:port0 weight 100
route route2 type normal src 0.0.0.0/0 dst 169.254.255.1 port router1:port0 weight 0
route route3 type normal src 0.0.0.0/0 dst 198.51.100.2 port router1:port0 weight 100
route route4 type normal src 0.0.0.0/0 dst 198.51.100.1 port router1:port1 weight 0

下記はこれらのルートに関するいくつかの注意点です。

* フローティングIPアドレスが外部ネットワークに存在しない場合、タイプ =ブラックホールであり、トラフィックはブラックホールにルートされ、トラフィックはそこでドロップされます。この場合、マッチする送信元は任意のネットワーク(0.0.0.0/0)で、送信先は外部のパブリックネットワークである198.51.100.0/24ネットワークです。

* ルート1はVMのフローティングIPアドレス(198.51.100.3)へのルートを示します。

* ルート2はテナントルーターへのlink-localコネクション(169.254.255.1)へのルートを示します。

* ルート3は外部のネットワークへのゲートウェイを示します。

* ルート4が言っていることは以下になります: 任意の送信元ネットワーク(0.0.0.0/0)と送信先198.51.100.1にマッチするトラフィック（MidoNet Provider Routerの外部ネットワーク(198.51.100/24) (demo-ext-net, bridge0)へのインターフェース）について、このトラフィックをネットワークへのルーターのインターフェース（ブリッジ1）であるポート1に転送してください。

実在のデプロイメントでは、MidoNet プロバイダールーターに接続されたほとんどのポートはアップリンクポートで、通常複数のアンリンクポートがあります(上記で説明されているネットワークの例では、ネットワークはアップリンクポートに接続されていません。) MidoNetの外に接続を持つ他の仮想ポートのように、それぞれのポートはデバイス（イーサーネットインターフェース）とホストに接続されています。このホストはサービスプロバイダーへつながるアップストリームルータへと物理的につながっているゲートウェイノードです。
