[[concept_e3j_tpd_q4]]

= Working with the Provider Router

The MidoNet Provider Router is typically configured in the Admin tenant.

To look at the MidoNet Provider Router, if necessary, use the sett command or
some other means to switch to the tenant on which the MidoNet Provider Router is
configured.

To list the routers on the current tenant, enter the command:

[source]
midonet> list router
router router1 name MidoNet Provider Router state up

To list the MidoNet Provider Router ports, enter the command:

[source]
midonet> router router1 list port
port port0 device router1 state up mac 02:fb:21:dc:49:62 address 169.254.255.1 net 169.254.255.0/30 peer router0:port0
port port1 device router1 state up mac 02:f3:fa:89:34:c6 address 198.51.100.1 net 198.51.100.0/24 peer bridge0:port0

The above output shows:

* port0 is peered with router0 (tenant-router) via the 169.254.255.1 link-local
address.
* port1 is peered with port0 on bridge0.

To list information about bridge0, enter the command:

[source]
midonet> show bridge bridge0
bridge bridge0 name demo-ext-net state up

demo-ext-net is an external, public network.

To list the port information for bridge0, enter the command:

[source]
midonet> bridge bridge0 list port
port port1 device bridge0 state up
port port2 device bridge0 state up
port port0 device bridge0 state up peer router1:port1

The above output shows:

* Three ports on bridge0.
* port0 on bridge0 is peered with port1 on router1 (the MidoNet Provider
Router).

To list the MidoNet Provider Router routes, enter the command:

[source]
midonet> router router1 list route
route route0 type blackhole src 0.0.0.0/0 dst 198.51.100.0/24 weight 100
route route1 type normal src 0.0.0.0/0 dst 198.51.100.3 port router1:port0 weight 100
route route2 type normal src 0.0.0.0/0 dst 169.254.255.1 port router1:port0 weight 0
route route3 type normal src 0.0.0.0/0 dst 198.51.100.2 port router1:port0 weight 100
route route4 type normal src 0.0.0.0/0 dst 198.51.100.1 port router1:port1 weight 0

Below are some notes about these routes:

* type = blackhole If no floating IP addresses exist on an external network,
traffic is routed to a blackhole, where the traffic is dropped. In this case,
the source to match is any network (0.0.0.0/0) and the destination is the
198.51.100.0/24 network, which is an external, public network.

* route1 shows the route to the floating IP address (198.51.100.3) of a VM.

* route2 shows the route to the link-local connection (169.254.255.1) to the
tenant router.

* route3 shows the route to the gateway to the external network.

* route4 says: for traffic that matches the source any network (0.0.0.0/0) with
the destination 198.51.100.1, which is the MidoNet Provider Router's interface
to the external network (198.51.100/24) (demo-ext-net, bridge0), forward this
traffic to port1, which is the router's interface to the network (bridge0).

In a real deployment , most of the ports connected to the MidoNet Provider
Router are up-link ports, and typically there are multiple unlink ports. (In the
example network described above, the network is not connected to up-link ports.)
Like other virtual ports with connections outside of MidoNet, each port is bound
to a device (Ethernet interface) and a host. The host is a Gateway Node that is
physically connected to the upstream router that goes out to a service provider.
