[[routing_process_overview]]
= ルーティングプロセス概要

ルーターポートに進入するトラッフィックについて、ルーターは下記動作を行います。

* 与えられたパケットの送信元と送信先に基づき、パケットとルーティングテーブル内のルートをマッチ
します。低いウェイトを持つルートが優先されます。

* マッチするルートが一つ以上あるパケットに関しては、パケットを送るにあたってルートのウェイトに
基づいてランダムに選んだものを使用します。

* 該当する送信元と宛先とを持つルートが存在しない場合、パケットをドロップします。

ルーターはルーティングテーブル内の以下のフィールドの情報を使います。

* ソース: パケット送信元IPアドレス・プレフィックスをフィルターします。

* ルートタイプ: パケットに対してのアクションを決定します。

* ネクストホップポートとネクストホップゲートウェイ: パケットをどこに送るか決定します。

下記は、テナントルーター上の２つのサンプルルートです（MidoNet CLIを使って表示されています）。

[source]
route route2 type normal src 0.0.0.0/0 dst 172.16.3.0/24 port router0:port1 weight 100
route route3 type normal src 172.16.3.0/24 dst 169.254.169.254 gw 172.16.3.2 port router0:port1 weight 100

++++
<?dbhtml stop-chunking?>
++++

== ソース

ルーティングに用いられる送信元IPプレフィックスを表示します。ルート選択のアルゴリズムは以下の通りです。

. ソースプレフィックスがパケットの送信元アドレスとマッチしないルートは無視します。0.0.0.0/0
というソースプレフィックスは全てにマッチします。

. 送信先IPアドレスのプレフィックスがパケットの送信先とマッチし、最長マスク（別名・
最長プレフィックスマッチング）を持つルートを見つけます。

. もし（送信先IPアドレスプレフィックスのマスク長が同じであるような）ルート候補が一つ以上ある場合は、
ルートのウェイトに基づき、重み付きランダムセレクションを使います。

. 複数のルート候補がある場合（かつ送信先のサブネットのマスク長とウェイトが同じ場合）、
ルートを選択するためにエージェントごとにラウンドロビンを使用します。

== タイプ

３タイプ: ノーマル、ブラックホール、リジェクトがあります。

* ノーマル: パケットを転送するための通常タイプのルートです。パケットを送るために、
ネクストホップゲートウェイとネクストホップポート情報を使います。

* ブラックホール: パケットがこのルートにマッチした場合は通知を送ることなくパケットをドロップ
するべきであると示します。もし外部ネットワークにフローティングIPアドレスが存在しない場合は、
パケットはブラックホールに送られそこでドロップされます。

* リジェクト:パケットがこのルートとマッチする場合を除き、ブラックホールと同様にルーターはICMPエラー
を返します（MidoNetはフローの最初のパケットの受信時、あるいはフロー再計算時のみエラー
を送ります）。エラーはタイプ3で（送信先ポートに届かなかったことを意味します）、ルートの
送信先IPアドレスプレフィックスが32ビットのマスクを持っている（すなわち特定のホスト = コード10）、
または32ビット以下のマスクを持っている（ネットワーク = コード9）ので、コードはコード9もしくは
コード10（送信先ホスト/ネットワークが管理上禁止されているものです）です。詳しい情報については
http://en.wikipedia.org/wiki/ICMP_Destination_Unreachable#Destination_unreachable
をご参照ください。

== 送信先

ピアデバイス（ルーターやブリッジなど）に接続されているインターフェースのIPアドレスを示します。
これは送信先ピアに送られたパケットの放出ポートです。

== ネクストホップゲートウェイ

ネクストホップゲートウェイは、このルーターと中継ルーターとを接続する中継ルータのポートの
IPアドレスです。このIPアドレスはARP解決を行うため（IPアドレスをMACアドレスにマッピングします）
と、中継ルーターにパケットを送信する前にどのようにその送信先MACアドレスを書き換えるのかを
決めるためだけに使われます。

通常のルーター（すなわち物理的なルーター）のルートは送信先仮想ポートを持っていないという点において、
MidoNetの仮想ルーターとは違うということを留意してください。
（MidoNetの「ノーマル」 ルートは持っています。"タイプ" の項目をご参照ください。）
従って、物理ルーターはパケット送信ポートを決定するのに、ネクストホップゲートウェイIPアドレスを
使います（ネクストホップゲートウェイIPアドレスにマッチするIPアドレスを持つポートが選択されます）。

パケットに何を行うかに関してルートは３つのオプションを持っています。

. パケットをドロップします。このケースの場合、ネクストホップゲートウェイは必要ありません。

. パケットを送信先に直接転送します。これは送信先がルータのポートの
一つとして同じL2ネットワークにある場合にのみ発生します。通常これはパケットの
送信先アドレスがルーターのポートと同じネットワークプレフィックス内にあるということです。
同じく、ネクストホップゲートウェイは必要ありません。

. パケットをデスティネーションに送りますが、中継ルーターを使います。このようなルートは
"ネクストホップゲートウェイ" として知られています。

== ネクストホップポート

ピアデバイスに接続されているポートのIDを表示します。

== ウェイト

複数のパスが存在する送信先へのパケットのロードバランシングに使われます。より低いウェイトを持つパスが
優先されるパスとみなされます（例えば高帯域幅のパス）。デフォルトのウェイトは100です。BGPピアから
学習したルート情報の場合は、BGPのAD値がルートのウェイトになります。"ソース" の項目もご参照ください。
