[[neutron_controller_node_installation]]
= コントローラノード

[IMPORTANT]
OpenStackの文書の
http://docs.openstack.org/kilo/install-guide/install/apt/content/neutron-controller-node.html[Install and configure controller node]
の指示に従います。ただし、 *次の相違事項と追加事項に注意してください。*

. *前提条件を設定する場合*
+
====
このまま適用します。
====

. *ネットワーキングのコンポーネントをインストールする場合*
+
====
適用*しないで*ください。

.. 代わりに、次のパッケージをインストールします。
+
[source]
----
# apt-get install neutron-server python-neutronclient python-neutron-plugin-midonet
# apt-get purge neutron-plugin-ml2
----
+
====

. *ネットワーキングのサーバーコンポーネントを構成する場合*
+
====
ステップ 'dを適用*しないで*ください。モジュラーレイヤー2（ML2）プラグイン、ルーターサービスおよび重複するIPアドレスを有効にします。

.. 代わりに、`/etc/neutron/neutron.conf` ファイルを変更して、次のキーを `[DEFAULT]` セクションに設定します。
+
[source]
----
[DEFAULT]
...
core_plugin = midonet.neutron.plugin_v2.MidonetPluginV2
----
+
====
+
[NOTE]
構成ファイルの行の開始にスペースを残さないでください（これはすべての構成ファイルに適用されます）。

. *モジュラーレイヤー2（ML2）のプラグインを構成する場合*
+
====
適用*しないで*ください。

代わりに、次の手順を実行します。

.. MidoNetプラグインのディレクトリを作成します。
+
[source]
----
mkdir /etc/neutron/plugins/midonet
----
+
`/etc/neutron/plugins/midonet/midonet.ini` ファイルを作成し、修正して次を含めます。
+
[literal,subs="quotes"]
----
[DATABASE]
sql_connection = mysql://neutron:**_NEUTRON_DBPASS_**@*_controller_*/neutron

[MIDONET]
# MidoNet API URL
midonet_uri = http://*_controller_*:8181/midonet-api
# MidoNet administrative user in Keystone
username = *_midonet_*
password = *_MIDONET_PASS_*
# MidoNet administrative user's tenant
project_id = service
----
+
.. `/etc/default/neutron-server` ファイルを修正して次を含めます。
+
[source]
----
NEUTRON_PLUGIN_CONFIG="/etc/neutron/plugins/midonet/midonet.ini"
----
+
====

. *コンピュートでネットワーキングの使用を構成する場合*
+
====
このまま適用します。
====

. *インストールを終了する場合* [[neutron_controller_node_installation_finalize]]
+
====
Do *not* apply.

Instead, perform the following steps.

.. Populate the database:
+
[source]
----
# su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/midonet/midonet.ini upgrade head" neutron
----
+
[source]
----
# midonet-db-manage upgrade head
----
+
.. Restart the Compute service:
+
[source]
----
# service nova-api restart
----
+
.. Restart the Networking service:
+
[source]
----
# service neutron-server restart
----
====
