= Controller Node

[IMPORTANT]
Follow the OpenStack documentation's
http://docs.openstack.org/kilo/install-guide/install/apt/content/neutron-controller-node.html[Install and configure controller node]
instructions, but *note the following differences*.

. *To configure prerequisites*
+
====
Apply as is.
====

. *To install the Networking components*
+
====
Do *not* apply.

.. Instead, install the following packages:
+
[source]
----
# apt-get install neutron-server python-neutron-plugin-midonet
----
+
====

. *To configure the Networking server component*
+
====
Do *not* apply step 'd. Enable the Modular Layer 2 (ML2) plug-in, router
service, and overlapping IP addresses'.

.. Instead, edit the `/etc/neutron/neutron.conf` file and add the following key
to the `[DEFAULT]` section:
+
[source]
----
[DEFAULT]
...
core_plugin = neutron.plugins.midonet.plugin.MidonetPluginV2
----
+
====
+
[NOTE]
Make sure to not leave any space at the starting of lines in any configuration
file (this applies to all configuration files).

. *To configure the Modular Layer 2 (ML2) plug-in*
+
====
Do *not* apply.

Instead, perform the following steps.

.. Create the directory for the MidoNet plugin:
+
[source]
----
mkdir /etc/neutron/plugins/midonet
----
+
.. Create the `/etc/neutron/plugins/midonet/midonet.ini` file and edit it to
contain the following:
+
[literal,subs="quotes"]
----
[DATABASE]
sql_connection = mysql://neutron:**_NEUTRON_DBPASS_**@*_controller_*/neutron

[MIDONET]
# MidoNet API URL
midonet_uri = http://*_controller_*:8080/midonet-api
# MidoNet administrative user in Keystone
username = *_midonet_*
password = *_MIDONET_PASS_*
# MidoNet administrative user's tenant
project_id = service
----
+
.. Edit the `/etc/default/neutron-server` file to contain the following:
+
[source]
----
NEUTRON_PLUGIN_CONFIG="/etc/neutron/plugins/midonet/midonet.ini"
----
+
====

. *To configure Compute to use Networking*
+
====
Apply as is.
====

. *To finalize installation*
+
====
Do *not* apply.

Instead, perform the following steps.

.. Populate the database:
+
[source]
----
# su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/midonet/midonet.ini upgrade kilo" neutron
----
+
.. Restart the Compute service:
+
[source]
----
# service nova-api restart
----
+
.. Restart the Networking service:
+
[source]
----
# service neutron-server restart
----
====
