[[midonet_cluster]]
= MidoNet Cluster

The MidoNet Cluster writes log messages to the
`/var/log/midonet-cluster/midonet-cluster.log` file.

++++
<?dbhtml stop-chunking?>
++++

== Debugging

During troubleshooting periods, you can increase the logging level via the
`mn-conf` utility.

The available log levels are: `DEBUG`, `INFO`, `WARN`, `ERROR`

[IMPORTANT]
In production environments it is not recommended to enable DEBUG logging due to
impact on performance, unless it's really required.

=== Single Host

To check the currently configured level for a certain Cluster host, execute the
following command on that host:

[literal,subs="verbatim,quotes"]
----
$ mn-conf get cluster.loggers.root
cluster.loggers.root = *INFO*
----

To increase the log level for this host to `DEBUG`, execute the following
command:

[literal,subs="verbatim,quotes"]
----
$ echo "cluster.loggers.root : *DEBUG*" | mn-conf set
----

This change applies immediately and does not require a Cluster restart.

=== Globally

It is also possible to increase the log level globally (i.e. for all Cluster
hosts) by changing the default template's value:

[literal,subs="verbatim,quotes"]
----
$ echo "cluster.loggers.root : *DEBUG*" | mn-conf set *-t default*
----

Note that if a host has a local log level configured, this will have higher
priority than the template configuration.

To see the current template configuration, execute the following command:

[literal,subs="verbatim,quotes"]
----
$ mn-conf get cluster.loggers.root -t default
cluster.loggers.root = *INFO*
----
