[[midonet_agent]]
= MidoNet Agent

The MidoNet Agent (Midolman) writes log messages to the
`/var/log/midolman/midolman.log` file.

++++
<?dbhtml stop-chunking?>
++++

== Debugging

During troubleshooting periods, you can increase the logging level via the
`mn-conf` utility.

The available log levels are: `DEBUG`, `INFO`, `WARN`, `ERROR`

[IMPORTANT]
In production environments it is not recommended to enable DEBUG logging due to
impact on performance, unless it's really required. If possible always first use
`mm-trace` (see xref:mm_trace[]) which has no performance impact.

=== Single Host

To check the currently configured level for a certain Agent host, execute the
following command on that host:

[literal,subs="verbatim,quotes"]
----
$ mn-conf get agent.loggers.root
agent.loggers.root = *INFO*
----

To increase the log level for this host to `DEBUG`, execute the following
command:

[literal,subs="verbatim,quotes"]
----
$ echo "agent.loggers.root : *DEBUG*" | mn-conf set
----

This change applies immediately and does not require an Agent restart.

=== Globally

It is also possible to increase the log level globally (i.e. for all Agent
hosts) by changing the default template's value:

[literal,subs="verbatim,quotes"]
----
$ echo "agent.loggers.root : *DEBUG*" | mn-conf set *-t default*
----

Note that if a host has a local log level configured, this will have higher
priority than the template configuration.

To see the current template configuration, execute the following command:

[literal,subs="verbatim,quotes"]
----
$ mn-conf get agent.loggers.root -t default
agent.loggers.root = *INFO*
----
