[[nat_rule_chains]]
= NATのルールチェーン情報の閲覧を指します。

テナント用のルーター、そしてルーターに設定されたルールチェーンをリストアップするためにMidoNet CLIを使うことができます。

以下の例では、ソースと行き先NATを実装するためにMidoNetがどのようにルールチェーンを使用するか、またMidoNet CLIをどのように使用するかを説明しています:
* テナントのルーターに設定されたインフィルター（プレルーティング）とアウトフィルター（ポストルーティング）についての情報が表示されています。
* ルールチェーンのためのルールをリストアップします。

++++
<?dbhtml stop-chunking?>
++++

== 仮定事項

下記にある例については、以下のようなネットワークコンディションがあることを仮定します:

* テナントのルーターの名称を"tenant-router”とします。

* プライベートネットワークのアドレスを（172.16.3.0/24）とします。

* パブリックネットワークのアドレスを（198.51.100.0/24）とします。

* プライベートIPアドレスが（172.16.3.3）とパブリック（フローティング）IPアドレス（198.51.100.3）のVMがあります。
== プレルーティングルールを閲覧します。

現在のテナント上のルーター、また、ルーターのルールチェーン情報をリストアップするために、以下のコマンドを入力します:
[source]
midonet> list router
router router0 name tenant-router state up infilter chain0 outfilter chain1

上記のアウトプットにあるように、”chain0”はルーターのプレルーティング（インフィルター）ルールチェーンで、”chain1”はポストルーティング（アウトフィルター）ルールチェーンをあらわしています。

ルーターのプレルーティングルールチェーンについての情報をリストアップするためには、以下のコマンドを入力します:
[source]
midonet> chain chain0 list rule
rule rule0 dst 198.51.100.3 proto 0 tos 0 in-ports router0:port0 pos 1 type dnat action accept target 172.16.3.3
rule rule1 dst 198.51.100.2 proto 0 tos 0 in-ports router0:port0 pos 2 type rev_snat action accept

テナントのルーター上のプレルーティングルールチェーン”rule0”は以下のインストラクションを含みます:

* VMに連携しているフローティングIPアドレスの行き先が（198.51.100.3）のパケット:

** 行き先のIPアドレスをVMのフローティングIPアドレス(198.51.100.3)からVMのプライベートIPアドレス(172.16.3.3)へ変更するために行き先NAT(DNAT)転換を行います。

== ポストルーティングルールを閲覧します。

テナントのルーター上のポストルーティングルールをリストアップするには、以下のコマンドを入力します:
[source]
midonet> chain chain1 list rule
rule rule0 src 172.16.3.3 proto 0 tos 0 out-ports router1:port0 pos 1 type snat action accept target 198.51.100.3
rule rule1 proto 0 tos 0 out-ports router1:port0 pos 2 type snat action accept target 198.51.100.2:1--1

テナントルーター上のポストルーティングルールの”rule0”は以下のインストラクションを含みます:
* ソースIPアドレス（172.16.3.3）からのパケット（VMのプライベートIPアドレス）です:

** VMプライベートIPアドレス(172.16.3.3)からVMフローティングIPアドレス(198.51.100.3)に変更するために、ソースNAT(SNAT)転換を行います。

