[[dnat_revdnat_example]]
= DNAT、REV_DNAT例

ルーター上のDNATとREV_DNATを設定するためにMidoNet CLIコマンドをどのように使うかの例が記載されています。

以下には、本例のルールチェーンについての仮定事項が記載されています。
* パブリックのサブネット(198.51.100.0/24)とプライベートのサブネット(10.0.0.0/24)のふたつのサブネットがあります。

* パブリックのIPアドレス（198.51.100.4）とプライベートのIPアドレス（10.100.1.150）をもつ、テナントのルーターに接続されているバーチャルデバイスがあります。

* トラフィックをVMのパブリックIPアドレスからVMのプライベートIPアドレスに転換します。

* 行き先アドレスの逆転換を行います。

上記にあるDNAT設定のためのルールチェーンの作成方法が記載されています。

. 新たなルールチェーンを作成します。
+
[source]
midonet> chain create name "dnat-test"
chain10

. ルーターポート上の行き先が（198.51.100.4）のトラフィックを承認し、行き先を（10.100.1.150）これに転換するルールを作成します。
+
[source]
midonet> chain chain10 add rule dst 198.51.100.4 in-ports router1:port0 pos 1 type dnat action accept target 10.100.1.150
chain10:rule2

. ルーターのゲートウェイからパブリックネットワークへの行き先をもつトラフィックを承認するルールを作成します。そして、パブリックネットワークアドレスからプライベートネットワークアドレスへとアドレスの逆転換を行います。
+
[source]
midonet> chain chain10 add rule dst 198.51.100.2 in-ports router0:port0 pos 2 type rev_snat action accept
chain10:rule3

. 以下を確認するルールをリストアップします。
+
[source]
midonet> chain chain10 list rule
rule rule2 dst 198.51.100.4 proto 0 tos 0 in-ports router1:port0 pos 1 type dnat action accept target 10.100.1.150
rule rule3 dst 198.51.100.2 proto 0 tos 0 in-ports router0:port0 pos 2 type rev_snat action accept

