[[snat_example]]
= SNATの例を指します。

ルーターポート上のSNATを設定するためにMidoNet CLIをどのように使用するかの例がここに記載されています。

例えば、プライベートIPアドレスとパブリックフローティングIPアドレスをもつVMのようなネットワークデバイス用にSNATを設定します。それらのIPアドレスは自身のもつローカルネットワークの外へとデータを転送します。

本例のルールチェーンについての仮定事項が以下に記載されています:
* パブリックサブネット(198.51.100.0/24)とプライベートサブネット(10.0.0.0/24)の二つサブネットがあります。

* パブリックIPアドレス（198.51.100.4）とプライベートIPアドレス（10.100.1.150）でテナントルーターに接続されているバーチャルデバイスがあります。

* VMのプライベートIPアドレスをVMのパブリックIPアドレスへとトラフィック転換を行います。

上記にあるSNAT設定のためのルールチェーンを作成します:

. 新たなルールチェーンを作成します:
+
[source]
midonet> chain create name "snat-test"
chain7

. 行き先が（10.100.1.150）から（198.51.100.4）に転換されたソースをもつルーターポート上のトラフィックを承認するルールを作成します:
+
[source]
midonet> chain chain7 add rule src 10.100.1.150 out-ports router1:port0 pos 1 type snat action accept target 198.51.100.4
chain7:rule2

. プライベートネットワークからのトラフィックを承認するルールを作成します。そして、ソースIPアドレスをルーターのIP
アドレスへと転換し、それがパブリックネットワークへのゲートウェイになるようにSNATを行います。
+
[source]
midonet> chain chain7 add rule out-ports router1:port0 pos 2 type snat action accept target 198.51.100.2

