[[nova_compute_node]]
= Compute Node

[IMPORTANT]
Follow the Red Hat documentation's
https://access.redhat.com/documentation/en/red-hat-openstack-platform/10/paged/manual-installation-procedures/chapter-8-install-the-compute-service[8.2. Install a Compute Node]
instructions, but *note the following differences and additions*.

. *8.2.1. Install the Compute Service Packages*
+
====
Do *not* apply as is.

Instead, install only the following packages:

[source]
----
# yum install openstack-nova-compute openstack-utils
----
====

. *8.2.2. Create the Compute Service Database*
+
====
Do *not* apply. Has been done on the Controller Node.
====

. *8.2.3. Configure the Compute Service Database Connection*
+
====
Apply as is.
====

. *8.2.4. Create the Compute Service Identity Records*
====
Do *not* apply. Has been done on the Controller Node.
====

. *8.2.5. Configure Compute Service Authentication*
====
Apply as is.
====

. *8.2.6. Configure the Firewall to Allow Compute Service Traffic*
+
====
Apply as is.
====

. *8.2.7. Configure the Compute Service to Use SSL*
+
====
Apply as is.
====

. *8.2.8. Configure RabbitMQ Message Broker Settings for the Compute Service*
+
====
Apply as is.
====

. *8.2.9. Enable SSL Communication Between the Compute Service and the Message Broker*
+
====
Apply as is.
====

. *8.2.10. Configure Resource Overcommitment*
+
====
Apply as is.
====

. *8.2.11. Reserve Host Resources*
+
====
Apply as is.
====

. *8.2.12. Configure Compute Networking*
+
====
Apply as is, except the following topics:

.. *8.2.12.3. Configure the L2 Agent*
+
Do *not* apply.
+
.. *8.2.12.4. Configure Virtual Interface Plugging*
+
Do *not* apply.
====

. *8.2.13. Populate the Compute Service Database*
+
====
Do *not* apply. Has been done on the Controller Node.
====

. *8.2.14. Launch the Compute Services*
+
====
.. *1. Starting the Message Bus Service*
+
Apply as is.

.. *2. Starting the Libvirtd Service*
+
Apply as is.

.. *3. Starting the API Service*
+
Do *not* apply. Only required on the Controller Node.

.. *4. Starting the Scheduler*
+
Do *not* apply. Only required on the Controller Node.

.. *5. Starting the Conductor*
+
Do *not* apply. Only required on the Controller Node.

.. *6. Starting the Compute Service*
+
Apply as is.
====

. *Additionally, perform the following steps*

.. *Configure libvirt*
+
====
Edit the `/etc/libvirt/qemu.conf` file to contain the following:

[literal,subs="quotes"]
----
user = "root"
group = "root"

cgroup_device_acl = [
    "/dev/null", "/dev/full", "/dev/zero",
    "/dev/random", "/dev/urandom",
    "/dev/ptmx", "/dev/kvm", "/dev/kqemu",
    "/dev/rtc","/dev/hpet", "/dev/vfio/vfio",
    *_"/dev/net/tun"_*
]
----
====

.. *Restart the libvirt service*
+
====
[source]
----
# systemctl restart libvirtd.service
----
====

.. *Install nova-rootwrap network filters*
+
====
[source]
----
# yum install openstack-nova-network
# systemctl disable openstack-nova-network.service
----
====

.. *Restart the Compute service*
+
====
[source]
----
# systemctl restart openstack-nova-compute.service
----
====
