[[initial_network_configuration]]
= Initial Network Configuration

Before launching your first instance, you must create the necessary virtual
network infrastructure to which the instances connect, including the external
network and tenant network.

== External Network

The external network typically provides Internet access for your instances. By
default, this network only allows Internet access from instances using Network
Address Translation (NAT). You can enable Internet access to individual
instances using a floating IP address and suitable security group rules. The
`admin` tenant owns this network because it provides external network access for
multiple tenants.

[NOTE]
Perform these commands on the controller node.

. *Create an external network*
+
====
Source the `admin` credentials to gain access to admin-only CLI commands:

[source]
----
$ source admin-openrc.sh
----

Create the network:

[source]
----
$ neutron net-create ext-net --router:external
Created a new network:
+---------------------------+--------------------------------------+
| Field                     | Value                                |
+---------------------------+--------------------------------------+
| admin_state_up            | True                                 |
| id                        | 893aebb9-1c1e-48be-8908-6b947f3237b3 |
| name                      | ext-net                              |
| provider:network_type     | flat                                 |
| provider:physical_network | external                             |
| provider:segmentation_id  |                                      |
| router:external           | True                                 |
| shared                    | False                                |
| status                    | ACTIVE                               |
| subnets                   |                                      |
| tenant_id                 | 54cd044c64d5408b83f843d63624e0d8     |
+---------------------------+--------------------------------------+
----

Like a physical network, a virtual network requires a `subnet` assigned to it.
The external network shares the same subnet and `gateway` associated with the
physical network connected to the external interface on the network node. You
should specify an exclusive slice of this subnet for `router` and floating IP
addresses to prevent interference with other devices on the external network.
====

. *Create a subnet on the external network*
+
====
Create the subnet:

[source]
----
$ neutron subnet-create ext-net EXTERNAL_NETWORK_CIDR --name ext-subnet \
  --allocation-pool start=FLOATING_IP_START,end=FLOATING_IP_END \
  --disable-dhcp --gateway EXTERNAL_NETWORK_GATEWAY
----

Replace `FLOATING_IP_START` and `FLOATING_IP_END` with the first and last IP
addresses of the range that you want to allocate for floating IP addresses.
Replace `EXTERNAL_NETWORK_CIDR` with the subnet associated with the physical
network. Replace `EXTERNAL_NETWORK_GATEWAY` with the gateway associated with the
physical network, typically the ".1" IP address. You should disable `DHCP` on
this subnet because instances do not connect directly to the external network
and floating IP addresses require manual assignment.

For example, using `203.0.113.0/24` with floating IP address range
`203.0.113.101` to `203.0.113.200`:

[source]
----
$ neutron subnet-create ext-net 203.0.113.0/24 --name ext-subnet \
  --allocation-pool start=203.0.113.101,end=203.0.113.200 \
  --disable-dhcp --gateway 203.0.113.1
Created a new subnet:
+-------------------+------------------------------------------------------+
| Field             | Value                                                |
+-------------------+------------------------------------------------------+
| allocation_pools  | {"start": "203.0.113.101", "end": "203.0.113.200"}   |
| cidr              | 203.0.113.0/24                                       |
| dns_nameservers   |                                                      |
| enable_dhcp       | False                                                |
| gateway_ip        | 203.0.113.1                                          |
| host_routes       |                                                      |
| id                | 9159f0dc-2b63-41cf-bd7a-289309da1391                 |
| ip_version        | 4                                                    |
| ipv6_address_mode |                                                      |
| ipv6_ra_mode      |                                                      |
| name              | ext-subnet                                           |
| network_id        | 893aebb9-1c1e-48be-8908-6b947f3237b3                 |
| tenant_id         | 54cd044c64d5408b83f843d63624e0d8                     |
+-------------------+------------------------------------------------------+
----
====

== Tenant Network

The tenant network provides internal network access for instances. The
architecture isolates this type of network from other tenants. The demo tenant
owns this network because it only provides network access for instances within
it.

[NOTE]
Perform these commands on the controller node.

. *Create the tenant network*
+
====
Source the `demo` credentials to gain access to user-only CLI commands:

[source]
----
$ source demo-openrc.sh
----

Create the network:

[source]
----
$ neutron net-create demo-net
Created a new network:
+-----------------+--------------------------------------+
| Field           | Value                                |
+-----------------+--------------------------------------+
| admin_state_up  | True                                 |
| id              | ac108952-6096-4243-adf4-bb6615b3de28 |
| name            | demo-net                             |
| router:external | False                                |
| shared          | False                                |
| status          | ACTIVE                               |
| subnets         |                                      |
| tenant_id       | cdef0071a0194d19ac6bb63802dc9bae     |
+-----------------+--------------------------------------+
----

Like the external network, your tenant network also requires a subnet attached
to it. You can specify any valid subnet because the architecture isolates tenant
networks. By default, this subnet uses DHCP so your instances can obtain IP
addresses.
====

. *Create a subnet on the tenant network*
+
====
Create the subnet:

[source]
----
$ neutron subnet-create demo-net TENANT_NETWORK_CIDR \
  --name demo-subnet --dns-nameserver DNS_RESOLVER \
  --gateway TENANT_NETWORK_GATEWAY
----

Replace `TENANT_NETWORK_CIDR` with the subnet you want to associate with the
tenant network, `DNS_RESOLVER` with the IP address of a DNS resolver, and
`TENANT_NETWORK_GATEWAY` with the gateway you want to associate with the tenant
network, typically the ".1" IP address.

Example using `192.168.1.0/24` with DNS resolver `8.8.4.4` and gateway
`192.168.1.1`:

[source]
----
$ neutron subnet-create demo-net 192.168.1.0/24 \
  --name demo-subnet --dns-nameserver 8.8.4.4 --gateway 192.168.1.1
Created a new subnet:
+-------------------+------------------------------------------------------+
| Field             | Value                                                |
+-------------------+------------------------------------------------------+
| allocation_pools  | {"start": "192.168.1.2", "end": "192.168.1.254"}     |
| cidr              | 192.168.1.0/24                                       |
| dns_nameservers   | 8.8.4.4                                              |
| enable_dhcp       | True                                                 |
| gateway_ip        | 192.168.1.1                                          |
| host_routes       |                                                      |
| id                | 69d38773-794a-4e49-b887-6de6734e792d                 |
| ip_version        | 4                                                    |
| ipv6_address_mode |                                                      |
| ipv6_ra_mode      |                                                      |
| name              | demo-subnet                                          |
| network_id        | ac108952-6096-4243-adf4-bb6615b3de28                 |
| tenant_id         | cdef0071a0194d19ac6bb63802dc9bae                     |
+-------------------+------------------------------------------------------+
----
====

. *Create a router on the tenant network and attach the external and tenant networks to it*
+
====
[source]
----
$ neutron router-create demo-router
Created a new router:
+-----------------------+--------------------------------------+
| Field                 | Value                                |
+-----------------------+--------------------------------------+
| admin_state_up        | True                                 |
| external_gateway_info |                                      |
| id                    | 635660ae-a254-4feb-8993-295aa9ec6418 |
| name                  | demo-router                          |
| routes                |                                      |
| status                | ACTIVE                               |
| tenant_id             | cdef0071a0194d19ac6bb63802dc9bae     |
+-----------------------+--------------------------------------+
----

Attach the router to the demo tenant subnet:

[source]
----
$ neutron router-interface-add demo-router demo-subnet
Added interface b1a894fd-aee8-475c-9262-4342afdc1b58 to router demo-router.
----

Attach the router to the external network by setting it as the gateway:

[source]
----
$ neutron router-gateway-set demo-router ext-net
Set gateway for router demo-router
----
====
