[[listing_the_openstack_security_group_rule_chain]]
= Listing the OpenStack security group rule chain

You can list all the rule chains and then look at the rule chain for the
OpenStack security group.

* To list all the rule chains and examine specific rule chains enter the
command:
+
[source]
midonet> list chain
chain chain5 name OS_SG_050593ed-56ad-44ef-8489-4052d02d99ff_INGRESS
chain chain0 name OS_PRE_ROUTING_5a151b0b-dea7-4918-bd17-876c1f7f5c64
chain chain1 name OS_POST_ROUTING_5a151b0b-dea7-4918-bd17-876c1f7f5c64
chain chain6 name OS_SG_01fce1b8-c277-4a37-a8cc-86732eea186d_INGRESS
chain chain4 name OS_SG_050593ed-56ad-44ef-8489-4052d02d99ff_EGRESS
chain chain7 name OS_SG_01fce1b8-c277-4a37-a8cc-86732eea186d_EGRESS
chain chain2 name OS_PORT_6f72342b-4947-432f-8d01-0cf4e4b8d049_INBOUND
chain chain3 name OS_PORT_6f72342b-4947-432f-8d01-0cf4e4b8d049_OUTBOUND
+
Note chain5, identified as a chain for an OpenStack security group (OS_SG) for
INGRESS traffic.

* To look at rule chain5 enter the command:
+
[source]
midonet> chain chain5 list rule
rule rule0 ethertype 2048 src 0.0.0.0/0 proto 6 tos 0 dst-port 5900 pos 1 type accept
rule rule1 ethertype 2048 src 0.0.0.0/0 proto 1 tos 0 pos 2 type accept
rule rule2 ethertype 2048 src 0.0.0.0/0 proto 6 tos 0 dst-port 22 pos 3 type accept
rule rule3 ethertype 2048 src 0.0.0.0/0 proto 6 tos 0 dst-port 80 pos 4 type accept

The above output shows the rule chain used to implement the security group you
configured in OpenStack. These rules contain the following instructions:

* All the rules match ethertype 2048 (IPv4) packets.

* All the rules match traffic from any source network (0.0.0.0/0).

* All the rules, except rule1, match packets of IP protocol 6 (TCP) and accept
them. rule1 matches packets of the ICMP type and accepts them.

* In addition to the other matches already mentioned, the rules match and accept
the packets according to the security group rules you defined in OpenStack,
specifically, packets with the destinations:

** TCP port 5900 (VNC)

** TCP port 22 (SSH)

** TCP port 80 (HTTP)
