[[listing_the_bridges_for_the_tenant]]
= テナント用にブリッジをリスト化します

オープンスタックセキュリティーグループに関連したルールチェーンは、ネットワーク(ブリッジ)ポート上に実装されています。

テナントについてのブリッジをリスト化し、demo-private-netネットワーク(ブリッジ)を表示するには次のコマンドを入力します：

[source]
midonet> list bridgebridge bridge0 name demo-private-net state up

++++
<?dbhtml stop-chunking?>
++++

==　ブリッジ上にポートをリスト化します

ブリッジポート上に設定されたルールチェーンについての情報をリスト化するには、次のコマンドを入力します：

[source]
midonet> bridge bridge0 list port
port port0 device bridge0 state up
port port1 device bridge0 state up infilter chain2 outfilter chain3
port port2 device bridge0 state up peer router1:port1

 [注記]
インフィルター(プレルーティング)チェーンならびにアウトフィルター(ポストルーティング)チェーンつきのポートはVMsに接続しています。ポート1は１つのVMに接続しています。

==　プレルーティングルールチェーン用のルールをリスト化します

ポート1用のプレルーティングルールチェーンをリスト化するには次のコマンドを入力します：


[source]
midonet> chain chain2 list rule
rule rule0 ethertype 2048 src !172.16.3.3 proto 0 tos 0 pos 1 type drop
rule rule1 hw-src !fa:16:3e:fb:19:07 proto 0 tos 0 pos 2 type drop
rule rule2 proto 0 tos 0 flow return-flow pos 3 type accept
rule rule3 proto 0 tos 0 pos 4 type jump jump-to chain4
rule rule4 ethertype !2054 proto 0 tos 0 pos 5 type drop

プレルーティングルールチェーンには以下に挙げる指示内容を含んでいます：

* ルール0は次のように述べています：各種パケットのうち、ethertype2048(IPv4)とマッチしているが、ソースIPアドレス172.16.3.3(これはVMのプライベートIPアドレスのこと)とはマッチしていないパケットはドロップします。

* ルール1は次のように述べています：ハードウェアソースつきの各種パケットのうち、リスト化してあるソースMACアドレス(これはVMのMACアドレスのこと)とマッチしないパケットはドロップします。

* ルール2は次のように述べています：各種パケットのうちリターンフローとマッチするパケット(つまりそのパケットはMidoNetが既に認知している接続に所属しているということ）は受け入れます。

* ルール3は次のように述べています：前記したドロップルールとマッチした結果、ドロップされなかったパケットが表示されているチェーン(チェーン4)にジャンプすることを許可します。

* ルール4は次のように述べています：　各種パケットのうちethertype2054(ARPパケット)とマッチしないパケットはドロップします。
