[[packet_flow_within_rule_chain]]
= ルールチェーンの中に見られるパケットのフロー

パケットに対してルールチェーンを呼び出す時には、ルールが順番に1つずつ呼び出されます。

いずれのルールにも条件があります：条件とは、パケットにマッチさせるべき属性セットのことです　?　この点につきましては詳細を下方に記しました　−　パケットはこの条件に対してチェックを受けます。パケットがこの条件に見合わない場合には、制御はルールチェーンに戻り、ルールチェーンは次のルールを呼び出すか（次のルールがあった場合）、あるいは自らの呼び出し元側に戻るかします。ルールチェーンの呼び出し元が必ずしもルーターであるとは限らないということに注意します‐それは下方で記したような、ジャンプルールが呼び出した別のルールチェーンかもしれません。もしパケットがルールの条件とマッチした場合、パケットになにが起きるかは、ルールの種別によって変わってきます。DROP(ドロップ)ルールのような単純なルール種別にたいしては、そのルールはnext_actionDROPを自らのチェーンに戻し、チェーンがDROPをその呼び出し元に戻します。この流れは、そのルーターが当初のルールチェーン（プレルーティングかポストルーティングか）の呼び出しによって、前述したようにDROP next_actionが戻り、ルーターがこのDROP next_actionを処理するまで続きます。

ルールの呼び出しは、前段落で紹介したルールチェーンの呼び出しの場合とほとんど同じです：

*もしもそのルールがプレルーティングの中で呼び出された時：そのパケットに対するルールの処理は入口ポート上で行ないます。

*もしもそのルールがポストルーティングの中で呼び出された時：そのパケットに対するルールの処理は入口ポート、出口ポート上で行ないます。

これらの呼び出しは、ルールチェーンの項で説明した時と全く同じように戻ります(next_action, new_packet)。しかしながら、この時、有効なnext_actionsのセットは異なりますし、その目的は、フローの処理をどのように継続するべきなのかをルールチェーンに指示することにあります。有効なnext_actionsは次のとおりです：

* ACCEPT:　ルールチェーンはパケットの処理を停止し、自らの呼び出し元に戻らなければなりません(ACCEPT, new_packet)。
*ルールチェーンは、ルールがパケットを放出した中、チェーンの中の次のルールを呼び出す必要があります。次のルールがない場合には、ルールチェーンは、自らの呼び出し元に戻らなければなりません(CONTINUE, new_packet)。

* DROP: ルールチェーンはパケットの処理を停止して、自らの呼び出し元に戻らなければなりません(DROP, new_packet)。

* RETURN: ルールチェーンはパケットの処理を停止し、自らの呼び出し元に戻らなければなりません(CONTINUE, new_packet)。この場合、このチェーンの中ではこれ以上実行されるルールがないため、ACCEPTアクションともCONTINUEのアクションとも流れが異なることに注意をしますが、今呼びかけを行なっているほうのチェーンの中にあるルールが実行されることはあります。

* REJECT:　ルールチェーンはパケットの処理を停止して、自らの呼び出し元に戻らなければなりません(REJECT, new_packet)。

各種パケットが具体的なルールにより処理される方法は、そのルールの種別によって変わってきます。これ以降のセクションでは、各ルール種別がどのように構築されていて、その各々のルール種別が、自らの条件にマッチしたパケットにどのような影響を及ぼすのかについて説明します。
