[[example_condition_1]]
=条件例１

各種パケットのうち、そのネットワークソースが10.0.0.0/16であるもののみが、ネットワーク10.0.5.0/24に到達する許可を得ます。この事を実現する方法は数通りあります。

その1つの方法が、「条件」を持ったDROPルールあるいはREJECTルールを構築する方法です。また、これらの属性を保有したACCEPTルールは下に挙げた意味を持ちます。

. (ethertype equal 2048) AND (src NOT equal (10.0.0.0, 16))であればDROP
. (dst equal (10.0.5.0, 24))であればACCEPT
. DROP

[NOTE]
ルール2が意味を持つには無条件dropが必要です。

上に記した属性を持ったルールチェーンを生成するためには、

.必要であればsettコマンドを使うかあるいは他の手段を使って、適切なテナントにアクセスします。
+
[source]
midonet> sett 10a83af63f9342118433c3a43a329528
tenant_id: 10a83af63f9342118433c3a43a329528

.コマンドを入力して新しいルールチェーンを作成し、そのルールチェーンに名前を付与します。
+
[source]
midonet> chain create name "drop_not_src_mynetwork_INBOUND"
chain5

. ソース10.0.0.0/16を持たないIPv4トラフィックをドロップするコマンドを入力します。
+
[source]
midonet> chain chain5 add rule ethertype 2048 src !10.0.0.0/16 type drop
chain5:rule0

.行き先が10.0.5.0/24を持ったIPv4トラフィックを受け入れるコマンドを入力します。
+
[source]
midonet> chain chain5 add rule ethertype 2048 dst 10.0.5.0/24 pos 2 type accept
chain5:rule2

. 新しいルールチェーンに追加されたルールをリスト化するためのコマンドを入力します。
+
[source]
midonet> chain chain5 list rule
rule rule3 ethertype 2048 src !10.0.0.0/16 proto 0 tos 0 pos 1 type drop
rule rule2 ethertype 2048 dst 10.0.5.0/24 proto 0 tos 0 pos 2 type accept
