= Compute Services (Nova)

[IMPORTANT]
Follow the OpenStack documentation's
ifdef::icehouse[]
http://docs.openstack.org/icehouse/install-guide/install/apt/content/ch_nova.html[Chapter 6. Configure Compute services]
endif::icehouse[]
ifdef::juno[]
http://docs.openstack.org/juno/install-guide/install/apt/content/ch_nova.html[Chapter 5. Add the Compute service]
endif::juno[]
instructions, but *note the following differences*.

== Controller Node

[NOTE]
Follow the OpenStack documentation's
ifdef::icehouse[]
http://docs.openstack.org/icehouse/install-guide/install/apt/content/nova-controller.html[Install Compute controller services]
endif::icehouse[]
ifdef::juno[]
http://docs.openstack.org/juno/install-guide/install/apt/content/ch_nova.html#nova-controller-install[Install and configure controller node]
endif::juno[]
instructions as is.

== Compute Node

[IMPORTANT]
Follow the OpenStack documentation's
ifdef::icehouse[]
http://docs.openstack.org/icehouse/install-guide/install/apt/content/nova-compute.html[Configure a compute node]
endif::icehouse[]
ifdef::juno[]
http://docs.openstack.org/juno/install-guide/install/apt/content/ch_nova.html#nova-compute-install[Install and configure a compute node]
endif::juno[]
instructions, but *note the following additions*.

. *Configure libvirt*
+
====
Edit the `/etc/libvirt/qemu.conf` file to contain the following:

[literal,subs="quotes"]
----
user = "root"
group = "root"

cgroup_device_acl = [
    "/dev/null", "/dev/full", "/dev/zero",
    "/dev/random", "/dev/urandom",
    "/dev/ptmx", "/dev/kvm", "/dev/kqemu",
    "/dev/rtc","/dev/hpet", "/dev/vfio/vfio",
    *_"/dev/net/tun"_*
]
----
====

. *Restart the libvirt service*
+
====
[source]
----
# service libvirt-bin restart
----
====

////
//
// Need clarification on future packaging of this. See JIRA OI-30.
//
. *Configure nova-rootwrap*
+
====
Create the `/etc/nova/rootwrap.d/midonet.filters` file and edit it to contain
the following:

[source]
----
[Filters]
# MidoNet
mm-ctl: CommandFilter, mm-ctl, root
----
====
////

. *Install nova-rootwrap network filters*
+
====
[source]
----
# apt-get install nova-network
----
====

. *Restart the Compute service*
+
====
[source]
----
# service nova-compute restart
----
====
