= Controller Node

[IMPORTANT]
Follow the OpenStack documentation's
ifdef::icehouse[]
http://docs.openstack.org/icehouse/install-guide/install/apt/content/neutron-ml2-controller-node.html[Configure controller node]
endif::icehouse[]
ifdef::juno[]
http://docs.openstack.org/juno/install-guide/install/apt/content/neutron-controller-node.html[Install and configure controller node]
endif::juno[]
instructions, but *note the following differences*.

ifdef::icehouse[]
. *Prerequisites*
endif::icehouse[]
ifdef::juno[]
. *To configure prerequisites*
endif::juno[]
+
====
Apply as is.
====

. *To install the Networking components*
+
====
Do *not* apply.

.. Instead, install the following packages:
+
[source]
----
# apt-get install neutron-server python-neutron-plugin-midonet
----
+
====

. *To configure the Networking server component*
+
====
ifdef::icehouse[]
Do *not* apply step '5. Configure Networking to use the Modular Layer 2 (ML2)
plug-in and associated services'.
endif::icehouse[]
ifdef::juno[]
Do *not* apply step 'd. Enable the Modular Layer 2 (ML2) plug-in, router
service, and overlapping IP addresses'.
endif::juno[]

.. Instead, edit the `/etc/neutron/neutron.conf` file and add the following key
to the `[DEFAULT]` section:
+
[source]
----
[DEFAULT]
...
core_plugin = midonet.neutron.plugin.MidonetPluginV2
----
+
====
+
[NOTE]
Make sure to not leave any space at the starting of lines in any configuration
file (this applies to all configuration files).

. *To configure the Modular Layer 2 (ML2) plug-in*
+
====
Do *not* apply.

Instead, perform the following steps.

.. Create the directory for the MidoNet plugin:
+
[source]
----
mkdir /etc/neutron/plugins/midonet
----
+
.. Create the `/etc/neutron/plugins/midonet/midonet.ini` file and edit it to
contain the following:
+
[literal,subs="quotes"]
----
[DATABASE]
sql_connection = mysql://neutron:**_NEUTRON_DBPASS_**@*_controller_*/neutron

[MIDONET]
# MidoNet API URL
midonet_uri = http://*_controller_*:8080/midonet-api
# MidoNet administrative user in Keystone
username = *_midonet_*
password = *_MIDONET_PASS_*
# MidoNet administrative user's tenant
project_id = service
----
+
.. Edit the `/etc/default/neutron-server` file to contain the following:
+
[source]
----
NEUTRON_PLUGIN_CONFIG="/etc/neutron/plugins/midonet/midonet.ini"
----
+
====

. *To configure Compute to use Networking*
+
====
Apply as is.
====

. *To finalize installation*
+
====
Apply as is.
====
