[[overlay_network]]
= オーバーレイネットワーク
オーバーレイネットワーク、つまり物理ネットワークは、接続に関する問題があった時にまず一番最初にチェックするポイントです。

== トンネルゾーン

MidoNetエージェントを走らせているホストが、トンネルゾーンに追加されていて、稼働していることを確認してください。

[literal,subs="quotes"]
----
# midonet-cli

midonet> list tunnel-zone
tzone tzone0 name tz type vxlan

midonet> tunnel-zone tzone0 list member
zone tzone0 host host0 address 192.168.0.1
zone tzone0 host host1 address 192.168.0.2
zone tzone0 host host2 address 192.168.0.3
zone tzone0 host host3 address 192.168.0.4

midonet> list host
host host0 name host-a alive true
host host1 name host-b alive true
host host2 name host-c alive true
host host3 name host-d alive true
----

パケットがトンネルインターフェース上を伝送しているかどうかをチェックして、エラーが無いこと、パケットがドロップしていないことを確認してください。

VXLANプロトコルの場合は、`tnvxlan-overlay`を確認してください。GREプロトコルの場合は、`tngre-overlay`を確認してください。

====
[literal,subs="quotes"]
----
# mm-dpctl datapath --show midonet | grep tnvxlan-overlay
Port #x '*tnvxlan-overlay*' VXLan Stats{*rxPackets=24170772*, *txPackets=45160026*, rxBytes=1628556667, txBytes=30598767320, *rxErrors=0*, *txErrors=0*, *rxDropped=0*, *txDropped=0*}
----
====

====
[literal,subs="quotes"]
----
# mm-dpctl datapath --show midonet | grep tngre-overlay
Port #x "*tngre-overlay*" Gre Stats{*rxPackets=508157678*, *txPackets=398704120*, rxBytes=291245619484, txBytes=318474308439, *rxErrors=0*, *txErrors=0*, *rxDropped=0*, *txDropped=0*}
----
====

== MidoNet データパス

MidoNetデータパスを確認してください。

====
[literal,subs="quotes"]
----
# mm-dpctl datapath --show midonet
Name: midonet
Index: 10
Supports megaflows: yes
Stats:
  Flows :1340066
  Hits  :1111802509
  Lost  :0
  Misses:17302163
Port #0 "midonet"  Internal  Stats{rxPackets=0, txPackets=0, rxBytes=0, txBytes=0, rxErrors=0, txErrors=0, rxDropped=0, txDropped=0}
Port #1 'metadata' Internal Stats{rxPackets=8, txPackets=0, rxBytes=648, txBytes=0, rxErrors=0, txErrors=0, rxDropped=0, txDropped=0}
Port #2 "tngre-overlay"  Gre  Stats{rxPackets=508157678, txPackets=398704120, rxBytes=291245619484, txBytes=318474308439, rxErrors=0, txErrors=0, rxDropped=0, txDropped=0}
Port #3 "tnvxlan-overlay"  VXLan  Stats{rxPackets=0, txPackets=0, rxBytes=0, txBytes=0, rxErrors=0, txErrors=0, rxDropped=0, txDropped=0}
Port #4 "tnvxlan-vtep"  VXLan  Stats{rxPackets=0, txPackets=0, rxBytes=0, txBytes=0, rxErrors=0, txErrors=0, rxDropped=0, txDropped=0}
Port #5 "tapa0164c42-dd"  NetDev  Stats{rxPackets=389426272, txPackets=342761506, rxBytes=1128206548338, txBytes=241007949600, rxErrors=0, txErrors=0, rxDropped=0, txDropped=0}
Port #6 "tap19ccc069-f1"  NetDev  Stats{rxPackets=0, txPackets=54640, rxBytes=0, txBytes=2347034, rxErrors=0, txErrors=0, rxDropped=0, txDropped=0}
Port #7 "tape3055fc6-cc"  NetDev  Stats{rxPackets=21375, txPackets=42911, rxBytes=3573207, txBytes=4607633, rxErrors=0, txErrors=0, rxDropped=0, txDropped=0}
----
====

====
[literal,subs="quotes"]
----
# mm-dpctl datapath --dump midonet
1340149 flows
  Flow
    Match: FlowMatch[InputPortNumber=5, EthSrc=0a:b4:2c:fc:86:86, EthDst=fa:16:3e:15:6c:cc, EtherType=0800, NetworkSrc=8.8.8.8, NetworkDst=172.16.17.18, NetworkProto=udp, NetworkTTL=52, NetworkTOS=0, FragmentType=None, SrcPort=53, DstPort=8968]
    Mask:  FlowMask[Priority{0}, InPort{-1}, Ethernet{src=ff:ff:ff:ff:ff:ff, dst=ff:ff:ff:ff:ff:ff}, EtherType{0xffffffff}, KeyIPv4{src=255.255.255.255, dst=255.255.255.255, proto=-1, tos=-1, ttl=-1, frag=-1}, UDP{src=65535, dst=65535}, Tunnel{tun_id=0, ipv4_src=0.0.0.0, ipv4_dst=0.0.0.0, tun_flag=0, ipv4_tos=0, ipv4_ttl=0}]
    Actions: 
      SetKey{Ethernet{src=fa:16:3e:e1:58:2e, dst=fa:16:3e:88:4c:59}}
      SetKey{KeyIPv4{src=8.8.8.8, dst=10.5.0.2, proto=17, tos=0, ttl=50, frag=0}}
      SetKey{UDP{src=53, dst=53241}}
      SetKey{Tunnel{tun_id=44, ipv4_src=192.168.123.76, ipv4_dst=192.168.123.79, tun_flag=0, ipv4_tos=0, ipv4_ttl=-1}}
      Output{port=3}
    Stats: FlowStats{packets=0, bytes=0}
    TCP flags: 
    Last used time: 0
[...]
----
====

== MTU

アンダーレイネットワークのフラグメンテーションを避けるために、VMインスタンスのMTUは、トンネルプロトコルのオーバーヘッドに対応している必要があります。

この調整されたMTUは、DHCPを通じて、MidoNetに酔って自動的にアドバタイズされます。しかし、これは、VMで使われているオペレーティングシステムによっては、適応されない場合があります。

VMのMTUはアンダーレイのMTUに基づいて設定されていることを確認ください。


[options="header"]
|====
|Underlay MTU |Tunnel Protocol |Protocol Overhead |VM's MTU
|1500 bytes   |VXLAN           |50 bytes          |1450 bytes
|1500 bytes   |GRE             |46 bytes          |1455 bytes
|9000 bytes   |VXLAN           |50 bytes          |8950 bytes
|9000 bytes   |GRE             |46 bytes          |8955 bytes
|====

