[[l4lb]]
= レイヤ4のロードバランシング

MidoNetのロードバランサーはレイヤ４(L4)のロードバランシグを提供します。フローティングIPアドレスからプライベートIPアドレスにトラフィック（ロード）をバランスしたいテナントに対応する場合などが典型的な事例です。

一般的にトラフィックは、外部もしくはパブリックのルータブルアドレス（例えば、サービスを使う世界中のユーザーです）から仮想IPアドレス（これは通常はパブリックのフローティングIPアドレスですが、VMの替わりにロードバランサーにアサインされます）にやってきます。そして、クラウド上で数多くのプライベートIPアドレスにロードバランスされます。MidoNetの場合は、これらのバックエンドのサーバーはVMです。ロードバランサーは接続を打ち切らず、ディスティネーションIPにトランスレートするので、あまりトランスパレントではありません。

*設定のオーバービュー*

設定の一環として、トラフィックがロードバランスされているバックエンドサーバーのプール(VM)を定義することができます。プールメンバーは通常プライベートIPアドレスを持っています。VMの配置は柔軟ですが、ロードバランサーがどこに設定されるかは考慮する必要があります。一般ルールとして、VMプライベートアドレスは、ロードバランサーがアタッチされているルーターから到達される＊必要があります＊
したがって、プールメンバーは、

* 全てルーターのシングルサブネットに全て属するか、もしくは

* ルーターの複数のサブネットに配置されます

最終的に、ロードバランサーはリクエストソースアドレスを修正せずに残すので、ロードバランサーはリターントラフィックのパスに配置される必要があることに留意してください。フォワードバケットに適用しているVIP->back-end-IPトランスレーションという流れを反転する機会をロードバランサーに与えずにリターントラフィックは、リクエストソースに反映されます。

*ヘルスモニタリング*

それに加えて、バックエンドサーバーのチェックを行う為のヘルスモニターの設定ができます。ヘルスモニターはプールから、健全でないノードを自動的に取り除き、健全に戻ったら追加します。

*MidoNetロードバランサーの制約*

MidoNetはロードバランサーを設定するために、Neutron APIを使います（https://wiki.openstack.org/wiki/Neutron/LBaaS/API_1.0でドキュメント化されています）しかし、すべてのNeutron LBaasフィーチャーがMidoNetでサポートされているわけではありません。

* L7のロードバランシングはサポートされていません。

* プールの統計情報はありません。

* ラウンドロビンメソッドのみがロードバランサーメソッドでサポートされています。

* Neutronプロバイダーモデルはサポートされていません。（例えば、各プールの特定のプロバイダーはサポートされていません）

* 各プールに一つのヘルスモニターのみ適用します（リストの一番上のものです）

* TCPヘルスチェックしか行いません(UDP, HTTPは適用外です)

* ソースIPセッションがパーシステンスです（もしくはクッキーかURL）

* フローティングIPを仮想IPアドレス(VIP)に関連づけることはできません。

* ヘルスモニタリングが稼働している時はVIP はプールメンバーとして同じサブネットにいてはいけません。

* ヘルスチェックにはICMPはありません。

* 接続の上限はありません。

* 各プールに一つのヘルスモニターしかありません。

* TCPのロードバランスしかサポートされていません。

* 選択したバックエンドに直接接続してスティッキーソースIPを使用する場合は、ロードバランサで使用されているのと同じポート上にホストすることはできません。

* 外部ネットワークをVIPとして使用するには、「共有」されなければなりません。
