[[health_monitor]]
= ヘルスモニター

ヘルスモニタリングは、プールメンバーが“生きているか”をチェックするアクティビティです。つまり、HTTP, TCP, UDP, もしくは ICMPでの接続性が、そのノードで確立しているかどうかのチェックです。

MidoNetのケースですと、TCPでの接続性のみをチェックします。ヘルスモニタリングはパケットをプールメンバーに送って、返信を受け取るかどうかを確認します。
何度かリトライした後に、ある時間以内にパケットをプールメンバーが返信したら、そのノードはACTIVEとして考慮されます。従って、ヘルスモニターは以下の三つの変数によって成り立ちます：

* max_retries: ヘルスモニターがノードをINACTIVEとして判断する前に、ヘルスモニターが返信が無い状態で何度パケットをプールメンバーに送ったか

* delay: ヘルスモニターからプールメンバーに対して、パケットを伝送する間隔の時間です

* timeout: 接続が確立されてから追加のタイムアウトです

ヘルスモニターは、アサインされた全てのプールメンバーの現状のステータスのトラッキングを行います。ロードバランシングの決定は、プールメンバーが“生きている”かがベースになります。

== HAProxy 設定

レイヤー４ロードバランサーを使う時は、バックエンドサーバーのチェックを行う為にヘルスモニターを設定します。

一度に、一つのホストしか全てのヘルスモニターを走らせることしかできません。
もし、ホストが何らかの理由でダウンしてしまったら、新しいホストが立ち上がって、必要なHAProxyインスタンスを生み出します。HAProxyインスタンスはMidoNetエージェント(Midolman)によって管理されており、設定は必要ありません。しかし、HAProxyインスタンスを潜在的に保持するホストを選択する必要があります。

これを設定するには、適切なホストの mn-conf(1) の agent セクションに haproxy_health_monitor セクションを加えてください。そして、下記の事例で示しているように、health_monitor_enableをtrueに設定してください。

[source]
----
agent.haproxy_health_monitor.health_monitor_enable = true
----

それに加えて、HAProxyインスタンスを走らせているホストは、"nogroup"と呼ばれるグループと"nobody"と呼ばれるユーザーを持つ必要があります。そうでないなら、HAProxyは起動することはできません。これはUbuntuのデフォルトの設定ですが、Red Hadではこのユーザーとグループを作成する必要があります。

* MidNetエージェントの中で、ヘルスモニターがどのように機能するか*

* MidoNetエージェント(midolman)は自分のヘルスモニターは実装しません。その変わりに、haproxyパッケージ(使われるhaproxy バージョンは 1.4です)の一部であるヘルスチェッカーを活用します。MidoNetエージェントは、以下のことをやりながら、HAProxyを活用します：

** ユーザーがプールにヘルスモニターをアタッチする時は、MidoNetエージェントはそのプールと関連しているHAProxyインスタンスを起動します。

** HAProxyプロセスはプールメンバー全てに関する情報を受け取って、ウォッチする必要があります。

** MidoNetエージェントは、そのノードのステータスに関して、HAProxyを定期的に調査します。そのステータス情報と一緒に、MidoNetエージェントは自身のデータベースを更新します。

* 以下のコンフィグ設定( +mn-conf(1)+ で)は、ヘルスモニタリングを考慮してどのようにアクトするかをMidoNetに伝えます：

** health_monitor_enable: TrueはMidoNetエーフェンとが、ヘルスモニタリングのためにHAProxyを設定できることを示しています。デフォルト設定ではこれはfalseになっています。

** namespace_cleanup: MidoNetエージェントがダウンして、HAProxyホストとして設定されなくなった後に、ホスト側で、HAProxy名前空間の残りがまだある時に、それをMidoNetエージェントのホストがクリンーアップしなければならないことをtrueは示しています。デフォルトではこれはfalseとして設定されています。

** namespace_suffix: HAProxyインスタンスをホールドしている名前空間の名前の最後に、追加される文字列です。これによって、HAProxy向けに作成される名前空間を簡単に、特定することができます。_MN がデフォルト値です。

** haproxy_file_loc: HAProxyのためのconfig ファイルが作成されファイルのロケーションを特定します。デフォルト値は/etc/midolman/l4lb/です。

* 一度に、全てのHAProxyインスタンスを含むことができるホストは一つしかありません。このホストは、設定で定義されるhealth_monitor_enable=trueという状態をもつMidoNetエージェントホストの一つになります。
もしホストが何らかの理由でダウンしてしまったら、health_monitor_enable=trueとして設定されている他のホストが、引き継いで、必要なHAProxyインスタンスを生み出します。

== プールの中のヘルスモニタリングを利用可能にします。
プールの中のヘルスモニタリングを利用可能にするために、以下のいずれかを実行することができます。
* CLIもしくはAPIサーバーを使ってヘルスモニターオブジェクトを作成します。そして、関連する遅延、タイムアウト、max_retriesの値を設定します。（詳細情報は、“ヘルスモニター”を見てください）

* モニターしたいプールに対して、ヘルスモニターオブジェクトをアタッチします。
一つのヘルスモニターは、プールはいくつでもアタッチできますが、プールには一つのヘルスモニターしかありません。

* ヘルスモニターオプジェクとのadmin_state_up をtrueにします。

*CLIの例*

下記の例は、ヘルスモニタリングを設定する為にMidoNet CLIをどのように使うかを示しています。

[source]
midonet> health-monitor list
midonet> health-monitor create type TCP delay 100 max-retries 50 timeout 500
hm0
midonet> load-balancer lb0 pool pool0 set health-monitor hm0
midonet> load-balancer lb0 pool pool0 health-monitor show
hm hm0 delay 100 timeout 500 max-retries 50 state down
midonet> health-monitor hm0 pool list
pool pool0 load-balancer lb0 health-monitor hm0 lb-method ROUND_ROBIN state up

== ヘルスモニタリングを利用不可能にします。

プールでヘルスモニタリングを利用不可能にするには、以下のいずれかを行うことができます：

* ヘルスモニターのadmin_state_upをfalseに設定します。このヘルスモニターを使っている全てのプールは、ヘルスモニターを利用不可能にします。
* プールのhealth_monitor_id をNullに設定します。
* ヘルスモニターオブジェクトを削除します。

