= Controller Node

[IMPORTANT]
Follow the OpenStack documentation's
http://docs.openstack.org/kilo/install-guide/install/yum/content/neutron-controller-node.html[Install and configure controller node]
instructions, but *note the following differences*.

. *To configure prerequisites*
+
====
Apply as is.
====

. *To install the Networking components*
+
====
Do *not* apply.

Instead, install the following packages:

[source]
----
# yum install openstack-neutron python-neutron-plugin-midonet
----
====

. *To configure the Networking server component*
+
====
Do *not* apply step 'd. Enable the Modular Layer 2 (ML2) plug-in, router
service, and overlapping IP addresses'.

Instead, edit the `/etc/neutron/neutron.conf` file and add the following key
to the `[DEFAULT]` section:
[source]
----
[DEFAULT]
...
core_plugin = neutron.plugins.midonet.plugin.MidonetPluginV2
----
====

. *To configure the Modular Layer 2 (ML2) plug-in*
+
====
Do *not* apply.

Instead, perform the following steps.

.. Create the directory for the MidoNet plugin:
+
[source]
----
# mkdir /etc/neutron/plugins/midonet
----
+
.. Create the `/etc/neutron/plugins/midonet/midonet.ini` file and edit it to
contain the following:
+
[literal,subs="quotes"]
----
[DATABASE]
sql_connection = mysql://neutron:**_NEUTRON_DBPASS_**@*_controller_*/neutron

[MIDONET]
# MidoNet API URL
midonet_uri = http://*_controller_*:8080/midonet-api
# MidoNet administrative user in Keystone
username = *_midonet_*
password = *_MIDONET_PASS_*
# MidoNet administrative user's tenant
project_id = service
----
+
.. Create a symbolic link to direct Neutron to the MidoNet configuration:
+
[source]
----
# ln -s /etc/neutron/plugins/midonet/midonet.ini /etc/neutron/plugin.ini
----
+
====

. *To configure Compute to use Networking*
+
====
Apply as is.
====

. *To finalize installation*
+
====
Do *not* apply.

Instead, perform the following steps.

.. Populate the database:
+
[source]
----
# su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/midonet/midonet.ini upgrade kilo" neutron
----
+
.. Restart the Compute services:
+
[source]
----
# systemctl restart openstack-nova-api.service openstack-nova-scheduler.service openstack-nova-conductor.service
----
+
.. Start the Networking service and configure it to start when the system boots:
+
[source]
----
# systemctl enable neutron-server.service
# systemctl start neutron-server.service
----
====
