[[neutron_controller_node_installation]]
= コントローラノード

[IMPORTANT]
OpenStack文書の
http://docs.openstack.org/kilo/install-guide/install/yum/content/neutron-controller-node.html[Install and configure controller node]
指示に従います。ただし、 *次の相違事項と追加事項に注意してください。*

. *前提条件を設定する場合*
+
====
このまま適用します。
====

. *ネットワーキングのコンポーネントをインストールする場合*
+
====
適用*しないで*ください。

代わりに、次のパッケージをインストールします。

[source]
----
# yum install openstack-neutron python-neutron-plugin-midonet
----
====

. *ネットワーキングのサーバーコンポーネントを構成する場合*
+
====
ステップ 「d. モジュラーレイヤー2（ML2）プラグイン、ルーターサービスおよび重複するIPアドレスを有効する」
を適用*しないで*ください。

代わりに、`/etc/neutron/neutron.conf` ファイルを変更して、次のキーを `[DEFAULT]` セクションに設定します。

[source]
----
[DEFAULT]
...
core_plugin = midonet.neutron.plugin_v2.MidonetPluginV2
...
dhcp_agent_notification = False
...
allow_overlapping_ips = True
----
====

. *モジュラーレイヤー2（ML2）のプラグインを構成する*
+
====
適用*しないで*ください。

代わりに、次の手順を実行します。

.. MidoNetプラグインのディレクトリを作成します。
+
[source]
----
# mkdir /etc/neutron/plugins/midonet
----
+
.. `/etc/neutron/plugins/midonet/midonet.ini` ファイルを作成し、修正して次を含めます。
+
[literal,subs="quotes"]
----
[MIDONET]
# MidoNet API URL
midonet_uri = http://*_controller_*:8181/midonet-api
# MidoNet administrative user in Keystone
username = *_midonet_*
password = *_MIDONET_PASS_*
# MidoNet administrative user's tenant
project_id = service
----
+
.. NeutronをMidoNetの構成に転送するためのシンボリックリンクを作成します。
+
[source]
----
# ln -s /etc/neutron/plugins/midonet/midonet.ini /etc/neutron/plugin.ini
----
+
====

. *コンピュートでネットワーキングの使用を構成する場合*
+
====
このまま適用します。
====

. *Load-Balancer-as-a-Service (LBaaS) の設定*
+
====
OpenStackのインストールガイドとともに、xref:configure_lbaas[]に記載されている、Load-Balancer-as-a-Service (LBaaS) を設定してください。
====

. *インストールを終了する場合* [[neutron_controller_node_installation_finalize]]
+
====
適用*しないで*ください。

代わりに、次の手順を実行します。

.. データベースを追加します。
+
[source]
----
# su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/midonet/midonet.ini upgrade kilo" neutron
----
+
[source]
----
# midonet-db-manage upgrade head
----
+
.. コンピュートサービスを再開します。
+
[source]
----
# systemctl restart openstack-nova-api.service openstack-nova-scheduler.service openstack-nova-conductor.service
----
+
.. ネットワーキングサービスを開始して、システムが起動したら開始するよう設定します。
+
[source]
----
# systemctl enable neutron-server.service
# systemctl start neutron-server.service
----
====
