= Midolman のインストール

仮想トポロジへのトラフィックの出入り口となるすべてのノードには、_MidoNet Agent (Midolman)_
をインストールする必要があります。このガイドでは、*_controller_*、*_gateway1_*、*_gateway2_*、*_compute1_*
の各ノードがこれに相当します。

. *Midolman パッケージをインストールする*
+
====
[source]
----
# yum install midolman
----
====

. *mn-conf をセットアップする*
+
====
`/etc/midolman/midolman.conf` を編集し、mn-conf を ZooKeeper クラスタにポイントします。

[source,subs="quotes"]
----
[zookeeper]
zookeeper_hosts = *_nsdb1_*:2181,*_nsdb2_*:2181,*_nsdb3_*:2181
----
====

. *すべてのエージェントで NSDB へのアクセスを構成する*
+
====
この手順は 1 回だけ実行してください。1 回実行すれば、すべての MidoNet Agent ノードで NSDB へのアクセスがセットアップされます。

次のコマンドを実行して、Zookeeper と Cassandra のサーバーアドレスにクラウド全体の値を設定します。

[source,subs="specialcharacters,quotes"]
----
$ cat << EOF | mn-conf set -t default
zookeeper {
    zookeeper_hosts = "*_nsdb1_*:2181,*_nsdb2_*:2181,*_nsdb3_*:2181"
}

cassandra {
    servers = "*_nsdb1_*,*_nsdb2_*,*_nsdb3_*"
}
EOF
----

次のコマンドを実行して、Cassandra レプリケーション係数を設定します。

[source,subs="specialcharacters,quotes"]
----
$ echo "cassandra.replication_factor : *_3_*" | mn-conf set -t default
----
====

. *リソース使用の設定*
+
====
リソース使用を設定するために　*各エージェントホスト*　で下記の手順を実行します。

[IMPORTANT]
本番環境では *large* （大）テンプレートを強くお勧めします。

.. *Midolman リソーステンプレート*
+
Midolmanリソーステンプレートを設定するためには、次のコマンドを実行します。
+
[source,subs="specialcharacters,quotes"]
----
$ mn-conf template-set -h local -t *_TEMPLATE_NAME_*
----
+
*_TEMPLATE_NAME_* を以下のいずれかのテンプレートに置き換えます。
+
[source,subs="specialcharacters,quotes"]
----
agent-compute-large
agent-compute-medium
agent-gateway-large
agent-gateway-medium
default
----

.. *Java Virtual Machine (JVM) リソーステンプレート*
+
JVMリソーステンプレートを設定するためには、デフォルトの `/etc/midolman/midolman-env.sh`
ファイルを以下のいずれかに置き換えます。
+
[source,subs="specialcharacters,quotes"]
----
/etc/midolman/midolman-env.sh.compute.large
/etc/midolman/midolman-env.sh.compute.medium
/etc/midolman/midolman-env.sh.gateway.large
/etc/midolman/midolman-env.sh.gateway.medium
----
====

. *Midolman を起動する*
+
====
[source]
----
# systemctl start midolman.service
----
====
