= MidoNet Cluster Installation

. *Install MidoNet Cluster package*
+
====
[source]
----
# yum install midonet-cluster
----
====

. *Set up mn-conf*
+
====
Edit `/etc/midonet/midonet.conf` to point mn-conf to the ZooKeeper cluster:

[source,subs="quotes"]
----
[zookeeper]
zookeeper_hosts = *_nsdb1_*:2181,*_nsdb2_*:2181,*_nsdb3_*:2181
----
====

. *Configure access to the NSDB*
+
====
This step needs to happen only once, it will set up access to the NSDB for
the MidoNet Cluster and Agent nodes.

Run the following command to set the cloud-wide values for the ZooKeeper and
Cassandra server addresses:

[source,subs="specialcharacters,quotes"]
----
$ cat << EOF | mn-conf set -t default
zookeeper {
    zookeeper_hosts = "*_nsdb1_*:2181,*_nsdb2_*:2181,*_nsdb3_*:2181"
}

cassandra {
    servers = "*_nsdb1_*,*_nsdb2_*,*_nsdb3_*"
}
EOF
----

Run the following command to set the Cassandra replication factor:

[source,subs="specialcharacters,quotes"]
----
$ echo "cassandra.replication_factor : *_3_*" | mn-conf set -t default
----
====

. *Configure Keystone access*
+
====
This step needs to happen only once, it will set up access to Keystone for the
MidoNet Cluster node(s).

Determine `domain_name` and `domain_id` to be used for Keystone authentication:

[literal,subs="verbatim,quotes"]
----
# openstack domain list
+---------+---------+---------+----------------------------------------------------------------------+
| ID      | Name    | Enabled | Description                                                          |
+---------+---------+---------+----------------------------------------------------------------------+
| *_default_* | *_Default_* | True    | Owns users and tenants (i.e. projects) available on Identity API v2. |
+---------+---------+---------+----------------------------------------------------------------------+
----

For `tenant_name`, use the project/tenant that the `midonet` user belongs to, as
configured during xref:keystone_midonet_user[user creation].

Configure the authentication parameters for MidoNet Cluster via `mn-conf`:

[literal,subs="verbatim,quotes"]
----
$ cat << EOF | mn-conf set -t default
cluster.auth {
   admin_role = "admin"
   provider_class = "org.midonet.cluster.auth.keystone.KeystoneService"
   keystone {
      admin_token = ""
      protocol = "http"
      host = "*_controller_*"
      port = 35357
      domain_name = "*_Default_*"
      domain_id = "*_default_*"
      tenant_name = "*_$MIDONET_TENANT_*"
      user_name = "midonet"
      user_password = "*_$MIDONET_PASS_*"
      version = 3
   }
}
EOF
----
====

. *Start the MidoNet Cluster*
+
====
[source]
----
# systemctl enable midonet-cluster.service
# systemctl start midonet-cluster.service
----
====
