[[authentication_services]]

= MidoNet内で使用可能な認証サービス

++++
<?dbhtml stop-chunking?>
++++

MidoNet APIには、KeystoneAuthServiceとMockAuthServiceの2種類の認証モードがあります。

このセクションでは、Keystoneの認証サービスと模擬認証、そしてweb.xmlファイルを使いどのようにして必要なサービスを選択するのかについて説明します。

== Keystone特有の設定

OpenStack Keystone認証サービスをMidoNetで使用するために、web.xmlファイルを設定する必要があります。

認証サービスのためにKeystoneを規定についての説明です。設定要素の名前: keystone-service_protocolとなり、認められた値: http, httpsとなります。プレーンテキストのHTTPを使い、httpを使ってKeystoneにアクセスすることが可能になります。httpsを規定した場合、MidoNet APIサーバーとKeystone認証サーバーの接続は暗号化され、httpsが推奨されます。下記の例は、Keystoneを使って暗号化されたコミュニケーションの設定に使われた、XML内でエンコードされた名前と値キーのペアです。

.Keystone Service Protocols
[options="header"]
|===============
| Parameter Name | Value | Description
| 2*|keystone-service_protocol | http | Keystoneサーバーと通信するため通常のHTTPを使用
| | https | Keystoneサーバーと通信するため暗号化されたHTTPSを使用
|===============
|====
| Parameter Name | Value | Description
.2+| keystone-service_protocol
| http | Keystoneサーバーと通信するため通常のHTTPを使用
| https | Keystoneサーバーと通信するため暗号化されたHTTPSを使用
|====


必要なサービスプロトコルを含むため、`/usr/share/midonet-api/WEB-INF/web.xml` ファイルを編集してください。

[source]
<context-param>
    <param-name>keystone-service_protocol</param-name>
    <param-value>https</param-value>
</context-param>

== 模擬認証について

模擬認証は、`web.xml`の設定ファイル内にある全てのロールにトークンをマッピングすることにより、認証システムをまねるものです。もし、アドミンロールにマッピングされたトークンがAPIリクエストに使われると、認証と承認は無効にされます。

[WARNING]
このモードはテスト目的で使用するもので、プロダクションでは使用できません。
