[[enabling_keystone_authentication]]
= Keystone認証の有効化

MidoNetでOpenStack Keystone認証サービスを使うためには、web.xmlファイル内にいくつかの設定をする必要があります。

++++
<?dbhtml stop-chunking?>
++++

== auth-auth_provider

認証サービスを提供するJavaクラスの、完全修飾パスをリスト化します。

[source]
<context-param>
  <param-name>auth-auth_provider</param-name>
  <param-value>
    org.midonet.api.auth.keystone.v2_0.KeystoneService
  </param-value>
</context-param>

== keystone-service_protocol

Keystoneサービスに使用されたプロトコルを特定します。

[source]
<context-param>
  <param-name>keystone-service_protocol</param-name>
  <param-value>http</param-value>
</context-param>

== keystone-service_host

Keystoneサービスのホストを特定します。

[source]
<context-param>
  <param-name>keystone-service_host</param-name>
  <param-value>192.168.100.104</param-value>
</context-param>

== keystone-service_port

Keystoneサービスのポートナンバーを特定します。

[source]
<context-param>
  <param-name>keystone-service_port</param-name>
  <param-value>35357</param-value>
</context-param>

== keystone-admin_token

APIが、Keystoneにリクエストを作るために使用するKeystone内のアドミンユーザーのトークンを特定します。

[source]
<context-param>
  <param-name>keystone-admin_token</param-name>
  <param-value>secret_token_XYZ</param-value>
</context-param>

== auth-admin_role

MidoNet内のアドミンユーザー名を特定します。アドミンは、全てのリソースにリードおよびライトアクセスを持っています。OpenStackの”アドミン”ロールを再利用することを推奨します。MidoNet向けに別途アドミンロールを作成することも選択可能です。

[source]
<context-param>
  <param-name>auth-admin_role</param-name>
  <param-value>admin</param-value>
</context-param>

== keystone-tenant_name

Keystoneにログインする際に使われたテナント名を規定します。Keystoneへのログイン認証には、ユーザーネーム、パスワードそおよびユーザーのテナント名が必要です。ここでテナント名を規定することにより、MidoNet API経由でKeystoneにログインする際にアプリケーションがテナント名を提供する必要を避けることができます。

[source]
<context-param>
  <param-name>keystone-tenant_name</param-name>
  <param-value>admin</param-value>
</context-param>
