[[authentication_services]]

= Available authentication services in MidoNet


The MidoNet Cluster package includes two authentication providers: _Keystone_
authentication and _mock_ authentication. You can select the current
authentication provider by modifying the value of the
`cluster.auth.provider_class` key using `mn-conf` to one of the following
values:

.Authentication Provider Classes
[options="header"]
|====
| Class | Description
| `org.midonet.cluster.auth.keystone.v2_0.KeystoneService` | Uses external
Keystone identity service, version 2.
| `org.midonet.cluster.auth.MockAuthService` | Disables authentication.
|====


This section describes the Keystone authentication service, the mock
authentication and some additional configurations options specific to each
provider.

== Keystone authentication

In order to use the OpenStack Keystone authentication service with MidoNet, you
must configure the `KeystoneService` provider class:

[source]
echo "cluster.auth.provider_class : org.midonet.cluster.auth.keystone.v2_0.KeystoneService" | mn-conf set -t default

[IMPORTANT]
You must restart all MidoNet Cluster instances after changing the authentication
provider.

For additional Keystone configuration options, see
xref:enabling_keystone_authentication[]


== Mock authentication

Mock authentication disables the authentication system by returning a fake
tokens to authenticating clients, and ignoring the sent tokens during
authorization.  To enable the mock authentication configure the
`MockAuthService` provider class.

[source]
echo "cluster.auth.provider_class : org.midonet.cluster.auth.MockAuthService" | mn-conf set -t default

[WARNING]
Mock authentication is the default authentication provider for the MidoNet
Cluster.  However, this mode is used for testing purposes but should not be used
in production.
