[[enabling_keystone_authentication]]
= Enabling Keystone authentication

In order to use the OpenStack Keystone authentication service with MidoNet, you
must configure the following keys in the MidoNet configuration.

++++
<?dbhtml stop-chunking?>
++++

== cluster.auth.provider_class

The fully qualified path of the Java class that provides the Keystone
authentication service.

[source]
org.midonet.cluster.auth.keystone.v2_0.KeystoneService

== cluster.auth.admin_role

Identifies the name of the admin role in MidoNet. The admin has read and write
access to all the resources. We recommend re-using the OpenStack _admin_ role.
Optionally you can create a separate admin role for MidoNet.

== cluster.auth.keystone.protocol

Identifies the protocol used for the Keystone service. The following values
are allowed:

.Keystone Protocol
[options="header"]
|====
| Class | Description
| `http` | Uses plain text HTTP to communicate with the Keystone server.
| `https` | Uses encrypted HTTPS to communicate with the Keystone service
(recommended).
|====

== cluster.auth.keystone.host

Identifies the host of the Keystone service (default is _localhost_).

== cluster.auth.keystone.port

Identifies the port number of the Keystone service (default is _35357_).

== cluster.auth.keystone.admin_token

Identifies the token of the admin user in Keystone that the API uses to make
requests to Keystone.

== cluster.auth.keystone.tenant_name

Specifies the name of the tenant that is used when logging into Keystone.
The log-in authentication to Keystone requires the username, password, and
tenant name of the user. By specifying the tenant name here, you can avoid the
need for applications to supply the tenant name when logging into Keystone
through the MidoNet API.
