[[authentication_roles]]

= Roles in MidoNet

The MidoNet API implements an RBAC mechanism to perform authorization.

Defined in the `AuthRole` class, the roles in MidoNet are:

* Admin: The root administrator of the system. Users with this role are allowed
to do all operations.

* TenantAdmin: Users with this role have write and read access to their own
resources.

* TenantUser: Users with this role only have read access to their own resources.

[IMPORTANT]
Currently, the _TenantAdmin_ and _TenantUser_ roles are not supported.

[NOTE]
Keep in mind that the RBAC policies defined in the external identity services
are not applied to MidoNet RBAC. For example, the type of access you receive in
Keystone does not directly map to the exact same access in MidoNet. The MidoNet
API strictly follows the policies for the three roles described above.

++++
<?dbhtml stop-chunking?>
++++

== Creating admin roles for MidoNet

The authorization service relies on the MidoNet Cluster configuration to
determine the role mapping.


You can use the authorization service to convert the roles in an external
service (like OpenStack Keystone) to those in MidoNet. The following table
contains the configuration keys corresponding to each MidoNet role.

.Authentication Roles
[options="header"]
|===============
|Configuration Key|Value|Description
|cluster.auth.admin_role|<role_name>|
    Specifies the name for the admin role in MidoNet.
|cluster.auth.tenant_admin_role|<role-name>|
    Specifies the name for the tenant admin role in MidoNet.
|cluster.auth.tenant_user_role|<role-name>|
    Specifies the name for the tenant user role in MidoNet.
|===============

You can use the `mn-conf` tool to modify the name used by the identity service
for each role. For example, if the name of the _Admin_ role is `admin`, type:

[source]
$ echo "cluster.auth.admin_role : admin" | mn-conf set -t default

[IMPORTANT]
By default the MidoNet Cluster configuration does not set any name for the
admin roles. Therefore, when using an external identity service that requires
identity roles, such as Keystone, you must set at least the name for the
_Admin_ role.
