[[service_container_scheduling]]
= スケジューリング

MidoNetクラスターは、コンテナサービスを用いて別のComputeホストに存在するサービスをスケジュールします。 コンテナスケジューリングは、次の入力データを考慮します。

* MidoNet エージェントは、そのComputeホストで実行されており、コンテナサービスが有効になっている必要があります。エージェントでのサービスを有効にしたり無効にする方法は、xref:agent_containers_configuration[] をご覧ください。

* NSDBのエージェントホストのコンフィギュレーションの_service container weight_の値は、プラスでなければなりません。xref:service_container_weight[]をご覧ください。

* サービスコンテナグループで定義されたようなコンテナサービスのスケジューリングポリシーxref:service_container_scheduling_policies[]をご覧ください。

* コンテナが最後にスケジュールされたホストにより報告されるコンテナ状態

スケジューリングはコンテナレベルで実行され、コンテナが取り得る以下の状態を考慮します。:

[width="60%",cols="10%,50%",options="header",]
|=======================================================================
|State |Description
|`DOWN` |The container is not scheduled at a host.
|`SCHEDULED` |The container is scheduled at a host, but that host has not yet
reported the container status.
|`UP` |The container is scheduled at a host, and that host has reported the
container status as `running`.
|=======================================================================

 `DOWN `状態のコンテナのみがスケジュールされます。コンテナ作成時、そして、その後使用可能なホストとその_state_ が変化する時にスケジューリングが実施されます。ホスト状態により、そのホストでエージェントがコンテナサービスあるいは対応する_container weight_を実行しているかどうかわかります。

ホストが_ eligible_の場合、コンテナを実行するために選ばれます。つまり、コンテナサービスを実行し、プラスの_ container weight _を持つことについての上記の最初２つの基準を満たし、かつ、当該ホストが同一コンテナに対してこれまでに故障としてマークされていない場合です。 _bad_ ホストとは、コンテナの起動に以前失敗したホストのことです。このようなことは、そのホストが過負荷であったり、コンテナを起動するために必要なソフトウェアがインストールされていない場合に起こり得ます。ホストを _ bad_ とマークするのは一時的な措置です。こうすれば、再スケジューリングするロジックで同じエージェントを際限なくリトライすることを防げます。コンテナ起動に失敗した後、ホストを故障としてマークする時間は、クラスタのコンテナコンフィギュレーションで設定可能です。xref:cluster_containers_configuration[]をご覧ください。


[IMPORTANT]

`scheduler_timeout` と `scheduler_bad_host_lifetime` 設定キーの値は、コンテナが適切にスケジュールされるため最も重要です。これらの値は、コンテナまたはエージェントの故障による許容できるダウンタイムと、ホストでコンテナを開始するために必要な時間の両方を考慮する必要があります。　`IPSEC` コンテナなど、開始するために無視できない時間が必要なコンテナがあります。従って、コンテナのタイムアウトscheduler_timeout）を小さい値にして、故障ホストの有効時間(scheduler_bad_host_lifetime)を非常に大きな値にすると、コンテナがスケジュールされなくなります。少数のcompute ホストで大量のコンテナを生成させようとする時にこのような状況が発生する可能性があります。そのような場合は、 `scheduler_timeout` の値を大きくするか、`scheduler_bad_host_lifetime`をゼロに設定することを推奨します。

ホストが_container weight_により重み付けされている場合は、ホストは条件を満たすホストからランダムに選ばれます。

例: コンテナウェイトの値が1、3、4であるホスト3つには、コンテナを実行するために選ばれる統計的な意味での確率はそれぞれ12.5%、37.5%、 50%になります。


[NOTE]

ホストの_ container weight _を変更してもコンテナの実行には影響がありません。ただし、ゼロにした場合は除きます。

コンテナがスケジュールされた後で、許容されたスケジューラタイムアウト以内にコンテナが`running`であるとエージェントが報告に失敗した場合、スケジューリングロジックが繰り返されます。サービスはホストとコンテナの状態を継続的にモニターし、以下の条件のいずれかが発生した時にコンテナは再スケジュールされます。

* エージェントがシャットダウンしたか故障したため、ホストのコンテナサービスが実行されていない。 

* ホストの_ container weight _ がゼロにセットされた。

* コンテナは`DOWN`状態で、条件を満たすホストのリストが変化した。

* コンテナは`SCHEDULED` 状態で、スケジューリングタイムアウトが時間切れとなった。

* コンテナは`UP`状態で、コンテナ状態は`stopping`、 `stopped` または `error`である。


++++
<?dbhtml stop-chunking?>
++++

[[service_container_weight]]
== ホストのコンテナウェイト

サービスコンテナを実行する条件を満たすかどうかを決定するためにホストのコンテナウェイト(コンテナスケジューリングの間で選択する場合に与えられるべきウェイト)を利用できます。

全ホストに割り当てられたコンテナウェイトを表示するには、以下のコマンドを使用してください。:

[source]
midonet> host list
host host1 name host1 alive true addresses 10.0.0.1 flooding-proxy-weight 1 container-weight 0
host host2 name host2 alive true addresses 10.0.0.2 flooding-proxy-weight 1 container-weight 5
host host3 name host3 alive true addresses 10.0.0.3 flooding-proxy-weight 1 container-weight 10

コンテナウェイトを別の値に変更するには、以下のコマンドを使用してください。:

[source]
midonet> host host1 set container-weight <new-value>

[NOTE]

ホストのコンテナウェイトを変更すると、コンテナスケジューリングに対して直ちに影響を与えます。ウェイトがゼロに設定された場合、そのホストで実行しているまたはスケジュールされていたコンテナすべては、他の資格があるホストへ移動されます。

[[service_container_scheduling_policies]]
== スケジューリングポリシー

MidoNet はサービスコンテナに対してスケジューリングポリシーを3種類サポートします。各ポリシーは、該当するコンテナに、適切なサービスコンテナグループを割り当てることで設定されます。

* _Anywhere Policy_: このポリシーは`hostGroupId`または`portGroupId`いずれにもセットしてないサービスコンテナグループに対応します。このポリシーのコンテナは、コンテナサービスを実行するいずれかのMidoNetホストでスケジュールされ、コンテナウェイトはプラスの値です。

* _Host Group Policy_: このポリシーのコンテナは、サービスコンテナグループのホストグループセットのメンバのホストでだけスケジュールされます。ホストは、さらに選ばれるための条件を満たす必要があります。

* _Port Group Policy_: このポリシーのコンテナは、サービスコンテナグループのポートグループセットのメンバで、外部ポートにバインドされたホストでだけスケジュールされます。ホストは、さらに条件を満たす必要があります。ポートグループポリシーを使用する場合、ポートがホスト間で移動する場合、ホストの集合は変化します。従って、このポリシーは、ポートグループのポートが存在する同一Computeホストでコンテナがスケジュールされることを保証します。ポートグループの詳細情報は、 xref:stateful_port_groups[]をご覧ください。


[IMPORTANT]

ホスト間トラフィックを確保するため、特定スケジューリングポリシーの条件を満たす全ホストは、同一トンネルゾーンで設定される必要があります。コンテナサービスは、ホストを選択する間、トンネルゾーンのメンバであることを必要条件としません。
