[[router_peering]]
= ルータピアリング

MidoNetのルータピアリング接続機能はVXLANトンネリングを利用する複数のサイトの間でオーバーレイ接続をすることができます。この章では、ルータピアリング接続を設定するためのニュートロンCLIとREST APIのコマンドを説明する。これらの操作は、クラウド管理者のみに可能なものです。

文章中には、次の単語が使用されます。:

* VTEPルータ:
+
両方の接続先においてVXLAN端点である、管理者所有のルータ。VXLAN技術を用いて接続先同士をつなぐ仮想ゲートウェイデバイス。

* ゲートウェイデバイス:
+
クラウド上のゲートウェイデバイスの抽象概念。VTEPルータはゲートウェイデバイスの一例である。これによって、将来的にハードウェアVTEPのようなほかのゲートウェイデバイスを定義することができる。 

* トンネルIP:
+
（外側の）VXLANヘッダーを構成するときにゲートウェイデバイスが利用するIPアドレス。 これらのIPアドレスはゲートウェイデバイスにしか知らされない。 特記すべきこととしては、これらは特定ポートとは特に関連付けられていないのでVXLANトラフィックはどこのエッジルータポートからも出入り（egress/ingress）可能なことである。

* マルチサイトネットワーク:
+
複数のサイトに広がる管理者所有のネットワーク。 「インター・AZネットワーク」と呼ばれることもある。このネットワークは、アップリンクネットワークのL2セグメントを作るテナント毎に割り当てられたプライベートCIDRを含みます。
このCIDRが実際にサイトをまたがって、同じCIDRを持つネットワークにマッピングされます。


* ピアルータ:
+
複数のサイト上にまたがるマルチサイトネットワークに接続するテナントルータ。通常このルータは、インターネット接続用に外部ネットワークをすでに持っている。ピアルータリングをするときには、マルチサイトネットワークに接続するためのもう1つのルータインターフェースができる。

*  ピアルータポート:
+
ピアルータに接続された、マルチサイトネットワーク上に作られるルータインタフェイスポート。このポートは、ピアルータに繋がれたプライベートテナントのトラフィックをマルチサイト間で接続する際に、ローカルピアルータのネクストホップとなる。

* VNI:
+
VXLANネットワークの識別に利用される24-bitのVXLANネットワーク識別名。それぞれのマルチサイトネットワークは、ゲートウェイデバイスに接続する際に、一つのVNIと関連付けられており、現時点では、2つのマルチサイトネットワークが、ゲートウェイデバイスにおいて、一つのVNI共有することはできない（この制限は必要に応じて将来外される可能性もある）。

* リモートMACテーブル:
+
VNI、MAC、トンネルIPのマッピングを含む、ゲートウェイデバイス上のテーブル。ゲートウェイデバイスがVXLANパケットを受け取ると、VXLANヘッダーにのるべきVNIと接続先IPアドレスを決定するためにこのテーブルを参照する。
よって、MACアドレスとトンネルIPはリモートサイトのものである。MACアドレスは、リモートピアルータポートにアサインされているMACアドレスを指し、それはゲートウェイデバイスに入るカプセル化される前のパケットの接続先MACアドレスと同じものである。このテーブルと、リモート接続先MACアドレス、パケットが入ってきたマルチサイトネットワークに関連付けられたVNI、を用いて、VXLANヘッダーに用いる接続先トンネルIPアドレスを確定することができる。

* リモート・サイト・ポート:
+
今の時点ではMidoNetは複数のサイト上のVXLANオーバーレイネットワークでのブロードキャストをサポートしていないので、ARPは複数のサイトを横断しては利用できない。この一時的な制限を乗り越えるため、さらには一般的にブロードキャストを避けるため、私たちは「リモート・サイト」ポートの概念を導入する。あるサイトでピアルータポートが作られるときには、もう片方のサイトには、ARPのブロードキャストを避けてマルチサイトネットワークのARP/MACテーブルをシードするために、そのポートのIPアドレスとMACアドレスを知らされている必要がある。そのためには、「リモート・サイト」タイプの特別なポートを全ての「リモート・サイト」のマルチサイトネットワークに作る必要がある。


次の例では、それぞれ各自のMidoNetとOpenStackを導入した2つのサイト、サイトAとサイトBがあります。クラウド管理者と、クラウドサービスを利用するテナントを表す「管理者」と「テナント」の2つのテナントがあります。

次のセットアップが設定されます:

*サイトA*

テナントネットワークCIDR: 10.0.0.0/24

マルチサイトネットワーク(サイトBと一致する必要あり):

* CIDR: 192.168.0.0/24
* VNI: 100

ルーターインターフェースポート (マルチサイトネットワーク < - > ピアルータ):

* IP: 192.168.0.1
* MAC: 16:B7:B5:A4:57:75

ゲートウェイデバイストンネルIP: 200.200.0.1

*サイトB*

テナントネットワークCIDR: 10.0.1.0/24

マルチサイトネットワーク(サイトAと一致する必要あり):

* CIDR: 192.168.0.0/24
* VNI: 100

ルーターインターフェースポート(マルチサイトネットワーク < - > ピアルータ):

* IP: 192.168.0.2
* MAC: 6F:E4:5A:FA:8E:09

ゲートウェイデバイストンネルIP: 200.200.0.2

注意すべき点として、上の例ではゲートウェイデバイストンネルIPが同じサブネットにありますが、実際にはそうである必要はないということだ。IP通信が可能であれば問題ありません。

これから見るように、マルチサイトピアリングの設定は多くのAPI操作とサイト間の調整が必要で、間違いを起こしやすくなっています。よって、以下のステップは外部のサービスによってオーケストレーションされ、自動化されることを推奨します。
