[router_peering_create_multiside_network]
= マルチサイトネットワークと L2 ゲートウェイ接続の作成

次のステップは、複数のサイトにまたがるL2セグメントとなるNeutronネットワークを作ることです。このネットワークは、両方のサイトに存在し、同じCIDRとVNIをも共有する必要があります。また、L2ゲートウェイ の論理構成にゲートウェイデバイスを関連付けることで、L2ゲートウェイデバイスになります。

L2ゲートウェイ接続ID: b0aef454-a7a5-11e5-8378-b3df9d563488

重要なのは、ネットワーク上でIPアドレスが予約されてしまわないように「--no-gateway」を指定することです。また、VMを直接ネットワーク上に起動する場合、（「-disable-dhcp」を外すことで）DHCPを動作可能にすることもできます。しかし、この場合、DHCPポート用にIPアドレスが割り当てられることに注意してください。

必須となる「segmentation_id」はVNIで、文字列の形式でなければなりません。L2ゲートウェイの「devices」フィールドはリストになっていますが、1つのデバイスにしか供給されません。


*サイト A*

[source]
----
# neutron net-create \
   --tenant-id tenant \
   --port-security-enabled=False \
   SiteAMultiSiteNetwork
----

Network ID: 7d107e3a-a7a3-11e5-986c-7b399d0489a5

[literal,subs="quotes"]
----
# POST http://neutron_api_url/l2-gateways
   '{"l2_gateway": {
      "tenant_id": "admin",
      "name": "SiteAL2Gateway",
      "devices": [{"device_id": "5f1a1a9a-a7a2-11e5-8bde-8b2506f539f8"}]}}'
----

L2 Gateway ID: ea57e7e8-a7a4-11e5-89c2-b78c120baeb9

[source]
----
# neutron subnet-create \
   --tenant-id tenant \
   --no-gateway \
   --no-dhcp \
   7d107e3a-a7a3-11e5-986c-7b399d0489a5 \
   192.168.0.0/24
----

Subnet ID: 15f9485c-a7a4-11e5-850b-0b488249b443

[literal,subs="quotes"]
----
# POST http://neutron_api_url/l2-gateway-connections
   '{"l2_gateway_connections": {
      "tenant_id": "admin",
      "network_id": "7d107e3a-a7a3-11e5-986c-7b399d0489a5",
      "segmentation_id": "100",
      "l2_gateway_id": "ea57e7e8-a7a4-11e5-89c2-b78c120baeb9"}}'
----

L2 Gateway Connection ID: b0aef454-a7a5-11e5-8378-b3df9d563488

*サイト B*

[source]
----
# neutron net-create \
   --tenant-id tenant \
   --port-security-enabled=False \
   SiteBMultiSiteNetwork
----

Network ID: 8943d506-af84-11e5-bb39-e7d07e647dfc

[literal,subs="quotes"]
----
# POST http://neutron_api_url/l2-gateways
   '{"l2_gateway": {
      "tenant_id": "admin",
      "name": "SiteBL2Gateway",
      "devices": [{"device_id": "8e47afce-af83-11e5-9b76-4b95f3de9711"}]}}'
----

L2 Gateway ID: 9514751c-af83-11e5-ac3c-affb2bc390ae

[source]
----
# neutron subnet-create \
   --tenant-id tenant \
   --no-gateway \
   --no-dhcp \
   8943d506-af84-11e5-bb39-e7d07e647dfc \
   192.168.0.0/24
----

Subnet ID: 90e9c6b2-af84-11e5-b12b-af7d2f9c54f7

[literal,subs="quotes"]
----
# POST http://neutron_api_url/l2-gateway-connections
   '{"l2_gateway_connections": {
      "tenant_id": "admin",
      "network_id": "7d107e3a-a7a3-11e5-986c-7b399d0489a5",
      "segmentation_id": "100",
      "l2_gateway_id": "ea57e7e8-a7a4-11e5-89c2-b78c120baeb9"}}'
----

L2 Gateway Connection ID: b0aef454-a7a5-11e5-8378-b3df9d563488

IPアドレスがこのネットワーク上で予約されてしまわないように、`--no-gateway`を指定しておくことが重要です。また、もしこのネットワーク上で直接VMを立ち上げるなら、DHCPを有効化(remove`-disable-dhcp`)することも可能です。しかし、その場合は、IPアドレスはDHCPポートに配置されます。

必須となる `segmentation_id` は VNIで、文字列形式でなくてはいけません。L2ゲートウェイの`devices` はリストですが、一つのデバイスのみが与えられます。