[[midolman_behavior_on_cassandra_failure]]
= ノードがフェイルした時のMidolmanのビヘイビア

カサンドラノードがフェイルした時に、期待されるビヘイビアは以下の通りです

この期間の間、カサンドラに対する一定のコールのフローが発生すると想定しています。ノードに対する接続性がフェイルした時をt=0として、そこから時間を記録していきます。

* 2.5秒以内（thrift_socket_timeout設定を設定することで決定できます。xref:midolman_configuration_options[] を参照ください）にMidolmanに例外がでてきて、タイムアウトであることを提示します。これは、プールにアサインされたクライントの一つが利用不可になったことを示唆しています。

この後で二つのオプションがあります:

. host_timeout_windowミリ秒以下（xref:midolman_configuration_options[]を参照ください）でhost_timeout_counter以上のタイムアウトを、ホストタイムアウトトラッキングメカニズムは検知します。これが一番早いオプションですが、短い時間で、多くのタイムアウトを生じさせる必要があります。
+
* これは利用者にとって、特に問題になっています。なぜなら、Cassandraにはできるだけ、頻度少なく繋ごうとしており、多くのパケットがフローをヒットしてしまいます。タイムアウトとラッカーにヒットすることは、より高いトラフィックを必要になるからです。
+
* ウィンドウサイズを増やしたり、カウンターを増やしたり、もしくはその両方を行うことで、診断ノードのフェイルした時に備えて、より厳格な設定にします。

. 所与のホストのクライアントプールは使い切られてしまうことがあります。これが起こるタイミングは、どれくらいの数のクライアントがホストプールにあるかどうかに依拠します。

max_active_connectionsによってクライアントの最大数は決定されます：ホストのキューからクローズされたり、取り除かれるために、各クライアントは最低でも一度は、タイムアウトしなければなりません。

最も遅い場合として、max_active_connections と thrift_socket_timeout を積算した秒数かかることがあります。
