[[midolman_configuration_options]]
= MidoNet エージェント (Midolman)設定オプション

このセクションは、MidoNet エージェントの設定オプションすべてをカバーします。

+zookeeper.session_gracetime+ と +agent.datapath.send_buffer_pool_buf_size_kb+
の設定値のみを除いて、デフォルトバリューの変更は推奨しません。

[WARNING]
本当に必要が無い限り、ルートキー、クラスター名、キースーペースの変更を避けてください。

++++
<?dbhtml stop-chunking?>
++++

== ZooKeeperクラスターのフェイルの後のMidoNetビヘイビア

MidoNetエージェント、Midolmanで走っているノードは、バーチャルネットワークトポロジーオンデマンドのピースをロードするために、ライブのZooKeeperセッションに依拠しています。また仮想デバイスへのアップデートを監視しています。

ZooKeeperにアクセスできなくなった時に、MidoNetエージェントのインスタンスは同じZooKeeperセッションをキープしている期間中に接続性をリカバリーする可能性がある時は、オペレーションが継続されます。mn-conf(1) のzookeeper
session_gracetime設定を編集することで管理できるセッションタイムアウトによって、オペレーティングタイムの量は検知されます。

一旦セッションが時間切れになったら、MidoNetエージェントは終了し、自らシャットダウンし、再ローンチするためのアップスタートのプロンプトを行います。

session_gracetime内でセッションとZooKeeperコネクションが復旧した場合は、MidoNetエージェントのオペレーションは、イベントを起こさずに再開します。MidoNetエージェントは、接続が解除されている間に仮想トポロジーで起こっている更新情報に関して学習を行います。内部の状態とフローテーブルを更新します。

MidoNetエージェントがZooKeeperから切り離されて走っている時や、セッションから戻るのを待っている時は、トラフィックは継続して処理されますが、以下のように機能性は制限されます。

* MidoNetエージェントは、仮想トポロジーへの更新は参照しません。したがって、
session_gracetimeが経過しすぎているネットワークトポロジーのバージョンでパケットは処理されることがあります。

* MidoNetエージェントは、ネットワークトポロジーの新しいピースのロードを行うことができません。ある特定のMidoNetエージェントにロードされたことのないデバイス上を通っていくパケットはエラーアウトされます。

* MidoNetエージェントは、Address Resolution Protocol (ARP) テーブルや Media Access Control (MAC)ラーニングテーブル の更新を参照したり、処理をすることができません。

時間が経つに連れて、MidoNetエージェントはどんどん使えなくなってしまいます。上に示されているトレードオフ条件はセンシブルなsession_gracetimeバリューを選択する際のキーになります。このバリューのデフォルト値は30秒です。

ZooKeeperの接続性は、MidoNet APIサーバーにとって問題ではありません。APIリクエストはステートレスで、ZooKeeperの接続性が無い時は、単純にフェールしてしまいます。

== ZooKeeper設定

+mn-conf(1)+ の ZooKeeper 設定のセクションを使って、以下を調整します。

* ZooKeeperセッションタイムアウトバリュー（ミリ秒単位） このバリューは、 ZooKeeper and と MidoNetエージェントの間の接続性に対して、システムがいつ介入するかを決定します。

* セッショングレースタイムアウトバリュー (ミリ秒単位) このバリューはエージェントがノードの停止を起こさずにZooKeeperに再接続できる期間を決定します。

* MidoNetデータのルートパス

[source]
----
zookeeper {
    zookeeper_hosts = <カンマ区切りのIPアドレス>
    session_timeout = 30000
    root_key = /midonet/v1
    session_gracetime = 30000
}
----

== Cassandra 設定

以下を調整する為にCassandra設定を活用できます。

* データベースの複製ファクター

* MidoNetクラスター名

[source]
----
cassandra {
    servers = <カンマ区切りのIPアドレス>
    replication_factor = 1
    cluster = midonet
}
----

== データパス設定

The agent uses a pool of reusable buffers to send requests to the datapath. You
may use the options in the +agent.datapath+ of mn-conf(1) to tune the pool's size
and its buffers. One pool is created for each output channel, the settings
defined here will apply to each of those pools.

Midolmanはデータパスにリクエストを送る為の再利用可能なバファーのプールを使います。プールサイズとバファーのチューニングを行う為に mn-conf(1) の +agent.datapath+ セクションのオプションを使うことができます。ひとつのプールは各アウトプットチャネルのために作られます。ここで、定義される設定は、それらの各プールに適用できます。

パケットサーズが、最大のバファーサイズを超えてしまったために、パフォーマンスが落ちてしまったことに気づいたときは、buf_size_kb設定の値を上げることができます。この設定はバファーサイズ（KB単位）をコントロールします。このバファーサイズはMidoNetエージェントが送ることができるパケットサイズの上限を規定します。Jumboフレームが横切るネットワークの中では、サイズを調整しましょう。そうすることで、一つのバファーが全体のフレームに乗っかることができ、フローアクションのために十分な余力も残すことできます。

== BGP フェールオーバー設定

デフォルトのBGPフェールオーバー時間は2,3分です。しかし、セッションの両端のいくつつかのパラメーターを変えることによってこの時間を減らすことができます： +mn-conf(1)+（MidoNet側）とBGPピア設定のリモート側です。下記の事例は、　MidoNet側でフェールオーバー時間を１分に減らすやり方を示している事例です。

[source]
----
agent {
    midolman {
        bgp_connect_retry=1
        bgp_holdtime=3
        bgp_keepalive=1
    }
}
----

ホストの mn-conf の設定は、BGPピア設定のリモートエンドのものとマッチしている必要があります。設定に関するより詳細な情報はxref:bgp_failover[]をご参照ください。
