[[midonet_config]]
= MidoNet 構成：mn-conf(1)

MidoNet は、ネットワークトポロジデータの保存に使用するものと同じ ZooKeeper クラスタに構成を保存します。

構成の読み取りと管理は、mn-conf(1) コマンドラインツールで行えます。
詳細については、マニュアルページを参照してください。概要については、次の段落を参照してください。

== ブートストラップ 

MidoNet の構成全体は ZooKeeper に保存されますが、オペレーターは mn-conf 自体を Zookeeper クラスタにポイントする必要があります。
エージェントなどの MidoNet プロセスにも同じことが当てはまります。構成は ZooKeeper から取得しますが、そのプロセスをブートストラップするにはアドレスが必要です。

ブートストラップ構成は、設定の順序で次のソースから読み取られます。

* 環境変数 MIDO_ZOOKEEPER_HOSTS と MIDO_ZOOKEEPER_ROOT_KEY

* +~/.midonetrc+

* +/etc/midonet/midonet.conf+

* +/etc/midolman/midolman.conf+ (for backwards compatibility).

これらのファイルは .ini 形式になっている必要があり、次のようになります。

[source]
----
[zookeeper]
zookeeper_hosts = 127.0.0.1:2181
root_key = /midonet/v1
----

[WARNING]
自分が行っている操作がどのような結果になるかわからない場合は、ルートキーを変更しないでください。

== 構成ソース

mn-conf では、少数のさまざまな構成ドキュメントを保存して管理できます。

* ノード固有の構成。 UUID で識別される、特定の MidoNet ノードのみに適用される構成キーが含まれます。

* 構成テンプレート。 構成チャンクであり、ユーザーが指定した名前で保存され、一連の MidoNet ノードに割り当てることができます。

* "default" 構成テンプレート。 これに含まれる構成キーは、システムのすべての MidoNet ノードによって使用されます。ただし、最初の 2 つのソースが値を無効にしない場合に限られます。

* 構成スキーマ。読み取り専用であり、MidoNet のすべての構成キーのデフォルト値とドキュメンテーション文字列が含まれます。このスキーマに含まれるデフォルトは、優先順位の高いソースのいずれかによって無効にされない場合に限って適用されます。

mn-conf コマンドを 1 回実行するだけでスキーマがダンプされ、既存のすべての MidoNet 構成キー、デフォルト値、ドキュメンテーションの完全なリストを効率的に取得できます。

[source,bash]
$ mn-conf dump -s
