[[midolman_behavior_on_cassandra_failure]]
= Agent behavior on node failure

The MidoNet Agent writes to Cassandra asynchronously after processing a packet
that produced stateful connection data, such as NAT mappings or connection
tracking keys.

The data written to Cassandra is purely a back up, as MidoNet agents share all
stateful connection data directly amongst themselves. The back up is used upon
agent reboot (to prevent lost connections across the reboot) and upon port
migration. An agent binding a port will fetch the existing connection state
from Cassandra for all connections traversing that port.

Should a Cassandra node fail, agents connected to it will fail over to other
nodes in the Cassandra cluster. If the host tries to bind a port during that
interval it may fail to fetch the state for the port, breaking pre-existing
connections on that port. Additionally, state for flows processed during that
interval may not be written to Cassandra, making it unavailable if it's needed
later in the process of binding a port. State is refreshed every minute, thus
a port migration would only break connections that were established in the
minute prior to the port migration and only if the disconnection happened
in that interval.
