[[midolman_behavior_on_cassandra_failure]]
= Midolman behavior on node failure

As described, when a Cassandra node fails, the expected behavior should be as
follows.

We assume there is a constant flow of calls to Cassandra during the period. All
times are taken from a t=0 point when the connectivity to the node starts
failing.

* Within 2.5 seconds (as determined by the thrift_socket_timeout config setting,
see also xref:midolman_configuration_options[]), an exception should appear in
Midolman advising it about a timeout. This implies that one of the clients
assigned to the pool has become unavailable.

After this, there are two options:

. The host timeout tracking mechanism will detect more than host_timeout_counter
timeouts in less than host_timeout_window milliseconds (see also
xref:midolman_configuration_options[]). This is the fastest option, but requires
that many timeouts happen within a short period of time.
+
* Note that this may be especially problematic for us, because we try to go to
Cassandra as little as possible and many packets will be hitting flows. Hitting
the timeout tracker case requires higher traffic.
+
* Increase the window size, or increase the counter, or both, to be stricter
when diagnosing node failures.

. The pool of clients in the given host becomes exhausted. The time for this to
happen depends on how many clients are present in the host's pool. The maximum
number of clients is determined by max_active_connections: each of the clients
will have to timeout at least once to be closed and removed from the host's
queue. This is the slowest case, it may take up to max_active_connections *
thrift_socket_timeout seconds.
