[[api_configuration_options]]
= Advanced MidoNet REST API configuration options

This section describes the configuration options for advanced users. The
values for the following keys are modified using the MidoNet configuration
tool, `mn-conf`. For more information on the MidoNet configuration, see
xref:midonet_config[].


++++
<?dbhtml stop-chunking?>
++++

== Configuration options

.Admin Roles
[options="header"]
|===============
|Configuration Key|Default Value|Description
|`cluster.rest_api.enabled`|`true`|
    Specifies whether the REST API service is enabled at the MidoNet cluster
    instance where the configuration applies.
|`cluster.rest_api.http_port`|8181|
    Specifies the listening port for the HTTP end-point.
|`cluster.rest_api.https_port`|8443|
    Specifies the listening port for the HTTPS end-point.
|===============


== Specifying the private and public keys for HTTPS

To enable the HTTPS end-point of the MidoNet Cluster REST API service, you must
configure a JKS key store containing the private and public key X.509
certificate used for encrypting such connections.

The REST API service uses Jetty as the underlying HTTP server. We recommend to
use the Jetty official documentation to create the key store, or add your
private and public key certificate to an existing one:
https://www.eclipse.org/jetty/documentation/current/configuring-ssl.html

The location of the key store file and the password for the private key are
specified as the following Java system properties.

.System Properties for the HTTPS Key Store
[options="header"]
|===============
|Property Name|Default Value|Description
|`midonet.keystore_path`|`/etc/midonet-cluster/ssl/midonet.jks`|
    The name of the key store file.
|`midonet.keystore_password`|_none_|
    The password for the private key entry. If not set, the HTTPS end-point of
    the REST API will be disabled (default).
|===============

To change the previous properties, and enable HTTPS, you can add the
corresponding property values to the environmental MidoNet Cluster
script file found at `/etc/midonet-cluster/midonet-cluster-env.sh`:

[source]
JVM_OPTS="$JVM_OPTS -Dmidonet.keystore_path=<key-store-file>"
JVM_OPTS="$JVM_OPTS -Dmidonet.keystore_password=<key-entry-password>"
