= Controller Node

[IMPORTANT]
Follow the Red Hat documentation's
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/5/html/Installation_and_Configuration_Guide/sect-Configure_the_Networking_Service.html[7.5. Configure the Networking Service]
instructions, but *note the following differences*.

. *7.5.1. Configure OpenStack Networking Service Authentication*
+
====
Apply as is.
====

. *7.5.2. Configure RabbitMQ Message Broker Settings for the Networking Service*
+
====
Apply as is.
====

. *7.5.3. Set the OpenStack Networking Service Plug-in*
+
====
Do *not* apply. Instead, perform the following steps:

.. Edit the `/etc/neutron/neutron.conf` file and add the following keys
to the `[DEFAULT]` section:
+
[source]
----
[DEFAULT]
...
core_plugin = midonet.neutron.plugin.MidonetPluginV2
allow_overlapping_ips = True
----
+
[NOTE]
Make sure to not leave any space at the starting of lines in any configuration
file (this applies to all configuration files).

.. Create the directory for the MidoNet plugin:
+
[source]
----
mkdir /etc/neutron/plugins/midonet
----

.. Create the `/etc/neutron/plugins/midonet/midonet.ini` file and edit it to
contain the following:
+
[literal,subs="quotes"]
----
[DATABASE]
sql_connection = mysql://neutron:**_NEUTRON_DBPASS_**@*_controller_*/neutron

[MIDONET]
# MidoNet API URL
midonet_uri = http://*_controller_*:8080/midonet-api
# MidoNet administrative user in Keystone
username = *_midonet_*
password = *_MIDONET_PASS_*
# MidoNet administrative user's tenant
project_id = service
----

.. Create a symbolic link to direct Neutron to the MidoNet configuration:
+
[source]
----
# ln -s /etc/neutron/plugins/midonet/midonet.ini /etc/neutron/plugin.ini
----
====

. *7.5.4. VXLAN and GRE tunnels*
+
====
Do *not* apply.
====

. *7.5.5. Configure Open vSwitch tunneling*
+
====
Do *not* apply.
====

. *7.5.6. Configure the OpenStack Networking Service Database Connection*
+
====
Do *not* apply.
====

. *7.5.7. Create the OpenStack Networking Database*
+
====
Do *not* apply.

Instead, create the database as follows:

[literal,subs="quotes"]
----
$ mysql -u root -p
CREATE DATABASE neutron;
GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'localhost' IDENTIFIED BY '*_NEUTRON_DBPASS_*';
GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'%' IDENTIFIED BY '*_NEUTRON_DBPASS_*';
----
====

. *7.5.8. Launch the OpenStack Networking Service*
+
====
Apply as is.
====
