[[midolman]]
= Midolman

Midolman（MidoNetエージェント）は、トラフィックがMidoNetを通過するすべてのホスト上で実行するデーモンです。

Open vSwitchカーネルモジュールにネットワークトラフィックの処理方法（パケットに適用する修正およびそのトンネルする先）を指示します。

MidolmanはOpen vSwitchカーネルモジュールをインストールしたLinuxカーネル、およびユーザー空間にJava 7ランタイムが必要です（OpenJDK 7推奨）。

MidolmanはOpen vSwitchカーネルモジュールバーション1.10.2 以降に対応しています。 カーネルモジュールをアップデートする必要がある場合、このモジュールの新しいバージョンは使用中のディストリビューションのクラウドソフトウェアレポジトリにあります。

++++
<?dbhtml stop-chunking?>
++++

== Recommended installation nodes

Midolmanをネットワーク仮想マシンとして使用している場合、一般的にはハイパーバイザとともにホストマシンにインストールする必要があります。

BGP（ボーダーゲートウェイプロトコル）で使用する場合、BGPピアのホップがほとんどない状態（理想的には1）でノードにインストールする必要があります。 MidoNetに縦方向のトラフィックがある場合、Midolmanはトラフィックを処理するアップリンクに対して帯域幅とプロキシが十分なマシンにインストールする必要があります。

== Configuration guidelines

Midolmanでは、Midolmanの設定ファイルでZooKeeperおよびCassandraサーバーのIPアドレスを指定する必要があります。

Midolmanを設定して、ZooKeeperのセッションタイムアウトとセッション猶予時間の値を減少させるとノードの障害検出が加速されます。 また、それによって、システムが回復可能な一時的な停止がノードの障害として処理されないため、その後の時間も短縮されます。 これらのタイムアウトの値を増やすと、逆の結果になります。 session_gracetimeの設定値以外、デフォルトのタイムアウト値の変更はお勧めしません。

== Network accessibility considerations

同じトンネルゾーンをホストするMidoNetエージェントは相互にIP接続する必要があります。

また、ZooKeeperとCassandraのサーバーへのTCP接続も必要です（ZooKeeperのデフォルトのTCPポート番号は2181、Cassandraは9042です）。

MidoNetエージェントではDNS（Domain Name System）を使用して、ホスト名と下層ネットワークアドレスが変換されます。 MidoNetエージェントをインストールした各サーバーのホスト名が解決可能であることを確認してください。

