[[underlay_network]]
= 下層ネットワーク

下層ネットワークは、MidoNetソフトウェアをホストする物理ネットワークです。

++++
<?dbhtml stop-chunking?>
++++

== GREおよびVXLANトンネル

MidoNetでは、下層の物理ホスト間の通信にトンネルを使用します。 MidoNetは次の2つのトンネルプロトコルをサポートしています。

* GRE（General Routing Encapsulation）プロトコル（MidoNetのデフォルトのトンネルプロトコル）。GREのラッパーサイズは46バイトに固定されています。

* VxLAN（Virtual Extensible LAN）プロトコル。 VXLANでは50バイトのオーバーヘッドが追加されます。

フラグメンテーションとリアセンブルを回避するため、適切なMTU（最大転送単位）を設定してこのオーバーヘッドを許可します。

== 下層ネットワークに対するMTUサイズの注意事項

オーバーヘッドを許可するために、ネットワークのアップリンクと仮想マシンはMTUのデフォルトサイズ（1500）に、GREトンネルを使用する物理ネットワークデバイスのMTUは1546にします。VxLANトラフィックが機能するためには、物理ネットワークデバイスのMTUのサイズを1550にする必要があります。

[IMPORTANT]
仮想マシンのMTUは、ボーダーゲートウェイのアップリンクインターフェイスのMTUを上回らないようにします。

== 上層ネットワークに対するMTUのサイズの注意事項

最適なデータリンクの設定は個々の環境によって異なります。MidoNetはイーサネットのジャンボフレームをサポートしています。ジャンボフレームのサポートを設定する場合、MidoNetネットワークのネットワークインターフェイスのMTUは、下層（物理）ネットワークのMTUのサイズを少なくとも46バイトまたは50バイト下回る必要があります（GREとVXLANをそれぞれカプセル化するため）。仮想ネットワークのトラフィックパスで発生するMTUの不一致に注意してください。このような不一致によって、IPのフラグメンテーション/デフラグメンテーションが起こり、ネットワークパフォーマンスに悪影響を及ぼす可能性があります。

下層ネットワークで1500バイト以上のイーサネットフレームがサポートされない場合、MidoNetネットワークのMTUを1454または1450バイトに設定します（GREとXVLANをそれぞれカプセル化するため）。この設定によって、仮想マシンのネットワークインターフェイスに適切なMTUのサイズを設定することができます。

== L3ゲートウェイアップリンクのNICのオフロード

NICへのオフロードは仲介ホストではなく、エンドホストに対して実行されます。 ゲートウェイアップリンクのNICはルーターのNICと同様に扱う必要があります。

L3ゲートウェイアップリンクのNICでLROが有効な場合、NICは受信したTCPパケットと結合して、宛先のMTUより大きいパケットをMidoNetに渡します。MidoNetではサイズの大きいセグメントはオフロード（LSO-転送前にサイズの大きいTCPを分割）されず、IPフラグメンテーションもサポートされないため、パケットはドロップします。 そのため、L3ゲートウェイアップリンクのNICへのオフロードを無効にする必要があります。アップリンクのNICで次を実行してください。

[source]
----
# ethtool -K p2p1 lro off
----

または、下記をネットワークスクリプトファイルに追加してください。

[source]
ETHTOOL_OPTS="lro off"

