= Controller Node

[IMPORTANT]
Follow the Red Hat documentation's
https://access.redhat.com/documentation/en/red-hat-enterprise-linux-openstack-platform/version-7/red-hat-enterprise-linux-openstack-platform-7-installation-reference/chapter-7-install-openstack-networking/[Chapter 7. Install OpenStack Networking]
instructions, but *note the following differences*.

. *7.1. Install the OpenStack Networking Packages*
+
====
Do *not* apply as is.

Instead, install the following packages:

[source]
----
# yum install openstack-neutron openstack-utils openstack-selinux python-neutron-plugin-midonet
----
====

. *7.2.1. Set the OpenStack Networking Plug-in*
+
====
Do *not* apply. Instead, perform the following steps:

.. Edit the `/etc/neutron/neutron.conf` file and configure the following keys
in the `[DEFAULT]` section:
+
[source]
----
[DEFAULT]
...
core_plugin = midonet.neutron.plugin_v2.MidonetPluginV2
...
allow_overlapping_ips = True
----

.. Create the directory for the MidoNet plugin:
+
[source]
----
mkdir /etc/neutron/plugins/midonet
----

.. Create the `/etc/neutron/plugins/midonet/midonet.ini` file and edit it to
contain the following:
+
[literal,subs="quotes"]
----
[DATABASE]
sql_connection = mysql://neutron:**_NEUTRON_DBPASS_**@*_controller_*/neutron

[MIDONET]
# MidoNet API URL
midonet_uri = http://*_controller_*:8181/midonet-api
# MidoNet administrative user in Keystone
username = *_midonet_*
password = *_MIDONET_PASS_*
# MidoNet administrative user's tenant
project_id = services
----

.. Create a symbolic link to direct Neutron to the MidoNet configuration:
+
[source]
----
# ln -s /etc/neutron/plugins/midonet/midonet.ini /etc/neutron/plugin.ini
----
====


. *7.2.2. Create the OpenStack Networking Database*
+
====
Do *not* apply.

Instead, create the database as follows:

[literal,subs="quotes"]
----
$ mysql -u root -p
CREATE DATABASE neutron character set utf8;
GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'localhost' IDENTIFIED BY '*_NEUTRON_DBPASS_*';
GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'%' IDENTIFIED BY '*_NEUTRON_DBPASS_*';
FLUSH PRIVILEGES;
quit
----

Afterwards, run the `neutron-db-manage` command:

[source]
----
# neutron-db-manage \
  --config-file /usr/share/neutron/neutron-dist.conf \
  --config-file /etc/neutron/neutron.conf \
  --config-file /etc/neutron/plugin.ini \
  upgrade head
----

Followed by the `midonet-db-manage` command:

[source]
----
# midonet-db-manage upgrade head
----
====

. *7.2.3. Configure the OpenStack Networking Database Connection*
+
====
Apply as is.
====

. *7.2.4. Create the OpenStack Networking Identity Records*
+
====
Apply as is.
====

. *7.2.5. Configure OpenStack Networking Authentication*
+
====
Apply as is.
====

. *7.2.6. Configure the Firewall to Allow OpenStack Networking Traffic*
+
====
Apply as is.
====

. *7.2.7. Configure RabbitMQ Message Broker Settings for OpenStack Networking*
+
====
Apply as is.
====

. *7.2.8. Enable SSL Communication Between OpenStack Networking and the Message Broker*
+
====
Apply as is.
====

. *7.2.9. Configure OpenStack Networking to Communicate with the Compute Service*
+
====
Apply as is.
====

. *Configure Load-Balancer-as-a-Service (LBaaS)*
+
====
Additionally to the Red Hat Installation Guide, configure
Load-Balancer-as-a-Service (LBaaS) as described in xref:configure_lbaas[].
====

. *7.2.10. Launch OpenStack Networking* [[neutron_controller_node_installation_finalize]]
+
====
Apply as is.
====

. *7.3. Configure the DHCP Agent*
+
====
Do *not* apply.
====

. *7.4. Create an External Network*
+
====
Do *not* apply.

Instead, create the Neutron networks after the OpenStack and MidoNet
installation is completed.

Any networks that are created before the MidoNet plug-in is active will not be
visible to MidoNet.
====

. *7.5. Configure the Plug-in Agent*
+
====
Do *not* apply.
====

. *7.6. Configure the L3 Agent*
+
====
Do *not* apply.
====
