[[connect_to_vtep]]
= VTEPへの接続

MidoNetをハードウェアVTEPに接続する時にはこの手順を踏みます。あるVTEP上で、いずれかのニュートロンネットワークをポート/vlanペアにバインドしようとする場合には、その前に、必ずこの手順を踏む必要があります。

. 手元にあるスウィッチの文書を参照して、スウィッチ上でVXLANを有効化し、スウィッチを必要なパラメータ全てを備えたVTEPとして設定します。
+
MidoNetは、VTEP上のPhysical_Switchテーブルには、このVTEPのマネージメントIP、マネージメントポートおよびトンネルIPを含むレコードが入っているものと予想します。これら詳細情報は手元に置いておきましょう。これらの詳細情報はVTEPを設定する時、あるいはニュートロンネットワークへのなんらかのバインディングを設定する時には必要になるからです。このテーブルのコンテンツを別場所に書きだす(ダンプする)には次のコマンドを使います。
+
[source]
vtep-ctl list Physical_switch
+
取り扱っているVTEPが、全ての物理的なポートを確実に登録するよう注意を払います。VTEPの中にあるPhysical_Portsテーブルを見れば、登録を検証することができます。このテーブルが表示するポートのみがニュートロンネットワークにバインドさせるものとして利用できます。次のコマンドを使えば物理的なポート全てが表示されますが、その時、Physical_Switchに付与した名前が<vtep_name>に取って代わります。(この点は、前記したコマンド"vtep-ctl list Physical_Switch"を使うことで確認することができます。)
+
[source]
vtep-ctl list-ports <vtep-name>

. VTEPを設定した後、トンネルとの接続状態ならびにマネージメントインターフェースとの接続状態の両方をテストする必要があるかもしれません。いずれの接続状態とも’up’状態であるべきです。
+
マネージメントデータベースへの接続状態をテストするには次の内容を実行します。
+
[source]
$ telnet <management-ip> <management-port>
Trying <management-ip>...
Connected to <management-ip>
Escape character is '^]'.
+
この時点で、これをコンソールにペーストします。
+
[source]
{"method":"list_dbs","id":"list_dbs","params":[]}
+
そうすると、この返信内容を確認することができます。
+
[source]
{"id":"list_dbs","error":null,"result":["hardware_vtep"]}
+
このVTEPの設定を保持しているOVSDBサーバーが、稼働中であり接続を担当しているのだということを検証したところです。同じような返信を受信しなかった場合には、VTEPの設定をもう一度調べてください。

. midonet-api config file/usr/share/midonet-api/WEB-INF/web.xml を修正して、Midonetの中のVXLANサービスを有効にします。

.. midonet-api config file/usr/share/midonet-api/WEB-INF/web.xmlの中で、このsnippetを見つけます。
+
[source]
<!-- VXLAN gateway configuration -->
<context-param>
    <param-name>midobrain-vxgw_enabled</param-name>
    <param-value>false</param-value>
</context-param>
+
そして、<param-value>タグのバリューを’true’に変更してください。

..変更を適用するためにTomcatを再起動します。

. VTEPが正しく設定できたことを確認できれば、VTEPをMidoNet設定に追加することができます。
+
詳細につきましては、xref:cli_add_vtep[]をご覧ください。
+
[IMPORTANT]
VLAN-ポートの割り当て情報、VTEPマネージメントインターフェースIPおよびそのポートに関する情報の他にも、”VTEP"種別のTunnelZoneの識別子情報が必要です。
MidoNet Agentデーモンを実行しているホストのうち、VTEPを使ってVXLANとのVXLANトンネルを作成したいホストについては、このトンネルゾーンのメンバーにならなければなりません。この時には、個々のホストがVXLANトンネルのエンドポイントとして使っているローカルIPを使います。

MidoNet設定にVTEPを追加できましたら、APIサーバーはその(VTEPの)マネージメントインターフェースに接続し、ロジカルブリッジを作成するために必要な情報の全てを収集します。さらに詳しいことにつきましては”Logical Bridge”の章をご覧ください。
