[[connect_vtep_to_neutron]]
= Setting up a connection between a VTEP and a Neutron network

Use this procedure to set up a connection between a VTEP and a Neutron network
in MidoNet.

For this procedure you will need to know the VTEP's management IP and port, the
physical port on the VTEP and the VLAN ID at this port to which you are
connecting, the UUID of the Neutron network which you want to connect to the
VTEP, and the IP addresses of all the hosts on the Neutron network that you want
to communicate with the VTEP.

. Create a tunnel zone of type'vtep'.
+
Issue the following command in the MidoNet CLI:
+
[source]
midonet> tunnel-zone create name vtep_zone1 type vtep
tzone1
+
As you can see you just created a 'vtep' type tunnel zone, tzone1.

. Add a VTEP to MidoNet and assign it to the 'vtep' tunnel zone that you
created.
+
[source]
midonet> vtep add management-ip 192.168.2.11 management-port 6632 tunnel-zone tzone1
name vtep1 description OVS VTEP Emulator management-ip 192.168.2.11 management-port 6632 tunnel-zone tzone1 connection-state CONNECTED
+
If your VTEP had been added successfully you should see a similar message,
saying 'connection-state CONNECTED'.

. Create a binding between the VTEP and a Neutron network behind a
MidoNet bridge. For that, you will need the UUID of the Neutron network behind
that bridge.
+
To find out the UUID use these commands:
+
[source]
midonet> list bridge
bridge bridge0 name public state up
midonet> show bridge bridge0 id
765cf657-3cf4-4d79-9621-7d71af38a298
+
The Neutron network you are binding the VTEP to is behind bridge0, and it has
the UUID of 765cf657-3cf4-4d79-9621-7d71af38a298 as you can see in the output of
the command.

. For the hosts on the Neutron network to be able to communicate with the VTEP,
their IP addressed have to be in the same tunnel zone as the VTEP.
+
====
.. To find out their addresses, use these commands:
+
[source]
midonet> host list
host host0 name rhos5-allinone-jenkins.novalocal alive true
midonet> host host0 list interface
iface veth1 host_id host0 status 3 addresses [u'172.16.0.2', u'fe80:0:0:0:fc2a:9eff:fef2:aa6c'] mac fe:2a:9e:f2:aa:6c mtu 1500 type Virtual endpoint DATAPATH
...

.. Add the host's IP address to the same tunnel zone as the VTEP:
+
[source]
midonet> tunnel-zone tzone1 add member host host0 address 172.16.0.1
====
+
Repeat these steps for every host in the Neutron network that you want to
communicate with the VTEP.
+
[IMPORTANT]
Normally, a host may only be assigned to one tunnel zone, gre or vxlan type. A
host connecting to a VTEP is an exception because you may assign it to two
tunnel zones, a gre/vxlan one and a vtep one.

. Create a binding between the VTEP's vlan 10 and the Neutron network behind the
bridge0.
+
In this example you are connecting the hosts on vlan 10 with the Neutron network
765cf657-3cf4-4d79-9621-7d71af38a298 behind the bridge0:
+
[source]
midonet> vtep management-ip 192.168.2.11 binding add network-id 765cf657-3cf4-4d79-9621-7d71af38a298 physical-port swp1s2 vlan 10

Congratulations, you have just created a binding between the network behind the
VTEP's vlan 10 physical port swp1s2 and the Neutron network with the UUID
765cf657-3cf4-4d79-9621-7d71af38a298 in MidoNet.

[TIP]
To be able to test the connection between the VTEP and MidoNet (i.e. to "ping"
MidoNet from a host on the VTEP) you have to modify the default ingress security
rule, by adding to it the IP address of the host (pinging the host from MidoNet
should work without any additional configuration). For more information, see
xref:connect_vtep_to_midonet[].
