[[vxlan_flooding_proxy]]
= VXLAN フラッディング・プロキシ

MidoNet クラスター・ノード上で動作しているVXLAN ゲートウェイ・コントローラは、スイッチが転送先VMをホストするハイパーバイザーに直接トラフィックをトンネルできるよう、VTEPのMAC リモート・テーブルを追加しようとします。

バーチャル・トポロジーによっては、VTEPに対し、特定の物理機器に対してトンネルを作るように指示することができないことがあります。これは、特にBUM (Broadcast, Unknown and Multicast) トラフィック上で生じます。このような場合MidoNet は、サービス・ノードでシミュレートされ正しい転送先に届けられるよう、サービス・ノードにトンネルを作るようVTEPに指示を出します。そのノードは、「フラッディング・プロキシ」と呼ばれます。:


  - フラッディング・プロキシ (FP) は、VTEPと同じトンネル・ゾーンに属しているすべて
   のMidoNetホストの中から選ばれた単一のノードです。
  - FP は、BUMトラフィックをシミュレートし、転送先（一般的に
    ハイパーバイザー）に対してパケットをトンネリングします。
  - フラッディング・プロキシに故障が生じた場合、MidoNet クラスターは、調整済みのアルゴリズムを使って新しい「フラッディング・プロキシ」役を選び、すべてのBUMトラフィックが新しいプロキシでシミュレーションされるようVTEPに指示します。

MidoNet Agentに割り当てられるウエイトはデフォルトで1に設定されており、MidoNet CLIに以下のコマンドを出すことで、変更できます：

[source]
host <host-alias> set flooding-proxy-weight <new-weight>

ウエイトが高いほど、そのホストがフラッディング・プロキシに選ばれる可能性が高まります。フラッディング・プロキシに設定される候補からAgentを除外するには、０のウエイトを割り当ててください。

フラッディング・プロキシが大量のトラフィックを処理する可能性があることに注意してください。そのような状況が想定される場合、プロキシ専用のホストに、高いウエイトを割り当てることをお勧めします。

