[[cli_list_vtep_bindings]]
= Obtaining descriptions of VTEP bindings

The MidoNet CLI offers a command to obtain the descriptions of all
bindings on a given VTEP, as well as all the VTEPs to which a specific
Neutron network is bound to.

*All bindings in a VTEP*

First, list all the VTEPs in order to identify the desired management IP:

[source]
midonet> vtep list
vtep vtep0 name VTEP-NAME description VTEP-DESCRIPTION management-ip 192.168.2.10 management-port 6632 tunnel-zone tzone0 connection-state connected

*Result*

The following command returns the descriptions of all VXLAN ports and their
Neutron network bindings on the selected VTEP:

[source]
vtep vtep0 list binding
physical-port swp1 vlan 0 network-id 4659a6ab-fcd2-4744-bfbb-6a331164881e
physical-port swp2 vlan 10 network-id 1d475afc-d892-4dc7-af72-9bd88e565dde
physical-port swp3 vlan 20 network-id 4659a6ab-fcd2-4744-bfbb-6a331164881e

From the output you can see a list of all the port-VLAN pairs applied on
a given VTEP.  The following information is displayed (the first line
will be used as example):

* The physical port name (e.g. `swp2`) and VLAN (e.g. `10`).

* The UUID of the Neutron network to which the port-VLAN pair is bound (e.g.,
`1d475afc-d892-4dc7-af72-9bd88e565dde`)

*VTEPs bound in a Neutron network*

First chose the MidoNet bridge corresponding to the desired Neutron
network:

[source]
midonet> bridge list
bridge bridge0 name my_network state up

We can verify the id of this bridge, which will be the same as the
Neutron network:

[source]
midonet> bridge bridge0 show id
4659a6ab-fcd2-4744-bfbb-6a331164881e

List the ports on the bridge:

[source]
midonet> bridge bridge0 port list
port port0 device bridge0 state up
port port1 device bridge0 state up
port port2 device bridge0 state up vtep vtep0

*Result*

The bridge will complete the list of ports with one entry for each of
the VTEPs that contain at least one binding.  In this case we see that
the Neutron network is bound to port-VLAN pairs at VTEPs 192.168.2.10
(as shown in the `list binding` example above).
