[[vxlan_gateway]]
= VXLAN Gateway

The VXLAN Gateway (VXGW) allows a virtual bridge to be extended to a
physical L2 segment that is reachable via an L3 network and a
VXLAN-capable physical switch.

A VXLAN-capable physical switch is also referred to as a _hardware VTEP_
(VXLAN Tunnel End Point). The VXGW allows creating one or many
VXLAN-based Logical Switches that span any number of hardware VTEPs and
a single MidoNet-ODP cloud.

The VXGW has the following advantages:

* Provides L2 connectivity between VMs in an overlay and servers in a physical
L2 segment.

* Provides L2 connectivity across an L3 transport network. This is useful when
the L2 fabric doesn't reach all the way from the racks hosting the VMs
to the physical L2 segment of interest.

* Compared to a pure L2 gateway, the VXGW scales better for overlay solutions:

** in a pure L2 solution, traffic between VMs and the physical segment
must be routed through a few  gateway nodes that are physically
connected to the L2 segment. The physical connections are inherently
limited; additionally, their use is limited by protocols like STP.

** with the VXGW, traffic between VMs and the physical segment can be
routed directly between any of the compute hosts and the hardware VTEP.

*VXGW Management*

A VXGW will be formed by binding a Neutron network to any number of
port-vlan pairs on one or multiple VTEPs.

VTEPs implement an abstraction called Logical Switch, independent from
MidoNet.  A Logical Switch represents a virtual L2 segment that connects
VLANs on some of the VTEP's ports.  For example, in a given VTEP "A",
with ports p1, p2, a Logical Switch can be formed by binding (p1, VLAN
40) and (p2, VLAN 30).  A Logical Switch can also extend the L2 segment
to ports on a different VTEP, whereby both devices would tunnelling
traffic on the Logical Switch.

A port-VLAN pair can only be bound to a single Logical Switch.  However,
a given port may be configured multiple Logical Switches as long as the
binding combines different VLANs.

The MidoNet Coordinator (xref:vxlan_coordinator[]) is able to connect to
the Management Service of VTEPs, create and configure Logical Switches
in its OVSDB instance according to the settings applied through the
MidoNet API.  Additionally, the Coordinator is able to extend the
Logical Switch functions described above to a Neutron network.

MidoNet simplifies and automates these configuration details which
remain invisible to the user.  It uses some conventions that may be
useful for two reasons: troubleshooting purposes, and making MidoNet
usage of the VTEP compatible with non-MidoNet related ones.

* MidoNet will create a single Logical Switch in the VTEP to group
all port-VLAN pairs bound to each Neutron network.

* The Logical Switch name will be formed by prepending `mn-` to the
Neutron network ID, being thus unique in a single MidoNet deployment.
Operators are free to create Logical Switches with any name format, but
should never create VTEPs with names prefixed with `mn-`.

* The Logical Switch tunnel key (VNI) is automatically generated by
MidoNet, monotonically increasing from 10000.  Operators are free to use
VNIs from 1 to 9999 for their own purposes.

* When a Neutron network is bound to port-VLAN pairs on multiple VTEPs,
a Logical Switch will be created on each VTEP's database.  However, all
will share the same name and VNID, following the conventions above.

The MidoNet controller will handle the exchange of learned MACs among
all VTEPs and MidoNet's Network State Database (NSDB) automatically.
