[[connect_vtep_to_neutron]]
= VTEPとニュートロンネットワークの接続設定

MidoNetの中で、VTEPとニュートロンネットワークとの間の接続を設定する時にはこの手順を踏みます。

本手順を遂行するには、次に挙げる情報を把握しておく必要があります。VTEPのマネージメントIPならびにそのポート、VTEP上にある物理的なポートおよび接続しようとしているこのポートのVLAN ID、VTEPに接続させようとしているニュートロンネットワークのUUID、そして、VTEPと通信させたい、ニュートロンネットワーク上にある対象ホスト全てのIPアドレス。

. ‘vtep’種別のトンネルゾーンを作成します。
+
VXLANトンネルを使ってVTEPと通信しようとするホストは全て、VTEP種別のトンネルゾーンに所属する必要があります。この時、どのホストも、各々のホストがVXLANトンネルエンドポイントとして使用するIPを使わなければなりません。
+
トンネルゾーンを作成するためには、MidoNet CLIの中で、次のコマンドを発行します。
+
[source]
midonet> tunnel-zone create name vtep_zone1 type vtep
tzone1
+
今、種別’vtep’のトンネルゾーンであるtzone1を作成したことが判ります。

. MidoNetにVTEPを追加して、そのMidoNetを、自分が作成した’vtep’トンネルゾーンに割り当てますが、この時には、MidoNetがVTEPに向けてVXLANトンネルの中で使おうとしていたこのホストのローカルIPを使用します。このIPは、このホストが他のMidoNetホストと通信をする時に使うIPと同じIPかもしれないことを覚えておきます。
+
[source]
midonet> vtep add management-ip 192.168.2.11 management-port 6632 tunnel-zone tzone1
name vtep1 description OVS VTEP Emulator management-ip 192.168.2.11 management-port 6632 tunnel-zone tzone1 connection-state CONNECTED
+
VTEPが上手く追加されると次のようなメッセージが表示されます。
'connection-state CONNECTED'.

. MidoNetブリッジの背後で、VTEPとニュートロンネットワークとの間のバインディングを作成します。そのためには、ニュートロンネットワークのUUIDがそのブリッジの背後になければなりません。UUIDを見つけるには以下のコマンドを使用します。
+
[source]
midonet> list bridge
bridge bridge0 name public state up
midonet> show bridge bridge0 id
765cf657-3cf4-4d79-9621-7d71af38a298
+
VTEPにバインディングしようとしているニュートロンネットワークはbridge0の背後にありますが、そのUUIDが765cf657-3cf4-4d79-9621-7d71af38a298であることが、コマンドの出力内容を見ると判ります。

. ニュートロンネットワーク上にある各種ホストがVTEPと通信できるようにするには、各々のホストのIPアドレスがVTEPと同じトンネルゾーンにある必要があります。
+
====
..それぞれのアドレスをみつけるには、次のコマンドを使用します。
+
[source]
midonet> host list
host host0 name rhos5-allinone-jenkins.novalocal alive true
midonet> host host0 list interface
iface veth1 host_id host0 status 3 addresses [u'172.16.0.2', u'fe80:0:0:0:fc2a:9eff:fef2:aa6c'] mac fe:2a:9e:f2:aa:6c mtu 1500 type Virtual endpoint DATAPATH
...

..VTEPと同じトンネルゾーンにホストのIPアドレスを追加します。
+
[source]
midonet> tunnel-zone tzone1 add member host host0 address 172.16.0.1
====
+
ニュートロンネットワークの中にあるホストの中でVTEPと通信させたいホスト全てについて、その1つずつにたいしてこの手順を繰り返し踏みます。
+
[IMPORTANT]
通常、ホストはgreタイプかvxlanタイプかのいずれか１つのトンネルゾーンにしか割り当てられません。VTEPに接続しているホストというものは例外なのです。なぜならば、その場合には２つのトンネルゾーンに、つまりgre/vxlanタイプとvtepタイプの両方に割り当てることができるからです。そしてこの場合でも、ホストは両方のトンネルゾーンにたいして同じIPを使用することができることを覚えておきましょう。

.VTEPのvlan10とニュートロンネットワークとの間のバインディングをbridge0の背後に作成します。
+
この事例では、bridge0の背後にvlan10上のホスト各種をニューロンネットワーク765cf657-3cf4-4d79-9621-7d71af38a298と接続しています。
+
[source]
midonet> vtep management-ip 192.168.2.11 binding add network-id 765cf657-3cf4-4d79-9621-7d71af38a298 physical-port swp1s2 vlan 10

MidoNetの中で、VTEPのvlan10物理ポートswp1s2の背後にあるネットワークと、UUIDが765cf657-3cf4-4d79-9621-7d71af38a298のニュートロンネットワークとの間にバインディングを作成に成功しました。

[TIP]
VTEPとMidoNetとの間の接続をテストする(つまりVTEP上のホストからMidoNetを”ping”すること）ためには、MidoNetにホストのIPアドレスを追加することによって、進入セキュリティールールを修正する必要があります。(MidoNetからホストをpingするために別途なにかを追加で設定する必要はありません。）さらに詳しいことにつきましてはref:connect_vtep_to_midonet[]を参照してください。
