[[cli_list_vteps]]
= Obtaining a list of VTEPs

Use this command to obtain the list of hardware VTEPs of which MidoNet is aware.

*Syntax*

[source]
list vtep

*Result*

For each VTEP, the command returns this information:

* name

* description

* management IP address

* management port

* tunnel IP addresses

* connection state, which indicates the state of the connection between the
MidoNet cluster node managing the VTEP and the hardware VTEP, and it can be
one of:

  ** `connected` when the cluster node established a connection

  ** `disconnected` when all MidoNet cluster nodes are disconnected from the
  VTEP, such as when no cluster node has started managing the VTEP or when the
  VXLAN Gateway service is disabled across all cluster nodes.

  ** `error` when there is a MidoNet cluster node owning and managing the VTEP
  but establishing a connection to the VTEPs OVSDB database failed.

*Example*

[source]
midonet> list vtep
vtep vtep0 name VTEP-NAME management-ip 192.168.2.10 management-port 6633 connection-state connected
