[[vxlan_gateway]]
= VXLAN ゲートウェイ

VXLAN ゲートウェイ(VXGW)は、仮想ブリッジを、L3ネットワークおよびVXLANが使用可能な物理的スウィッチを通じて連絡可能な物理的なL2セグメントにまで延長することを可能にしてくれます。

VXLANが使用可能な物理的スウィッチは、”ハードウェアVTEP” （VXLANトンネルエンドポイント）とも呼ばれている。VXGWは、１つのあるいはたくさんのVXLANベースのロジカルスウィッチを作成することを許可し、これらのスウィッチは好きなだけの数のハードウェアVTEPに広がることができ、また単一のMidoNet-ODPクラウドにも広がります。

VXGWには次のような利点があります：

**物理的なL2セグメントの中で、オーバーレイやサーバー内において、VM間にL2の接続性を提供します。

*L3転送ネットワーク間にたいして、L2の接続性を提供します。これが役立つのは、L2ファブリックがVMをホストしているラックから該当する物理的なL2セグメントにまで到達することができない時です。

*純粋なL2ゲートウェイと比べると、VXGWスケールのほうがオーバーレイソリューションには向いています：

**純粋なL2ソリューションにおいては、VMと物理的セグメント間のトラフィックは、L2セグメントに物理的に接続しているいくつかのゲートウェイ接続ポイントを通じて経路構築されていなくてはなりません。物理的な接続は本質的に制約を持っています：それに加えて、その使い勝手もSTPといったプロトコールによって制約を抱えています。

**VXGWを用いますと、VMと物理的セグメント間のトラフィックの経路構築は、どのcomputeホスト間、ハードウェアVTEP間を通じてでも直接実現することができます。

*VXGWマネージメント*

VXGWは、ニュートロンネットワークを、１つかあるいは複数のVTEP上にある、好きな数だけのポート-vlanペアとバインドすることで構築することができます。

VTEPは、MidoNetとは独立して、ロジカルスウィッチと呼ばれる抽出物を実装します。このロジカルスウィッチは仮想L2セグメントを代表しており、VLANをVTEPのいくつかのポートに接続しています。たとえば、ある与えられたVTEP”A”が存在した時に、ポートp1とp2を使って、(p1、vlan　40)と(p2, vlan　30)とをバインディングすることでロジカルスウィッチを構築することができます。また、ロジカルスウィッチはL2セグメントを異なるVTEP上にあるポートに延長することもでき、そのことにより、どちらの機器もがロジカルスウィッチ上でトラフィックをトンネル化します。

Port-vlanペアは、ロジカルスウィッチ１つにしかバインドすることができません。しかしながら、バインディングにより複数の異なるVLANが組み合わさる限り、ある付与されているポートには複数のロジカルスウィッチが設定してあるかもしれません。

MidoNetコーディネーター(xref:vxlan_coordinator[])は、VTEPのマネージメントサービスに接続することができますし、また、MidoNet APIを通じて適用された設定に基づき、
自身のOVSDB内でロジカルスウィッチを作成し設定することができます。このコーディネーターはさらに、前述したロジカルスウィッチ機能をニュートロンネットワークに延長することもできます。

MidoNetは、ユーザーの目には見えないこれらの設定の詳細を簡素化し自動化します。MidoNetは、2つの目的から、役に立つかもしれない慣習をいくつか使用します：トラブルシューティングを行なうことを目的として、そして、VTEPのMidoNet使用を、非MidoNet使用のものと互換性を持たせるためです。

*MidoNetは、個々のニュートロンネットワークにバインドしているport-vlanペア全てをグループ化するために、VTEPの中で単一のロジカルスウィッチを作成します。

*ロジカルスウィッチの名前はニュートロンネットワークIDに”mn-“を付け足すことで構築しますので、単一のMidoNetデプロイメントの中では独自の名前となります。オペレーターはロジカルスウィッチの名前形式を自由に選ぶことができますが、VTEPを作成する時にはその名前の先頭に”mn-“を付けることは絶対にしてはなりません。

*ロジカルスウィッチのトンネルキー(VNID)はMidoNetが自動生成し、それは10000から単調に増加します。オペレーターはVNIを自身の目的に応じて、1から9999までの数字を自由に使うことができます。

*ニュートロンネットワークが、複数のVTEP上のport-vlanペアにバインドしている時には、ロジカルスウィッチは各々のVTEPデータベース上に作成されます。ただし、どのロジカルスウィッチもが、前述した慣習に則り、同じ名前と同じVNIDとを共有します。

MidoNetコントローターは、学習したMACを、全てのVTEP間およびMidoNetのネットワークステートデータベース(NSDB)間で自動交換します。
