[[cli_list_vtep_bindings]]
= VTEPバインディング

MidoNet CLIは、与えられているVTEP上の全てのバインディングについての説明を入手するためのコマンドを提供しています。また、MidoNet CLIは、特定のニュートロンネットワークがバインドしているVTEP全てについての説明を入手するためのコマンドも提供しています。

* VTEPの中にある全てのバインディング*

はじめに、VTEP全てをリスト化して、適切なマネージメントIPが特定できるようにします。

[source]
midonet> vtep list
name vtep0 description Vtep1 management-ip 192.168.2.13 management-port 6632 tunnel-zone tzone0 connection-state CONNECTED

*結果*

コマンドが成功しますと、プログラムは、選択したVTEP上にある全てのVXLANポートに関する説明およびそれらVXLANポートとニュートロンネットワークとのバインディング情報を返信します。

[source]
vtep management-ip 192.168.2.13 list binding
binding binding0 management-ip 192.168.2.13 physical-port Te 0/2 vlan 908 network-id bc3afc36-6274-4603-9109-c29f1c12ba33
binding binding1 management-ip 192.168.2.13 physical-port Te 0/2 vlan 439 network-id 1d475afc-d892-4dc7-af72-9bd88e565dde
binding binding4 management-ip 192.168.2.13 physical-port in1 vlan 119 network-id bc3afc36-6274-4603-9109-c29f1c12ba33

出力した内容結果を見ると、与えられたVTEPに適用したポート-vlanペア全てをリストで見ることができます。以下の情報が表示されています(一行目は事例として使用しています)。
* バインディングのアリア (たとえば binding0).

* VTEPのマネージメントIP ( たとえば192.15.112.22)

* 物理的なポート(たとえばTe0/2)ならびにVLAN (908).

* ポート-vlanペアのバインド先であるニュートロンネットワークのUUID (たとえばbc3afc36-6274-4603-9109-c29f1c12ba33)

*ニュートロンネットワークの中でバインドしているVTEP*

はじめに、適切なニュートロンネットワークに対応するMidoNetブリッジを選びます。

[source]
midonet> bridge list
bridge bridge0 name my_network state up

このブリッジのidは検証することができます。このidはニュートロンネットワークと同じidです。

[source]
midonet> bridge bridge0 show id
bc3afc36-6274-4603-9109-c29f1c12ba33

ブリッジ上のポートをリスト化します。

[source]
midonet> bridge bridge0 port list
port port0 device bridge0 state up
port port1 device bridge0 state up
port port2 device bridge0 state up management-ip 192.168.2.13 vni 10012
port port3 device bridge0 state up management-ip 192.168.2.14 vni 10012

*結果*

ブリッジは、バインディングを少なくとも１つ含んだVTEPそれぞれにたいして１つのエントリーを記述して、ポートのリストを完成させます。この事例では、ニュートロンネットワークがVTEP 192.168.2.13(上記の事例の”list binding”に表示してあるとおりです)ならびにVTEP 192.68.2.14（上は事例では省略して表示していません）で、ポート-vlanペアとバインドしていることが判ります。
