[[resource_protection]]
= MidoNets リソースプロテクション

このセクションは、潜在的なルージュVMによって行われるDDS攻撃からMidoNetエージェントを守るための方法が書かれています。

++++
<?dbhtml stop-chunking?>
++++

== 概要

同じハイパーバイザーで走っているVMを走らせているテナント間で、MidoNetはリソースのプロテクションと分離を提供します。MidoNetはVMがイニシエートするMidoNetに対するDenial of Service (DoS)攻撃に対してプロテクションを提供します。これは、カーネルフローテーブルを持っていないパケットをできるだけ早くエミットすることによってプロテクトします。リソースのプロテクション無しに、他のVMからの、もしくは他のVMに向かう新しいフローは、タイムリーに行うことができません。もしくは、フローが全く滞ってしまいます。なぜなら、ルージュVMがパケットをプロセスするエージェントのケイパビリティーのほとんどを取ってしまうからです。テナントが必ずしも信頼できないパブリックのクラウド設定では、これはシリアスな問題として、考慮されます。

== 期待されるビヘイビア

このソリューションが対応する二つのメインの要件があります：

* VMはMidoNetエージェントのプロセシングキャパシティーのかなりの部分を使うことを担保しています。別のVMがエージェントのトータルキャパシティーを超えたレートでパケットを送った場合は、他のVMは、期待されるレートとレイテンシーで新しいフローを設定することができます。

* エージェントのプロセシングキャパシティーをフルに活用していないVMに、エージェントは、プロセシングキャパシティーを公平に再配分します。

カーネルフローテーブルが抜けていて、ユーザースペースにいっている全てのパケットに、MidoNetエージェントはhierarchical token bucket (HTB)を適用します。全てのポートに対して、プロセスキャパシティーを公平に共有します。

MidoNetホストとVTEPの間のトラフィックがリソースの50% を使うことを補償しながら、残りの50%はVMポートで分散される形式で、HTBは設定されます。

システムのトータルバーストキャパシティーを定義するバケットのサイズがヒエラルキーの一番上にあります。このバケットの下に別のバケットがあります。一つがトンネルトラフィック、もう一つがVTEPトラフィックで、もう一つが、VMトラフィックです。これらは、公平にプロセシングキャパシティーを共有します。トンネルトラフィックとVTEPバケットが空になることはありません。VMで共有されているバケットの下に、各VMのバケットがあります。VM共有されているバケットニハ、ゼロケーパビリティーがあります。つまり、これはトークンを蓄積しません：もし、全てのVMリーフバケットがフルだった場合、過剰なキャパシティーが、トンネルトラフィックか、VTEPバケットか、トップレベルバケットに行きます。

== 設定

+mn-conf(1)+ の +agent.datapath+ セクションで、リソースプロテクション設定パラメーターを特定することができます。利用可能なパラメーターは：

* global_incoming_burst_capacity - これは、トップレベルバケットのサイズを規定して、HTBの中の異なったレベル間で分けられるシステムトークンの総数（これはインフライトパケットと対応します）を決定します：トークンがバケットに戻されるレートは、これらが処理されるレートのファンクションに依拠します。

* tunnel_incoming_burst_capacity - これは、トンネルトラフィックに関連するバケットのキャパシティーを規定します。また、MidoNetエージェントが他のエージェントとコミュニケーションするレートを規定します。

* vm_incoming_burst_capacity - これは、VMリーフバケットのキャパシティーを規定します。このパラメーターは、各個別のVMがトラフィックを送れるレートを規定します。

* vtep_incoming_burst_capacity - MidoNetエージェントがVxLANドメインとコミュニケーションできるレートを規定するVxLAN VTEP機能と関連するバケットのキャパシティーを設定します。

上記のパラメーターに関して、+mn-conf(1)+ のスキーマを参照ください。


これらのプロパティに対する推奨値は、MidoNetホストのロール（ゲートウェイかコンピュートノード）や他のソース関連のプロパティー、例えば、JVMメモリーやフローテーブルのサイズなど、とのインターアクションに依拠します。Midolman RPMとDebianパッケージには、コンピュート/ゲートウェイホストにそれぞれチューニングされた設定バージョンを含んでいます。これらの設定は、デフォルトの設定と共に、/etc/midolmanの中にあります。推奨値のリストテーブルは、"Recommended Values"を参照ください。

== リソースプロテクションを無効化する

リソースプロテクションのフィーチャーを無効化できます。

リソースプロテクションを無効化するには：

. 設定のセクションに書かれている全てのパラメーターの値を“０”にします。ただし、global_incoming_burst_capacityパラメーターは除きます。

これにより、全てのトークンが、グローバルバケットに蓄積されるようになり、この一つのバケットから全てのトラフィックがディストリビュートされるようになります。
