[[concept_i13_q4d_q4]]
= Connecting a bridge to a router

You can easily connect a virtual bridge to a virtual router via virtual ports on
the two devices. Make sure you create a bridge and a router with an Interior
port on each device.

[NOTE]
See xref:creating_a_router[] and xref:adding_a_bridge[] for information about
creating routers and bridges and adding router and bridge ports.

To connect a bridge to a router:

. Enter the command to list the bridges on the current tenant:
+
[source]
midonet> list bridge
bridge bridge1 name test-bridge state up

. Enter the command to list the ports on the bridge:
+
[source]
midonet> bridge bridge1 list port
port port0 device bridge1 state up

. Enter the command to list the routers on the current tenant:
+
[source]
midonet> list router
router router1 name test-router state up

. Enter the command to list the ports on the router:
+
[source]
midonet> router router1 list port
port port0 device router1 state up mac 02:a6:81:08:ab:5d address 10.100.1.1 net 10.0.0.0/24

. Enter the command to bind the desired router port (for example, port0 on
router1) to the desired bridge port (for example, port0 on bridge1):
+
[source]
midonet> router router1 port port0 set peer bridge1:port0

. Enter the command to list the ports on the router (in this example, router1):
+
[source]
midonet> router router1 list port
port port0 device router1 state up mac 02:a6:81:08:ab:5d address 10.100.1.1 net 10.0.0.0/24 peer bridge1:port0
+
The above output shows that port0 on router1 is connected to port0 on bridge1.
