= Architecture

[IMPORTANT]
This guide assumes the following system architecture, based on
http://docs.openstack.org/icehouse/install-guide/install/apt/content/ch_overview.html#example-architecture-with-neutron-networking[Figure 1.2. Three-node architecture with OpenStack Networking (neutron)]
of the OpenStack Documentation.

This architecture consists of three hosts:

* Controller Node (*_controller_*)
* Network Node (*_network_*)
* Compute Node (*_compute1_*)

The _MidoNet Network State Database (NSDB)_ uses
https://zookeeper.apache.org/[ZooKeeper]
and
http://www.datastax.com/documentation/cassandra/2.0/cassandra/gettingStartedCassandraIntro.html[Cassandra]
to store network topology and state information. The NSDB components can be
installed on separate hosts, but this guide assumes them to be installed on all
thee nodes (*_controller_*, *_network_*, *_compute1_*).

The _MidoNet Agent (Midolman)_ has to be installed on all nodes where traffic
enters or leaves the virtual topology, in this guide this are the *_network_*
and *_compute1_* nodes.

The _Midonet API_ can be installed on a separate host, but this guide assumes it
to be installed on the *_controller_* node.

The _Midonet Command Line Interface (CLI)_ can be installed on a separate host,
but this guide assumes it to be installed on the *_controller_* node.

The _Midonet Neutron Plugin_ replaces the ML2 Plugin and has to be installed on
all three nodes (*_controller_*, *_network_*, *_compute1_*).

## Hosts and Services

.Controller Node (*_controller_*)
* General
** Database (MySQL)
** Message Broker (RabbitMQ)
* OpenStack
** Identity Service (Keystone)
** Image Service (Glance)
** Compute (Nova)
** Networking (Neutron)
** Dashboard (Horizon)
* MidoNet
** API
** CLI
** Neutron Plugin
** Network State Database (NSDB)
*** Network Topology (ZooKeeper)
*** Network State Information (Cassandra)

.Network Node (*_network_*)
* OpenStack
** Networking (Neutron)
*** DHCP Agent
*** Metadata Agent
* MidoNet
** Agent (Midolman)
** Neutron Plugin
** Network State Database (NSDB)
*** Network Topology (ZooKeeper)
*** Network State Information (Cassandra)

.Compute Node (*_compute1_*)
* OpenStack
** Compute (Nova)
** Networking (Neutron)
* MidoNet
** Agent (Midolman)
** Neutron Plugin
** Network State Database (NSDB)
*** Network Topology (ZooKeeper)
*** Network State Information (Cassandra)
