[[bgp_uplink_configuration]]
= BGP アップリンク構成

MidoNet では、外部接続にボーダーゲートウェイプロトコル（BGP）を利用します。

BGP にはスケーラビリティと冗長性があるため、実稼動環境では BGP を使用することを強くお勧めします。

デモ環境や POC 環境では、代わりに静的ルーティングを使用できます。詳しくは、操作ガイドを参照してください。

こちらの手順では、次のサンプル環境を想定しています。

* フローティング IP ネットワーク 1 個
** _192.0.2.0/24/24_

* MidoNet ゲートウェイノード 2 個
** _gateway1_、_bgp1_ に _eth1_ で接続
** _gateway2_、_bgp2_ に _eth1_ で接続

* リモート BGP ピア 2 個
** _bgp1_、_198.51.100.1_、AS _64513_
** _bgp2_、_203.0.113.1_、AS _64514_

* 対応する MidoNet BGP ピア
** _198.51.100.2_、AS _64512_
** _203.0.113.2_、AS _64512_

次の手順に従って、GBP アップリンクを構成してください。

. MidoNet CLI を起動し、Edge ルーターを検索する
+
[literal,subs="quotes"]
----
midonet-cli> router list
router *_router0_* name *Edge Router* state up
router router1 name Tenant Router state up infilter chain0 outfilter chain1
----
+
この例の場合、Edge ルーターは *_router0_* です。

. BGP セッション用の仮想ポートを作成する
+
リモート BGP ピアごとに、BGP 通信に使用するポートを Edge ルーター上に作成します。
+
[literal,subs="quotes"]
----
midonet> router *_router0_* add port address *_198.51.100.2_* net 198.51.100.0/30
*_router0:port0_*

midonet> router *_router0_* add port address *_203.0.113.2_* net 203.0.113.0/30
*_router0:port1_*

midonet> router *_router0_* port list
port *_port0_* device router0 state up mac ac:ca:ba:11:11:11 address *_198.51.100.2_* net 198.51.100.0/30
port *_port1_* device router0 state up mac ac:ca:ba:22:22:22 address *_203.0.113.1_* net 203.0.113.0/30
[...]
----
+
この例で作成されたポートは、*_port0_* と *_port1_* です。

. 仮想ポートで BGP を構成する
+
[literal,subs="quotes"]
----
midonet> router *_router0_* set asn *_64512_*
midonet> router *_router0_* add bgp-peer asn *_64513_* address *_198.51.100.1_*
*_router0:peer0_*

midonet> router *_router0_* list bgp-peer
peer peer0 asn 64513 address 198.51.100.1

midonet> router *_router0_* add bgp-peer asn *_64514_* address *_203.0.113.1_*
*_router0:peer1_*

midonet> router *_router0_* list bgp-peer
peer peer0 asn 64513 address 198.51.100.1
peer peer1 asn 64514 address 203.0.113.1
----

. MD5認証を追加する必要がある場合：
+
[literal,subs="quotes"]
----
midonet> router *_router0_* bgp-peer *_peer0_* set password *_BGP_PASSWORD_*
midonet> router *_router0_* bgp-peer *_peer1_* set password *_BGP_PASSWORD_*
----

. MidoNetの構成で定義されたデフォルトタイマーより優先されるカスタムタイマーをこのセッションに
与えることができます。
+
[literal,subs="quotes"]
midonet> router *_router0_* bgp-peer *_peer0_* set connect-retry 10
midonet> router *_router0_* bgp-peer *_peer0_* set hold-time 5
midonet> router *_router0_* bgp-peer *_peer0_* set keep-alive 5
midonet> router *_router0_* bgp-peer *_peer1_* set connect-retry 10
midonet> router *_router0_* bgp-peer *_peer1_* set hold-time 5
midonet> router *_router0_* bgp-peer *_peer1_* set keep-alive 5
midonet> router *_router0_* list bgp-peer
peer peer0 asn 64513 address 198.51.100.1 keep-alive 5 hold-time 5 connect-retry 10
peer peer1 asn 64514 address 203.0.113.1 keep-alive 5 hold-time 5 connect-retry 10

. Add routes to the remote BGP peers
+
In order to be able to establish connections to the remote BGP peers,
corresponding routes have to be added.
+
[literal,subs="quotes"]
----
midonet> router *_router0_* route add src 0.0.0.0/0 dst *_198.51.100.0/30_* port *_router0:port0_* type normal
router0:route0

midonet> router *_router0_* route add src 0.0.0.0/0 dst *_203.0.113.0/30_* port *_router0:port1_* type normal
router0:route1
----

. BGPルートをアドバタイズする
+
ホストされている仮想マシンが外部接続できるようにするため、フローティング IP ネットワークを BGP ピアにアドバタイズする必要があります。
+
[literal,subs="quotes"]
----
midonet> router *_router0_* add bgp-network net *_192.0.2.0/24_*
router0:net0

midonet> router router0 list bgp-network
net net0 net 192.0.2.0/24
----

. 仮想ポートを物理ネットワークインターフェースにバインドする
+
Edge ルーターの仮想ポートをゲートウェイノードの物理ネットワークインターフェースにバインドします。
+
[IMPORTANT]
物理インターフェースの状態が `UP` になっていて、IP アドレスが割り当てられていないことを確認してください。

.. MidoNet ホストをリストし、ゲートウェイノードを検索します。
+
[literal,subs="quotes"]
----
midonet> host list
host *_host0_* name *_gateway1_* alive true
host *_host1_* name *_gateway2_* alive true
[...]
----
+
この例のホストは *_host0_* と *_host1_* です。

.. ゲートウェイノードの物理インターフェースをリストします。
+
[literal,subs="quotes"]
----
midonet> host *_host0_* list interface
[...]
iface *_eth1_* host_id host0 status 3 addresses [] mac 01:02:03:04:05:06 mtu 1500 type Physical endpoint PHYSICAL
[...]

midonet> host *_host1_* list interface
[...]
iface *_eth1_* host_id host0 status 3 addresses [] mac 06:05:04:03:02:01 mtu 1500 type Physical endpoint PHYSICAL
[...]
----

.. 物理ホストインターフェースを Edge ルーターの仮想ポートにバインドします。
+
[literal,subs="quotes"]
----
midonet> host *_host0_* add binding port *_router0:port0_* interface *_eth1_*
host host0 interface eth1 port router0:port0

midonet> host *_host1_* add binding port *_router0:port1_* interface *_eth1_*
host host1 interface eth1 port router0:port1
----

.. ステートフルポートグループを構成します。
+
[literal,subs="quotes"]
----
midonet-cli> port-group create name uplink-spg stateful true
*_pgroup0_*
----

.. ポートをポートグループに追加します。
+
[literal,subs="quotes"]
----
midonet> port-group *_pgroup0_* add member port *_router0:port0_*
port-group pgroup0 port router0:port0

midonet> port-group *_pgroup0_* add member port *_router0:port1_*
port-group pgroup0 port router0:port1

midonet> port-group pgroup0 list member
port-group pgroup0 port router0:port0
port-group pgroup0 port router0:port1
----
