[[recommended_hardware]]
= Recommended Hardware

This section provides information about the hardware recommended for a MidoNet
deployment.

.Recommended Deployment Hardware
[options="header"]
|===============
|Hardware|Requirements
|Network State Database, API, and Agent Nodes|
    CPU: 64-bit x86, quad core or above

    Memory: ≥ 32GB RAM

    HDD: ≥ 30GB (available free disk space)

    NIC: 2 x ≥ 1Gbit
|2 x GW Nodes|
    CPU: 64-bit x86, quad core or above

    Memory: ≥ 32GB RAM

    HDD: ≥ 30GB

    Network: 3 x ≥ 1Gbit
|NIC Cards|
    For a high-performance data network: use NICs that support multiple queues
    and MSI-X
|Top of Rack Switch|
    Non-blocking multilayer switch (L2/L3) with jumbo frame support
|Hard Disks|
    Ideally, both the Zookeeper transaction log and Cassandra data files need
    their own dedicated disks, with additional disks for other services on the
    host. However, for small POCs and small deployments, it is ok to share the
    Cassandra disk with other services and just leave the Zookeeper transaction
    log on its own.
|===============
