= Midolman のインストール

仮想トポロジへのトラフィックの出入り口となるすべてのノードには、_MidoNet Agent (Midolman)_
をインストールする必要があります。このガイドでは、*_gateway1_*、*_gateway2_*、*_compute1_*
の各ノードがこれに相当します。

. *Midolman パッケージをインストールする*
+
====
[source]
----
# apt-get install openjdk-8-jre-headless
# apt-get install midolman
----
====

. *リソース使用の設定*
+
====
リソース使用を設定するために　*各エージェントホスト*　で下記の手順を実行します。

[IMPORTANT]
本番環境では *large* （大）テンプレートを強くお勧めします。

.. *Midolman リソーステンプレート*
+
Midolmanリソーステンプレートを設定するためには、次のコマンドを実行します。
+
[source,subs="specialcharacters,quotes"]
----
$ mn-conf template-set -h local -t *_TEMPLATE_NAME_*
----
+
*_TEMPLATE_NAME_* を以下のいずれかのテンプレートに置き換えます。
+
[source,subs="specialcharacters,quotes"]
----
agent-compute-large
agent-compute-medium
agent-gateway-large
agent-gateway-medium
default
----

.. *Java Virtual Machine (JVM) リソーステンプレート*
+
JVMリソーステンプレートを設定するためには、デフォルトの `/etc/midolman/midolman-env.sh`
ファイルを以下のいずれかに置き換えます。
+
[source,subs="specialcharacters,quotes"]
----
/etc/midolman/midolman-env.sh.compute.large
/etc/midolman/midolman-env.sh.compute.medium
/etc/midolman/midolman-env.sh.gateway.large
/etc/midolman/midolman-env.sh.gateway.medium
----
====

. *すべてのエージェントで MidoNet Metadata Proxy へのアクセスを構成する*
+
====
この手順は 1 回だけ実行してください。1 回実行すれば、すべての MidoNet Agent ノードで MidoNet Metadata Proxy がセットアップされます。

次のコマンドを実行して、クラウド全体の値を設定します。

[source,subs="specialcharacters,quotes"]
----
$ echo "agent.openstack.metadata.nova_metadata_url : \"http://**_nova_metadata_host_**:**_nova_metadata_port_**\"" | mn-conf set -t default
$ echo "agent.openstack.metadata.shared_secret : *_shared_secret_*" | mn-conf set -t default
$ echo "agent.openstack.metadata.enabled : true" | mn-conf set -t default
----

*_nova_metadata_host_*、*_nova_metadata_port_*、*_shared_secret_* は適切な値に
置きかえてください。これらの値は対応する Nova Metadata API の設定に
マッチしている必要があります。

*_nova_metadata_host_* と *_nova_metadata_port_* には Nova Metadata API が
要求を受け付けるアドレスを指定します。 *_shared_secret_* には
nova.conf の "neutron" セクション内の "metadata_proxy_shared_secret"
フィールドと同じ値を設定してください。

Nova 側の設定は Neutron Metadata Proxy を使用する場合と同じです。
OpenStack のドキュメントを参照してください。

http://docs.openstack.org/admin-guide-cloud/networking_config-identity.html#configure-metadata[Cloud Administrator Guide: Configure Metadata]
====

. *Midolman を起動する*
+
====
[source]
----
# service midolman start
----
====
