[[zookeeper]]
= ZooKeeper

install_plugins.shスクリプトは、ZooKeeperの露出したJMXマトリクスからグラフを作り出す、Muninプラグインと設定ファイルもインストールします。

それぞれのノードにおいて、ZooKeeperのレプリカ番号を示す必要があります;スクリプトはどのようにしてこの作業を行うかのわかりやすいガイダンスを与えてくれます。

ZooKeeperの統計データはModoStorageグループ"zookeeper"カテゴリー内で見つけることができます。ZooKeeperはリーダー/フォロワーのため、メトリクスを別々のMBeansに分類します。それぞれのノードは同じ値を２回レポートします、一つはフォロワーロール内で、もう一つはリーダーロール内です。与えられたノードはロールを変えることがありえるということをふまえてください(例えば、もしリーダーがシャットダウンしたら、フォロワーノードがリーダーにとってかわることがあり得ます)。これらのイベントは簡単に見ることができます。例えば、"フォロワーとしての接続カウント"内のラインが急に無効になり、"リーダーとしての接続カウント"内に別のラインが現れます。

以下は、MidoNetデプロイメントリポジトリ内で与えられたMunin設定の例からのグラフの説明です。グラフはZooKeeper JMXサービスのサブセットより作られました。利用可能なグラフは、

*コネクションカウント(フォロワー/リーダーとして)*

これらの二つのグラフは任意の時点での、ロールにおけるこのノードへのライブ接続の数を表示しています。

*メモリーデータツリーにて(フォロワー/リーダーとして)*

データノードとウォッチカウント両方の、インメモリーノードデータベースのサイズを表示します。

*レイテンシ (フォロワー/リーダーとして)*

接続内で経験されたレイテンシ平均および最大値を表示します。

*Packet Count (フォロワー/リーダーとして)*

任意の時点において、ロール内でノードにより送信/受信されたパケットのカウントを表示します。

*定数サイズ*

リーダーの選出に合意しているノードの数についてのそれぞれのノードの観点を表示します。

ZooKeeperはそれぞれの特定の接続についての情報も見せます。これはトラブルシューティングの際に役立つかもしれません。
jconsole (http://www.oracle.com/technetwork/java/index.htmlにて "jconsole" と検索をして情報を参照してください)を使って、以下が可能となります。

. ポート9199で、任意のZooKeeperノードに接続します。

. org.apache.ZooKeeperService, ReplicatedServer_idXへナビゲートします。

. 望ましいレプリカを選びます。

. 接続されたクライアントのIPアドレスのリストを見るためのリーダーもしくはフォロワーのコネクションに入ります。ここで見られるインフォメーションは以下を含みます。

* レイテンシ

* パケット送信/受信数

* 特定のクライアントへのセッションIDなど。

グラフの中で値が見られるいくつかのMBeansは、(コンピューター的に強い）興味深いインフォメーションを提供するオペレーションも含んでいます。jconsoleを使って、org.apache.ZooKeeperService、またその後は適切なレプリカそして、そのロールによりリーダーもしくはフォロワーを展開してください。

* InMemoryDataTree.approximateDataSize: インメモリーデータストアのサイズについて示します。

* InMemoryDataTree.countEphemerals: 一時的ノードのカウントについて示します。

インストレーションスクリプトはZooKeeperのJVMの状態についてモニターするグラフも提供します。

* JVM GCタイム

* JVM ヒープサマリー

* JVM ノンヒープサマリー

これらのグラフの説明はこのドキュメントの範囲を超えていますが、高いJVM GCタイムはZooKeeperがMidolmanの問題の元であることを示しています。これは高いレイテンシとCPUリソースの低利用により示されています。ZooKeeperはパラレルコレクターを使い、JVM GCタイムは全ての生成の対応をするjava.lang:type=GarbageCollector,name=PS Scavenge MBeanから、全ての場所での最後のコレクションの時間をトラックします。

