[[munin]]
= Muninのモニタリング

Muninはスレーブノードより定期的に値をフェッチするクーロンベースプロセスをもつマスターノードによりできています。

スレーブノードはさまざまなソース（Java Management Extensions (JMX)を含む）よりメトリクスを抽出するためにmuninノードを実行し、マスターにさらします。データはRRDツールデータベースにフィードされグラフを生成するために使われます。

与えられたサービスにモニタリングを加えることはサービスのインスタンスが実行されるそれぞれのホストにてmuninノードを設定することと、マスターノードにてこのノードよりデータをフェッチするためにMuninを設定することを含みます。

MidoNetデプロイメントリポジトリはmonitoring/munin/にて、全てのサポートされたモニタリングを設定するため自動化されたスクリプトを含みます。

このガイドと自動化された設定スクリプトの情報はmunin 1.4.6-3ubuntu3.3に基づきます。更なるインフォメーションはhttp://munin-monitoring.org/をご参照ください。

== Muninの設定

ドキュメンテーションからのインストラクションに従ってください;このインフォメーションは非常に簡単であり、難しい設定などは一切なしに動く基本の設定ファイルを含んでいます。

*マスターノード*

*munin*と*munin-plug-ins-extra*パッケージをインストールしてください。また、jmx2muninをGitHubリポジトリ(https://github.com/tcurdt/jmx2munin)よりインストールしてください。

マスター設定に新しい2つのスレーブを加えるためには、/etc/munin/munin.confにこれらのサンプル設定を加えてください:

[source]
[MidoStorage;node1]address 10.0.0.1 use_node_name yes

[source]
[MidoStorage;node2]address 10.0.0.2 use_node_name yes

[NOTE]
これら上記のアドレスはサンプルです。これらはノードのIPアドレスである必要であるべきです。

これにより、Muninマスターが与えられたスレーブよりデータファイルをフェッチすることが始まります。"MidoStorage"の名前がMuninインターフェースに両方のノードを含んだグループとして現れます。このガイドの後ほどにあるセクションでサービス特有のグラフをどのようにして加えるかの説明があります。

*スレーブノード*

*munin-node*と*munin-plugin-extra*パッケージをインストールしてください。また、jmx2muninをGitHubリポジトリよりインストールしてください。/etc/munin/munin-node.conf.sampleを再利用して単純にマスターのIPアドレスをアップデートすることができます。

*プラグイン*

Muninはディスク、メモリ、CPUやその他のためのメトリクスを示すいくつかのデフォルトプラグインを提供します。今はこれらは使わないほうがいいかもしれません、なぜならそれぞれのスレーブの/etc/munin/pluginsにあるシンボリックリンクを削除することによって、これらを簡単に取り除くことができるからです。

*MidoNetプラグイン*

MidoNetサブシステムのためにメトリクスをフェッチするには、関連するスレーブに新しいプラグインを加えることとのみが必要です。ほとんど全ての作業ができる自動化されたスクリプトがあります。MidoNetデプロイメントリポジトリを現在のディレクトリでコピーしていると想定して、それぞれのスレーブにて以下のコマンドを実行するのみです:

[source]
sudo ./install_plugins.sh
sudo service munin-node restart

RedHat Enterprise Linux 7にて以下を使うべきです:

[source]
sudo systemctl restart munin-node

これは全ての利用可能なプラグインをインストールし、Munin設定をアップデートします。

マスターへは何もするべきではありません。Muninフェッチプロセスが実行されるとき、データのフェッチが始まるはずです。もし待つのが難しいようであれば、スレーブよりデータを引き出すMuninクーロンジョブを始動させる、以下のコマンドをマスターで実行することもできます:

[source]
sudo -u munin munin-cron
