[[establish_bgp_session]]
= BGP Uplink Configuration

MidoNet utilizes the Border Gateway Protocol (BGP) for external connectivity.

For production deployments it is strongly recommended to use BGP due to it's
scalability and redundancy.

For demo or POC environments, alternatively static routing can be used.

The following instructions assume below sample environment:

* One floating IP network
** _192.0.2.0/24_

* Two MidoNet gateway nodes
** _gateway1_, connecting to _bgp1_ via _eth1_
** _gateway2_, connecting to _bgp2_ via _eth1_

* Two remote BGP peers
** _bgp1_, _198.51.100.1_, AS _64513_
** _bgp2_, _203.0.113.1_, AS _64514_

* Corresponding MidoNet BGP peers
** _198.51.100.2_, AS _64512_
** _203.0.113.2_, AS _64512_

Follow these steps to configure the BGP uplinks.

. Launch the MidoNet CLI and find the Edge Router
+
[literal,subs="quotes"]
----
midonet-cli> router list
router *_router0_* name *Edge Router* state up
router router1 name Tenant Router state up infilter chain0 outfilter chain1
----
+
In this example the Edge Router is *_router0_*.

. Create virtual ports for the BGP sessions
+
For each remote BGP peer, create a port on the Edge Router that is
going to be used for BGP communication.
+
[literal,subs="quotes"]
----
midonet> router *_router0_* add port address *_198.51.100.2_* net 198.51.100.0/30
*_router0:port0_*

midonet> router *_router0_* add port address *_203.0.113.2_* net 203.0.113.0/30
*_router0:port1_*

midonet> router *_router0_* port list
port *_port0_* device router0 state up mac ac:ca:ba:11:11:11 address *_198.51.100.2_* net 198.51.100.0/30
port *_port1_* device router0 state up mac ac:ca:ba:22:22:22 address *_203.0.113.1_* net 203.0.113.0/30
[...]
----
+
In this example the created ports are *_port0_* and *_port1_*.

. Configure BGP on the virtual ports
+
[literal,subs="quotes"]
----
midonet> router *_router0_* set asn *_64512_*
midonet> router *_router0_* add bgp-peer asn *_64513_* address *_198.51.100.1_*
*_router0:peer0_*

midonet> router *_router0_* list bgp-peer
peer peer0 asn 64513 address 198.51.100.1

midonet> router *_router0_* add bgp-peer asn *_64514_* address *_203.0.113.1_*
*_router0:peer1_*

midonet> router *_router0_* list bgp-peer
peer peer0 asn 64513 address 198.51.100.1
peer peer1 asn 64514 address 203.0.113.1
----

. Add routes to the remote BGP peers
+
In order to be able to establish connections to the remote BGP peers,
corresponding routes have to be added.
+
[literal,subs="quotes"]
----
midonet> router *_router0_* route add src 0.0.0.0/0 dst *_198.51.100.0/30_* port *_router0:port0_* type normal
router0:route0

midonet> router *_router0_* route add src 0.0.0.0/0 dst *_203.0.113.0/30_* port *_router0:port1_* type normal
router0:route1
----

. Advertise BGP routes
+
In order to provide external connectivity for hosted virtual machines, the
floating IP network has to be advertised to the BGP peers.
+
[literal,subs="quotes"]
----
midonet> router *_router0_* add bgp-network net *_192.0.2.0/24_*
router0:net0

midonet> router router0 list bgp-network
net net0 net 192.0.2.0/24
----

. Bind virtual ports to physical network interfaces
+
Bind the Edge Router's virtual ports to the physical network
interfaces on the Gateway Nodes.
+
[IMPORTANT]
Ensure that physical interfaces are in state `UP` and do not have an IP address
assigned.

.. List the MidoNet hosts and find the Gateway Nodes:
+
[literal,subs="quotes"]
----
midonet> host list
host *_host0_* name *_gateway1_* alive true
host *_host1_* name *_gateway2_* alive true
[...]
----
+
In this example the hosts are *_host0_* and *_host1_*.

.. List the Gateway Nodes' physical interfaces:
+
[literal,subs="quotes"]
----
midonet> host *_host0_* list interface
[...]
iface *_eth1_* host_id host0 status 3 addresses [] mac 01:02:03:04:05:06 mtu 1500 type Physical endpoint PHYSICAL
[...]

midonet> host *_host1_* list interface
[...]
iface *_eth1_* host_id host0 status 3 addresses [] mac 06:05:04:03:02:01 mtu 1500 type Physical endpoint PHYSICAL
[...]
----

.. Bind the physical host interfaces to the Edge Router's virtual
ports:
+
[literal,subs="quotes"]
----
midonet> host *_host0_* add binding port *_router0:port0_* interface *_eth1_*
host host0 interface eth1 port router0:port0

midonet> host *_host1_* add binding port *_router0:port1_* interface *_eth1_*
host host1 interface eth1 port router0:port1
----

.. Configure a stateful port group:
+
[literal,subs="quotes"]
----
midonet-cli> port-group create name uplink-spg stateful true
*_pgroup0_*
----

.. Add the ports to the port group:
+
[literal,subs="quotes"]
----
midonet> port-group *_pgroup0_* add member port *_router0:port0_*
port-group pgroup0 port router0:port0

midonet> port-group *_pgroup0_* add member port *_router0:port1_*
port-group pgroup0 port router0:port1

midonet> port-group pgroup0 list member
port-group pgroup0 port router0:port0
port-group pgroup0 port router0:port1
----
