[[establish_bgp_session]]
= BGPセッションの確立

このセクションは、BGPセッションの設定方法プロセスについて説明します。

BGPを設定する時に以下の情報があることを確認ください。

* BGPセッションを確立する仮想ルーターを持っているテナントID。通常このルーターは“MidoNetプロバイダールーター”で、使用されるテナントIDは”admin”です。

* BGPセッションのためのローカルとピアの自律システム（AS）番号。例では64512と64513を使用します。

* BGPピアのIPアドレス

* BGPピアにアドバタイズするルートのリスト

* “MidoNetプロバイダールーター”のUUID

事例では、仮想トポロジーにはひとつのポートにひとつのルーターが含まれています。

. midonet-cli を開始してプロバイダルーターを参照します
+
midonet-cliを開始するために、システムのプロンプトに以下を入力します。
+
[source]
$ midonet-cli
+
midonet> プロンプトが表示されますので、以下のコマンドを入力してください。
+
[source]
midonet> cleart
midonet> router list
router router0 name MidoNet Provider Router
+
cleartコマンドは、CLIにロードされているテナントを取り除きます。プロバイダールーターには
テナントIDが設定されていないので、テナントをまず最初に取り除く必要があります。

. アドミンテナントをロードする為に以下のコマンドを発行します。
+
[literal,subs="quotes"]
midonet> sett _admin_
+
_admin_ を、OpenStackにおけるアドミンテナントのIDに置換してください。
OpenStack Identity サービス（Keystone）からこのIDを取得することができます。
+
[source]
$ keystone tenant-list

. BGPセッションのための仮想ポートを作成します。
+
リモートルーターと、BGPコミュニケーションに使われる仮想ポートを作成する必要があります。
+
[source]
midonet> router router0 add port address 10.12.12.1 net 10.12.12.0/24
router0:port0
+
作成したポートを検証する為に、以下を入力ください。
+
[source]
midonet> router router0 list port
port port0 device router0 state up mac 02:47:98:a1:e5:f8 address 10.12.12.1 net 10.12.12.0/24

. BGPセッションを作成する前に、ルーターにAS番号を割り当てます。
+
[source]
midonet> router router0 set asn 64512
midonet> router router0 show
router router0 name MidoNet Provider Router state up asn 64512
midonet>
+
. 次に、ルーターのBGPピアを一覧表示します。
+
[source]
midonet> router router0 list bgp-peer
midonet>
+
まだBGPピアを追加していないため、このコマンドは何も出力しません。
下記のコマンドを使用し、BGPピアを追加します：
+
[source]
midonet> router router0 add bgp-peer asn 64513 address 10.12.12.2
router0:peer0
midonet> router router0 list bgp-peer
peer peer0 asn 64513 address 10.12.12.2
midonet>
+
MD5認証を追加する必要がある場合：
[source]
midonet> router router0 bgp-peer peer0 set password BGPPASSWORD
midonet>
+
MidoNetの構成で定義されたデフォルトタイマーより優先されるカスタムタイマーをこのセッションに
与えることができます。
[source]
midonet> router router0 bgp-peer peer0 set connect-retry 10
midonet> router router0 bgp-peer peer0 set hold-time 5
midonet> router router0 bgp-peer peer0 set keep-alive 5
midonet> router router0 list bgp-peer
peer peer0 asn 64513 address 10.12.12.2 keep-alive 5 hold-time 5 connect-retry 10
midonet>

. ルートをアドバタイズします。
+
この時点で、BGPセッション上でルートをアドバタイズできます。OpenStackの環境で、ホストになった仮想マシンに外部接続性を提供するために、BGP上のパブリックフローティングIPレンジをアドバタイズする必要があります。
+
[source]
midonet> router router0 add bgp-network net 192.168.12.0/24
router0:net0
midonet> router router0 list bgp-network
net net0 net 192.168.12.0/24

. ルーターのポートと物理ネットワークのインターフェースをバインドします。
+
BGPピアに接続する為にルーターポートを作成した場合は、ポートはネットワークインターフェースに繋がらない場合があります。アクティブな物理ネットワークインターフェースにバインドして、ポート（とそのBGPセッション）を利用可能にしてください。
+
このバインディングを作成する為に、ホストとネットワークのインターフェースを確認する必要があります。この情報を用いて、物理ネットワークインターフェースとポートをバインドしたり、BGPセッションをアクティベートするためのコマンドを活用します。
+
[NOTE]
仮想ポートにバインドしたいインターフェースにIPアドレスがないこと、そのインターフェースがアップされていることを確認してください。
+
最初にホストをリスト化します。
+
[source]
midonet> host list
host host0 name ip-10-152-161-111 alive true
host host1 name ip-10-164-23-206 alive true
+
ホストを見つけた後に、ネットワークインターフェースをリスト化できます。
+
[source]
midonet> host host0 list interface
iface midonet host_id host0 mac 6a:07:42:e2:6c:88 mtu 1500 type Virtual endpoint DATAPATH
iface lo host_id host0 addresses [u'127.0.0.1', u'0:0:0:0:0:0:0:1'] mac 00:00:00:00:00:00 mtu 16436 type Physical endpoint LOCALHOST
iface virbr0 host_id host0 addresses [u'192.168.122.1'] mac 46:0b:df:a4:91:65 mtu 1500 type Virtual endpoint UNKNOWN
iface osvm-ef97-16fc host_id host0 addresses [u'fe80:0:0:0:7cf9:8ff:fe60:54ff'] mac 7e:f9:08:60:54:ff mtu 1500 type Virtual endpoint DATAPATH
iface osvm-38d0-266a host_id host0 addresses [u'fe80:0:0:0:2034:f5ff:fe89:1b89'] mac 22:34:f5:89:1b:89 mtu 1500 type Virtual endpoint DATAPATH
iface eth0 host_id host0 addresses [u'10.152.161.111', u'fe80:0:0:0:2000:aff:fe98:a16f'] mac 22:00:0a:98:a1:6f mtu 1500 type Physical endpoint PHYSICAL
iface eth1 host_id host0 mac 22:00:0a:7a:b3:4e mtu 1500 type Physical endpoint PHYSICAL
+
この場合は、router0:port0をhost0上のeth1にバインドします。
 +
[source]
midonet> host host0 add binding port router0:port0 interface eth1
host host0 interface eth1 port router0:port0
+
この時点で、host0上でルーターポートはアクティベートされて、bgpdが起動します。
+
[NOTE]
router0とport0のエイリアスは、各midonet-cliセッションで、必要に応じて自動生成されます。これらのエイリアスを使って(UUIDsの替わりに)バインディングしたいとき場合は、midonet-cliは、現行のセッションでこれらのオブジェクトを“認識”する必要があります。その実現のために、それらをリストしてください。

= 同じルーターポート上の第2のセッションを追加する場合

第二のアップリンクルーターが利用可能である場合は、このルーターのポートに第二のBGPセッションを
追加する事が有用であり得ます。そうしますと、2つのメリットがあります。ルーターポートのバインディング
を所有しているホストは、両方のアップストリームルーター間で負荷を分散することができて、そのうちの
一方のみが故障した場合には切断されません。

同じルーターポートに第2のピアを追加するには、AS番号とIPアドレスを調整して、一つのピアの場合と同じ
コマンドを使用します。BGPセッションが確立されるルーターのポートは自動的にピアのIPアドレスに基づいて
選択されます。

上記の例に第2のピアを追加します：
[source]
midonet> router router0 add bgp-peer asn 64514 address 10.12.12.3
router0:peer1
midonet> router router0 list bgp-peer
peer peer0 asn 64513 address 10.12.12.2 keep-alive 5 hold-time 5 connect-retry 10
peer peer1 asn 64514 address 10.12.12.3
midonet>

= 第2のルーターポートにBGPセッションを追加する場合

アップストリーム側が単一のルーターポートのルーティングは、単一障害点であり、また、パフォーマンスの
ボトルネックである可能性がありますので、MidoNetの環境にNorth-Southトラフィックを処理する1つ以上
のホストを追加するのが賢明です。

解決策は、ルーターに2つ目の仮想ポートを追加し、別の物理ホストにバインドすることです。適切な
ルーティング設定で、MidoNetは2つのポート/ホスト間で送信トラフィックを分散し、
アップストリームルーターもMidoNetに向けたトラフィックを分散します。

最初のステップは、第2のルーターのポートを追加することです：

[source]
midonet> router router0 add port address 10.22.22.1 net 10.22.22.0/24
router0:port1
midonet>
midonet> router router0 list port
port port0 device router0 state up plugged no mac ac:ca:ba:ab:ed:b8 address 10.12.12.1 net 10.12.12.0/24
port port1 device router0 state up plugged no mac ac:ca:ba:5e:0a:02 address 10.22.22.1 net 10.22.22.0/24

新しいポートを介して到達可能であるBGPピアを追加することができます：

[source]
midonet> router router0 add bgp-peer asn 64515 address 10.22.22.2
router0:peer2
midonet> router router0 list bgp-peer
peer peer0 asn 64513 address 10.12.12.2 keep-alive 5 hold-time 5 connect-retry 10
peer peer1 asn 64514 address 10.12.12.3
peer peer2 asn 64515 address 10.22.22.2
midonet>

そして、別の物理ホストのNICに新しいポートをバインドします：

[source]
midonet> host host1 add binding port router0:port1 interface eth0
host host1 interface eth0 port router0:port1
midonet>

この時点で、host1のMidoNetエージェントが新しいルーターポートを起動し、10.22.22.2のピアと
通信するbgpdを設定します。

1つめのポートと同じく、10.22.22.0/24ネットワーク上の第二のBGPピアを追加すると、host1は2つの
アップストリームルーターの間でロードバランシングし、その2つのBGPピアの1つが故障した場合でも
ゲートウェイとして機能できます。
