////
// Note:
// This file is shared between the Operations Guide and the Quick Start Guides.
// It is located underneath the Operations Guide sources, the Quick Start Guide
// sources only contain a symbolic link to this file.
// Ref: https://midonet.atlassian.net/browse/MND-148
////
[[bgp_uplink_configuration]]
= BGP Uplink Configuration

MidoNet utilizes the Border Gateway Protocol (BGP) for external connectivity.

For production deployments it is strongly recommended to use BGP due to it's
scalability and redundancy.

For demo or POC environments, alternatively static routing can be used.

The following instructions assume below sample environment:

* One floating IP network
** _192.0.2.0/24_

* Two MidoNet gateway nodes
** _gateway1_, connecting to _bgp1_ via _eth1_
** _gateway2_, connecting to _bgp2_ via _eth1_

* Two remote BGP peers
** _bgp1_, _198.51.100.1_, AS _64513_
** _bgp2_, _203.0.113.1_, AS _64514_

* Corresponding MidoNet BGP peers
** _198.51.100.2_, AS _64512_
** _203.0.113.2_, AS _64512_

Follow these steps to configure the BGP uplinks.

. Launch the MidoNet CLI and find the Edge Router
+
[literal,subs="quotes"]
----
midonet-cli> router list
router *_router0_* name *Edge Router* state up
router router1 name Tenant Router state up infilter chain0 outfilter chain1
----
+
In this example the Edge Router is *_router0_*.

. Create and bind virtual ports for the BGP sessions
+
Refer to xref:edge_router_setup[] for instructions on how to create the
necessary ports and bind them to the Gateway hosts' physical network interfaces.
+
You can confirm the port configuration within MidoNet CLI by listing the Edge
Router's ports:
+
[literal,subs="quotes"]
----
midonet> router *_router0_* port list
port port0 device router0 state up mac fa:16:3e:11:11:11 addresses *_198.51.100.2/30_*
port port1 device router0 state up mac fa:16:3e:22:22:22 addresses *_203.0.113.2/30_*
[...]
----

. Configure basic BGP settings
+
[literal,subs="quotes"]
----
midonet> router *_router0_* set asn *_64512_*

midonet> router *_router0_* add bgp-peer asn *_64513_* address *_198.51.100.1_*
*_router0:peer0_*

midonet> router *_router0_* add bgp-peer asn *_64514_* address *_203.0.113.1_*
*_router0:peer1_*

midonet> router *_router0_* list bgp-peer
peer peer0 asn 64513 address 198.51.100.1
peer peer1 asn 64514 address 203.0.113.1
----

. If needed, configure MD5 authentication:
+
[literal,subs="quotes"]
----
midonet> router *_router0_* bgp-peer *_peer0_* set password *_BGP_PASSWORD_*
midonet> router *_router0_* bgp-peer *_peer1_* set password *_BGP_PASSWORD_*
----

. If needed, configure custom timers that will take precedence over the default
ones defined in the MidoNet configuration:
+
[literal,subs="quotes"]
midonet> router *_router0_* bgp-peer *_peer0_* set connect-retry 10
midonet> router *_router0_* bgp-peer *_peer0_* set hold-time 5
midonet> router *_router0_* bgp-peer *_peer0_* set keep-alive 5
midonet> router *_router0_* bgp-peer *_peer1_* set connect-retry 10
midonet> router *_router0_* bgp-peer *_peer1_* set hold-time 5
midonet> router *_router0_* bgp-peer *_peer1_* set keep-alive 5
midonet> router *_router0_* list bgp-peer
peer peer0 asn 64513 address 198.51.100.1 keep-alive 5 hold-time 5 connect-retry 10
peer peer1 asn 64514 address 203.0.113.1 keep-alive 5 hold-time 5 connect-retry 10

. Add routes to the remote BGP peers
+
In order to be able to establish connections to the remote BGP peers,
corresponding routes have to be added.
+
[literal,subs="quotes"]
----
midonet> router *_router0_* route add src 0.0.0.0/0 dst *_198.51.100.0/30_* port *_router0:port0_* type normal
router0:route0

midonet> router *_router0_* route add src 0.0.0.0/0 dst *_203.0.113.0/30_* port *_router0:port1_* type normal
router0:route1
----

. Advertise BGP routes
+
In order to provide external connectivity for hosted virtual machines, the
floating IP network has to be advertised to the BGP peers.
+
[literal,subs="quotes"]
----
midonet> router *_router0_* add bgp-network net *_192.0.2.0/24_*
router0:net0

midonet> router router0 list bgp-network
net net0 net 192.0.2.0/24
----
