[[bgp_failover]]
= BGP failover configuration on a BGP peer

The default BGP failover time is 2-3 minutes. However, you can reduce this time
by changing some parameters on both ends of the BGP session.

You must make the change in +mn-conf(1)+ on the MidoNet side, and the remote
end BGP peer configuration.

The basic BGP timers are 'keepalive' and 'holdtime'. By default, keepalive timer
is 60 seconds. The hold-down timer is, by convention, 3 times the keepalive
interval, 180 seconds. You can go as low as 1 and 3 seconds for these values,
but keep in mind that this may potentially result in the BGP session flapping.

Another important BGP timer that you can tweak is the BGP 'connect_retry' timer,
also called the 'connect' timer. You can use this timer to set the amount of
time between retries to establish a connection to configured peers which have
gone down for some reason.

The example below shows how to reduce the default BGP values to 1, 1, and 3
seconds, for keep-alive, hold-time, and connect-retry, respectively, on the BGP
peer's session end (e.g. Quagga or Cisco):

[source]
neighbor 192.0.2.1 timers 1 3
neighbor 192.0.2.1 timers connect 1

To match those settings you would have to set the following parameters on the
MidoNet end of the BGP session:

[source]
----
# bgpd
bgp_connect_retry=1
bgp_holdtime=3
bgp_keepalive=1
----
